/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  UpdateProfile200,
  UpdateProfileBody
} from '../model';

import { customFetch } from '.././mutator.ts';

export type updateProfileResponse200 = {
  data: UpdateProfile200
  status: 200
}

export type updateProfileResponse400 = {
  data: void
  status: 400
}

export type updateProfileResponseSuccess = (updateProfileResponse200) & {
  headers: Headers;
};
export type updateProfileResponseError = (updateProfileResponse400) & {
  headers: Headers;
};

export type updateProfileResponse = (updateProfileResponseSuccess | updateProfileResponseError)

export const getUpdateProfileUrl = () => {




  return `/api/app/account/profile`
}

export const updateProfile = async (updateProfileBody: UpdateProfileBody, options?: Parameters<typeof customFetch>[1]): Promise<updateProfileResponse> => {

  return customFetch<updateProfileResponse>(getUpdateProfileUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProfileBody)
  }
);}


