/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthLogin200,
  AuthLoginBody,
  AuthMe200,
  AuthSignup200,
  AuthSignupBody,
} from "../model";

import { customFetch } from ".././mutator";

export type authLoginResponse200 = {
  data: AuthLogin200;
  status: 200;
};

export type authLoginResponseSuccess = authLoginResponse200 & {
  headers: Headers;
};
export type authLoginResponse = authLoginResponseSuccess;

export const getAuthLoginUrl = () => {
  return `/auth/login`;
};

export const authLogin = async (
  authLoginBody: AuthLoginBody,
  options?: RequestInit,
): Promise<authLoginResponse> => {
  return customFetch<authLoginResponse>(getAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authLoginBody),
  });
};

export type authSignupResponse200 = {
  data: AuthSignup200;
  status: 200;
};

export type authSignupResponseSuccess = authSignupResponse200 & {
  headers: Headers;
};
export type authSignupResponse = authSignupResponseSuccess;

export const getAuthSignupUrl = () => {
  return `/auth/signup`;
};

export const authSignup = async (
  authSignupBody: AuthSignupBody,
  options?: RequestInit,
): Promise<authSignupResponse> => {
  return customFetch<authSignupResponse>(getAuthSignupUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authSignupBody),
  });
};

export type authMeResponse200 = {
  data: AuthMe200;
  status: 200;
};

export type authMeResponse401 = {
  data: void;
  status: 401;
};

export type authMeResponseSuccess = authMeResponse200 & {
  headers: Headers;
};
export type authMeResponseError = authMeResponse401 & {
  headers: Headers;
};

export type authMeResponse = authMeResponseSuccess | authMeResponseError;

export const getAuthMeUrl = () => {
  return `/auth/me`;
};

export const authMe = async (
  options?: RequestInit,
): Promise<authMeResponse> => {
  return customFetch<authMeResponse>(getAuthMeUrl(), {
    ...options,
    method: "GET",
  });
};

export type authLogoutResponse204 = {
  data: void;
  status: 204;
};

export type authLogoutResponseSuccess = authLogoutResponse204 & {
  headers: Headers;
};
export type authLogoutResponse = authLogoutResponseSuccess;

export const getAuthLogoutUrl = () => {
  return `/auth/logout`;
};

export const authLogout = async (
  options?: RequestInit,
): Promise<authLogoutResponse> => {
  return customFetch<authLogoutResponse>(getAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};
