/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthCheckResetLink200,
  AuthCheckResetLinkParams,
  AuthForgotPassword202,
  AuthForgotPasswordBody,
  AuthLogin200,
  AuthLoginBody,
  AuthMe200,
  AuthResetPassword200,
  AuthResetPasswordBody,
  AuthSignup200,
  AuthSignupBody
} from '../model';

import { customFetch } from '.././mutator.ts';

export type authLoginResponse200 = {
  data: AuthLogin200
  status: 200
}

export type authLoginResponseSuccess = (authLoginResponse200) & {
  headers: Headers;
};
;

export type authLoginResponse = (authLoginResponseSuccess)

export const getAuthLoginUrl = () => {




  return `/auth/login`
}

export const authLogin = async (authLoginBody: AuthLoginBody, options?: Parameters<typeof customFetch>[1]): Promise<authLoginResponse> => {

  return customFetch<authLoginResponse>(getAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authLoginBody)
  }
);}


export type authSignupResponse200 = {
  data: AuthSignup200
  status: 200
}

export type authSignupResponseSuccess = (authSignupResponse200) & {
  headers: Headers;
};
;

export type authSignupResponse = (authSignupResponseSuccess)

export const getAuthSignupUrl = () => {




  return `/auth/signup`
}

export const authSignup = async (authSignupBody: AuthSignupBody, options?: Parameters<typeof customFetch>[1]): Promise<authSignupResponse> => {

  return customFetch<authSignupResponse>(getAuthSignupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authSignupBody)
  }
);}


export type authMeResponse200 = {
  data: AuthMe200
  status: 200
}

export type authMeResponse401 = {
  data: void
  status: 401
}

export type authMeResponseSuccess = (authMeResponse200) & {
  headers: Headers;
};
export type authMeResponseError = (authMeResponse401) & {
  headers: Headers;
};

export type authMeResponse = (authMeResponseSuccess | authMeResponseError)

export const getAuthMeUrl = () => {




  return `/auth/me`
}

export const authMe = async ( options?: Parameters<typeof customFetch>[1]): Promise<authMeResponse> => {

  return customFetch<authMeResponse>(getAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type authLogoutResponse204 = {
  data: void
  status: 204
}

export type authLogoutResponseSuccess = (authLogoutResponse204) & {
  headers: Headers;
};
;

export type authLogoutResponse = (authLogoutResponseSuccess)

export const getAuthLogoutUrl = () => {




  return `/auth/logout`
}

export const authLogout = async ( options?: Parameters<typeof customFetch>[1]): Promise<authLogoutResponse> => {

  return customFetch<authLogoutResponse>(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


export type authForgotPasswordResponse202 = {
  data: AuthForgotPassword202
  status: 202
}

export type authForgotPasswordResponse429 = {
  data: void
  status: 429
}

export type authForgotPasswordResponseSuccess = (authForgotPasswordResponse202) & {
  headers: Headers;
};
export type authForgotPasswordResponseError = (authForgotPasswordResponse429) & {
  headers: Headers;
};

export type authForgotPasswordResponse = (authForgotPasswordResponseSuccess | authForgotPasswordResponseError)

export const getAuthForgotPasswordUrl = () => {




  return `/auth/password/forgot`
}

export const authForgotPassword = async (authForgotPasswordBody: AuthForgotPasswordBody, options?: Parameters<typeof customFetch>[1]): Promise<authForgotPasswordResponse> => {

  return customFetch<authForgotPasswordResponse>(getAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authForgotPasswordBody)
  }
);}


export type authCheckResetLinkResponse200 = {
  data: AuthCheckResetLink200
  status: 200
}

export type authCheckResetLinkResponseSuccess = (authCheckResetLinkResponse200) & {
  headers: Headers;
};
;

export type authCheckResetLinkResponse = (authCheckResetLinkResponseSuccess)

export const getAuthCheckResetLinkUrl = (params: AuthCheckResetLinkParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/password/reset?${stringifiedParams}` : `/auth/password/reset`
}

export const authCheckResetLink = async (params: AuthCheckResetLinkParams, options?: Parameters<typeof customFetch>[1]): Promise<authCheckResetLinkResponse> => {

  return customFetch<authCheckResetLinkResponse>(getAuthCheckResetLinkUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type authResetPasswordResponse200 = {
  data: AuthResetPassword200
  status: 200
}

export type authResetPasswordResponse400 = {
  data: void
  status: 400
}

export type authResetPasswordResponse410 = {
  data: void
  status: 410
}

export type authResetPasswordResponseSuccess = (authResetPasswordResponse200) & {
  headers: Headers;
};
export type authResetPasswordResponseError = (authResetPasswordResponse400 | authResetPasswordResponse410) & {
  headers: Headers;
};

export type authResetPasswordResponse = (authResetPasswordResponseSuccess | authResetPasswordResponseError)

export const getAuthResetPasswordUrl = () => {




  return `/auth/password/reset`
}

export const authResetPassword = async (authResetPasswordBody: AuthResetPasswordBody, options?: Parameters<typeof customFetch>[1]): Promise<authResetPasswordResponse> => {

  return customFetch<authResetPasswordResponse>(getAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authResetPasswordBody)
  }
);}


