/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateBillingCheckout200,
  CreateBillingCheckoutBody,
  CreateBillingPortal200,
  CreateBillingPortalBody,
  GetBillingStatus200
} from '../model';

import { customFetch } from '.././mutator.ts';

export type getBillingStatusResponse200 = {
  data: GetBillingStatus200
  status: 200
}

export type getBillingStatusResponseSuccess = (getBillingStatusResponse200) & {
  headers: Headers;
};
;

export type getBillingStatusResponse = (getBillingStatusResponseSuccess)

export const getGetBillingStatusUrl = () => {




  return `/api/app/billing/status`
}

export const getBillingStatus = async ( options?: Parameters<typeof customFetch>[1]): Promise<getBillingStatusResponse> => {

  return customFetch<getBillingStatusResponse>(getGetBillingStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type createBillingCheckoutResponse200 = {
  data: CreateBillingCheckout200
  status: 200
}

export type createBillingCheckoutResponseSuccess = (createBillingCheckoutResponse200) & {
  headers: Headers;
};
;

export type createBillingCheckoutResponse = (createBillingCheckoutResponseSuccess)

export const getCreateBillingCheckoutUrl = () => {




  return `/api/app/billing/checkout`
}

export const createBillingCheckout = async (createBillingCheckoutBody: CreateBillingCheckoutBody, options?: Parameters<typeof customFetch>[1]): Promise<createBillingCheckoutResponse> => {

  return customFetch<createBillingCheckoutResponse>(getCreateBillingCheckoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBillingCheckoutBody)
  }
);}


export type createBillingPortalResponse200 = {
  data: CreateBillingPortal200
  status: 200
}

export type createBillingPortalResponseSuccess = (createBillingPortalResponse200) & {
  headers: Headers;
};
;

export type createBillingPortalResponse = (createBillingPortalResponseSuccess)

export const getCreateBillingPortalUrl = () => {




  return `/api/app/billing/portal`
}

export const createBillingPortal = async (createBillingPortalBody: CreateBillingPortalBody, options?: Parameters<typeof customFetch>[1]): Promise<createBillingPortalResponse> => {

  return customFetch<createBillingPortalResponse>(getCreateBillingPortalUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBillingPortalBody)
  }
);}


