/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetOnboarding200
} from '../model';

import { customFetch } from '.././mutator.ts';

export type getOnboardingResponse200 = {
  data: GetOnboarding200
  status: 200
}

export type getOnboardingResponseSuccess = (getOnboardingResponse200) & {
  headers: Headers;
};
;

export type getOnboardingResponse = (getOnboardingResponseSuccess)

export const getGetOnboardingUrl = () => {




  return `/api/app/onboarding`
}

export const getOnboarding = async ( options?: Parameters<typeof customFetch>[1]): Promise<getOnboardingResponse> => {

  return customFetch<getOnboardingResponse>(getGetOnboardingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


