/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateWorkspace201,
  CreateWorkspaceBody,
  CreateWorkspaceDocument201,
  CreateWorkspaceDocumentBody,
  ListWorkspaces200
} from '../model';

import { customFetch } from '.././mutator.ts';

export type listWorkspacesResponse200 = {
  data: ListWorkspaces200
  status: 200
}

export type listWorkspacesResponseSuccess = (listWorkspacesResponse200) & {
  headers: Headers;
};
;

export type listWorkspacesResponse = (listWorkspacesResponseSuccess)

export const getListWorkspacesUrl = () => {




  return `/api/app/workspaces`
}

export const listWorkspaces = async ( options?: Parameters<typeof customFetch>[1]): Promise<listWorkspacesResponse> => {

  return customFetch<listWorkspacesResponse>(getListWorkspacesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type createWorkspaceResponse201 = {
  data: CreateWorkspace201
  status: 201
}

export type createWorkspaceResponseSuccess = (createWorkspaceResponse201) & {
  headers: Headers;
};
;

export type createWorkspaceResponse = (createWorkspaceResponseSuccess)

export const getCreateWorkspaceUrl = () => {




  return `/api/app/workspaces`
}

export const createWorkspace = async (createWorkspaceBody: CreateWorkspaceBody, options?: Parameters<typeof customFetch>[1]): Promise<createWorkspaceResponse> => {

  return customFetch<createWorkspaceResponse>(getCreateWorkspaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWorkspaceBody)
  }
);}


export type createWorkspaceDocumentResponse201 = {
  data: CreateWorkspaceDocument201
  status: 201
}

export type createWorkspaceDocumentResponseSuccess = (createWorkspaceDocumentResponse201) & {
  headers: Headers;
};
;

export type createWorkspaceDocumentResponse = (createWorkspaceDocumentResponseSuccess)

export const getCreateWorkspaceDocumentUrl = (workspace: string,) => {




  return `/api/app/workspaces/${workspace}/documents`
}

export const createWorkspaceDocument = async (workspace: string,
    createWorkspaceDocumentBody: CreateWorkspaceDocumentBody, options?: Parameters<typeof customFetch>[1]): Promise<createWorkspaceDocumentResponse> => {
    const formData = new FormData();
formData.append(`file`, createWorkspaceDocumentBody.file);
formData.append(`name`, createWorkspaceDocumentBody.name);
if(createWorkspaceDocumentBody.folder !== undefined) {
 formData.append(`folder`, createWorkspaceDocumentBody.folder);
 }

  return customFetch<createWorkspaceDocumentResponse>(getCreateWorkspaceDocumentUrl(workspace),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}


