/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateBinder201,
  CreateBinderBody,
  CreateBinderDocument201,
  CreateBinderDocumentBody,
  GetBinderDocument200,
  ListBinderDocuments200,
  ListBinders200,
  ListOrganizationBinders200
} from '../model';

import { customFetch } from '.././mutator.ts';

export type listBindersResponse200 = {
  data: ListBinders200
  status: 200
}

export type listBindersResponseSuccess = (listBindersResponse200) & {
  headers: Headers;
};
;

export type listBindersResponse = (listBindersResponseSuccess)

export const getListBindersUrl = () => {




  return `/api/app/binders`
}

export const listBinders = async ( options?: Parameters<typeof customFetch>[1]): Promise<listBindersResponse> => {

  return customFetch<listBindersResponse>(getListBindersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type listOrganizationBindersResponse200 = {
  data: ListOrganizationBinders200
  status: 200
}

export type listOrganizationBindersResponseSuccess = (listOrganizationBindersResponse200) & {
  headers: Headers;
};
;

export type listOrganizationBindersResponse = (listOrganizationBindersResponseSuccess)

export const getListOrganizationBindersUrl = (org: string,) => {




  return `/api/app/orgs/${org}/binders`
}

export const listOrganizationBinders = async (org: string, options?: Parameters<typeof customFetch>[1]): Promise<listOrganizationBindersResponse> => {

  return customFetch<listOrganizationBindersResponse>(getListOrganizationBindersUrl(org),
  {
    ...options,
    method: 'GET'


  }
);}


export type createBinderResponse201 = {
  data: CreateBinder201
  status: 201
}

export type createBinderResponseSuccess = (createBinderResponse201) & {
  headers: Headers;
};
;

export type createBinderResponse = (createBinderResponseSuccess)

export const getCreateBinderUrl = (org: string,) => {




  return `/api/app/orgs/${org}/binders`
}

export const createBinder = async (org: string,
    createBinderBody: CreateBinderBody, options?: Parameters<typeof customFetch>[1]): Promise<createBinderResponse> => {

  return customFetch<createBinderResponse>(getCreateBinderUrl(org),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBinderBody)
  }
);}


export type listBinderDocumentsResponse200 = {
  data: ListBinderDocuments200
  status: 200
}

export type listBinderDocumentsResponseSuccess = (listBinderDocumentsResponse200) & {
  headers: Headers;
};
;

export type listBinderDocumentsResponse = (listBinderDocumentsResponseSuccess)

export const getListBinderDocumentsUrl = (org: string,
    binder: string,) => {




  return `/api/app/binders/${org}/${binder}/documents`
}

export const listBinderDocuments = async (org: string,
    binder: string, options?: Parameters<typeof customFetch>[1]): Promise<listBinderDocumentsResponse> => {

  return customFetch<listBinderDocumentsResponse>(getListBinderDocumentsUrl(org,binder),
  {
    ...options,
    method: 'GET'


  }
);}


export type createBinderDocumentResponse201 = {
  data: CreateBinderDocument201
  status: 201
}

export type createBinderDocumentResponseSuccess = (createBinderDocumentResponse201) & {
  headers: Headers;
};
;

export type createBinderDocumentResponse = (createBinderDocumentResponseSuccess)

export const getCreateBinderDocumentUrl = (org: string,
    binder: string,) => {




  return `/api/app/binders/${org}/${binder}/documents`
}

export const createBinderDocument = async (org: string,
    binder: string,
    createBinderDocumentBody: CreateBinderDocumentBody, options?: Parameters<typeof customFetch>[1]): Promise<createBinderDocumentResponse> => {
    const formData = new FormData();
formData.append(`file`, createBinderDocumentBody.file);
formData.append(`name`, createBinderDocumentBody.name);
if(createBinderDocumentBody.folder !== undefined) {
 formData.append(`folder`, createBinderDocumentBody.folder);
 }

  return customFetch<createBinderDocumentResponse>(getCreateBinderDocumentUrl(org,binder),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}


export type getBinderDocumentResponse200 = {
  data: GetBinderDocument200
  status: 200
}

export type getBinderDocumentResponseSuccess = (getBinderDocumentResponse200) & {
  headers: Headers;
};
;

export type getBinderDocumentResponse = (getBinderDocumentResponseSuccess)

export const getGetBinderDocumentUrl = (org: string,
    binder: string,
    documentPath: string,) => {




  return `/api/app/binders/${org}/${binder}/documents/${documentPath}`
}

export const getBinderDocument = async (org: string,
    binder: string,
    documentPath: string, options?: Parameters<typeof customFetch>[1]): Promise<getBinderDocumentResponse> => {

  return customFetch<getBinderDocumentResponse>(getGetBinderDocumentUrl(org,binder,documentPath),
  {
    ...options,
    method: 'GET'


  }
);}


