/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation200Status } from './acceptInvitation200Status.ts';

export type AcceptInvitation200 = {
  status: AcceptInvitation200Status;
};
