/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type AcceptInvitation200Status = typeof AcceptInvitation200Status[keyof typeof AcceptInvitation200Status];


export const AcceptInvitation200Status = {
  pending: 'pending',
  accepted: 'accepted',
  joined: 'joined',
  revoked: 'revoked',
  expired: 'expired',
} as const;
