/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptLegal200OrganizationsItem } from './acceptLegal200OrganizationsItem.ts';

export type AcceptLegal200 = {
  version: string;
  person: boolean;
  organizations: AcceptLegal200OrganizationsItem[];
};
