/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddBinderPerson200GroupsItemMembersItem } from './addBinderPerson200GroupsItemMembersItem.ts';

export type AddBinderPerson200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: AddBinderPerson200GroupsItemMembersItem[];
};
