/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddBinderPerson200GroupsItem } from './addBinderPerson200GroupsItem.ts';
import type { AddBinderPerson200OrganizationMembersItem } from './addBinderPerson200OrganizationMembersItem.ts';
import type { AddBinderPerson200PeopleItem } from './addBinderPerson200PeopleItem.ts';

export type AddBinderPerson200 = {
  organization: string;
  workspace: string;
  people: AddBinderPerson200PeopleItem[];
  groups: AddBinderPerson200GroupsItem[];
  openToOrganization: boolean;
  organizationMembers: AddBinderPerson200OrganizationMembersItem[];
  canManage: boolean;
};
