/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type AddDocumentCollaboratorBodyPermission = typeof AddDocumentCollaboratorBodyPermission[keyof typeof AddDocumentCollaboratorBodyPermission];


export const AddDocumentCollaboratorBodyPermission = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
