/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddDocumentCollaborator200Collaborator } from "./addDocumentCollaborator200Collaborator";

export type AddDocumentCollaborator200 = {
  /** @nullable */
  collaborator?: AddDocumentCollaborator200Collaborator;
};
