/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddDocumentCollaborator200Collaborator } from './addDocumentCollaborator200Collaborator.ts';

export type AddDocumentCollaborator200 = {
  /** @nullable */
  collaborator?: AddDocumentCollaborator200Collaborator;
};
