/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type AddDocumentCollaborator200CollaboratorAccess = typeof AddDocumentCollaborator200CollaboratorAccess[keyof typeof AddDocumentCollaborator200CollaboratorAccess];


export const AddDocumentCollaborator200CollaboratorAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
