/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddDocumentCollaborator200CollaboratorAccess } from './addDocumentCollaborator200CollaboratorAccess.ts';
import type { AddDocumentCollaborator200CollaboratorUser } from './addDocumentCollaborator200CollaboratorUser.ts';

/**
 * @nullable
 */
export type AddDocumentCollaborator200Collaborator = {
  permission: string;
  access: AddDocumentCollaborator200CollaboratorAccess;
  permissionLabel: string;
  roleName: string;
  user: AddDocumentCollaborator200CollaboratorUser;
} | null;
