/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddOrganizationPerson200GroupsItem } from './addOrganizationPerson200GroupsItem.ts';
import type { AddOrganizationPerson200PeopleItem } from './addOrganizationPerson200PeopleItem.ts';

export type AddOrganizationPerson200 = {
  organization: string;
  people: AddOrganizationPerson200PeopleItem[];
  groups: AddOrganizationPerson200GroupsItem[];
  binders: string[];
  canManage: boolean;
  viewer: string;
};
