/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddOrganizationPerson200GroupsItemMembersItem } from './addOrganizationPerson200GroupsItemMembersItem.ts';

export type AddOrganizationPerson200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  memberCount: number;
  members: AddOrganizationPerson200GroupsItemMembersItem[];
  binders: string[];
};
