/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AddOrganizationGroupMember200GroupsItem } from './addOrganizationGroupMember200GroupsItem.ts';
import type { AddOrganizationGroupMember200PeopleItem } from './addOrganizationGroupMember200PeopleItem.ts';

export type AddOrganizationGroupMember200 = {
  organization: string;
  people: AddOrganizationGroupMember200PeopleItem[];
  groups: AddOrganizationGroupMember200GroupsItem[];
  canManage: boolean;
};
