/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type AdminSubscriptionAccessListPayloadUsersItemAccessSource = typeof AdminSubscriptionAccessListPayloadUsersItemAccessSource[keyof typeof AdminSubscriptionAccessListPayloadUsersItemAccessSource];


export const AdminSubscriptionAccessListPayloadUsersItemAccessSource = {
  config_bypass: 'config_bypass',
  stripe: 'stripe',
  admin_grant: 'admin_grant',
  admin_revoke: 'admin_revoke',
  none: 'none',
} as const;
