/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSubscriptionAccessListPayloadUsersItemAccessSource } from './adminSubscriptionAccessListPayloadUsersItemAccessSource.ts';
import type { AdminSubscriptionAccessListPayloadUsersItemOverride } from './adminSubscriptionAccessListPayloadUsersItemOverride.ts';

export type AdminSubscriptionAccessListPayloadUsersItem = {
  username: string;
  fullName?: string;
  email?: string;
  hasAccess: boolean;
  accessSource: AdminSubscriptionAccessListPayloadUsersItemAccessSource;
  /** @nullable */
  stripeStatus: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  /** @nullable */
  override: AdminSubscriptionAccessListPayloadUsersItemOverride;
};
