/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSubscriptionAccessListPayloadUsersItem } from './adminSubscriptionAccessListPayloadUsersItem';

export interface AdminSubscriptionAccessListPayload {
  users: AdminSubscriptionAccessListPayloadUsersItem[];
  page: number;
  limit: number;
  hasMore: boolean;
  query: string;
}
