/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type AdminSubscriptionAccessListPayloadUsersItemOverrideAccess = typeof AdminSubscriptionAccessListPayloadUsersItemOverrideAccess[keyof typeof AdminSubscriptionAccessListPayloadUsersItemOverrideAccess];


export const AdminSubscriptionAccessListPayloadUsersItemOverrideAccess = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
