/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSubscriptionAccessListPayloadUsersItemAccessSource } from "./adminSubscriptionAccessListPayloadUsersItemAccessSource";
import type { AdminSubscriptionAccessListPayloadUsersItemOverride } from "./adminSubscriptionAccessListPayloadUsersItemOverride";

export type AdminSubscriptionAccessListPayloadUsersItem = {
  username: string;
  fullName?: string;
  email?: string;
  hasAccess: boolean;
  accessSource: AdminSubscriptionAccessListPayloadUsersItemAccessSource;
  /** @nullable */
  stripeStatus: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  /** @nullable */
  override: AdminSubscriptionAccessListPayloadUsersItemOverride;
};
