/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSubscriptionAccessListPayloadUsersItemOverrideAccess } from './adminSubscriptionAccessListPayloadUsersItemOverrideAccess.ts';
import type { AdminSubscriptionAccessListPayloadUsersItemOverrideMode } from './adminSubscriptionAccessListPayloadUsersItemOverrideMode.ts';

/**
 * @nullable
 */
export type AdminSubscriptionAccessListPayloadUsersItemOverride = {
  access: AdminSubscriptionAccessListPayloadUsersItemOverrideAccess;
  mode?: AdminSubscriptionAccessListPayloadUsersItemOverrideMode;
  /** @nullable */
  reason?: string | null;
  updatedBy: string;
  updatedAt: number;
} | null;
