/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSubscriptionAccessListPayloadUsersItemOverrideAccess } from './adminSubscriptionAccessListPayloadUsersItemOverrideAccess.ts';

/**
 * @nullable
 */
export type AdminSubscriptionAccessListPayloadUsersItemOverride = {
  username: string;
  access: AdminSubscriptionAccessListPayloadUsersItemOverrideAccess;
  updatedBy: string;
  updatedAt: number;
} | null;
