/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ArchiveBinderDocumentBody = {
  documentPath: string;
  changeNumber?: number;
  draft?: boolean | string;
};
