/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ArchiveBinderDocument201 = {
  organization: string;
  workspace: string;
  branch: string;
  /** @nullable */
  changeNumber: number | null;
};
