/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthSignup200User } from './authSignup200User.ts';

export type AuthSignup200 = {
  /** @nullable */
  user: AuthSignup200User;
  /** @nullable */
  token: string | null;
};
