/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthResetPassword200User } from './authResetPassword200User.ts';

export type AuthResetPassword200 = {
  /** @nullable */
  user: AuthResetPassword200User;
  /** @nullable */
  token: string | null;
  /** @nullable */
  suggestedOrganizationName?: string | null;
};
