/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthMe200User } from './authMe200User.ts';

export type AuthMe200 = {
  /** @nullable */
  user: AuthMe200User;
  /** @nullable */
  token: string | null;
  /** @nullable */
  suggestedOrganizationName?: string | null;
};
