/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthLogin200User } from "./authLogin200User";

export type AuthLogin200 = {
  /** @nullable */
  user: AuthLogin200User;
  /** @nullable */
  token: string | null;
};
