/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type AuthLoginBody = {
  username?: string;
  email?: string;
  /** @minLength 1 */
  password: string;
  rememberMe?: boolean;
};
