/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { BillingStatusPayloadOverrideAccess } from './billingStatusPayloadOverrideAccess.ts';
import type { BillingStatusPayloadOverrideMode } from './billingStatusPayloadOverrideMode.ts';

/**
 * @nullable
 */
export type BillingStatusPayloadOverride = {
  access: BillingStatusPayloadOverrideAccess;
  mode?: BillingStatusPayloadOverrideMode;
  /** @nullable */
  reason?: string | null;
  updatedBy: string;
  updatedAt: number;
} | null;
