/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { BillingStatusPayloadOverrideAccess } from './billingStatusPayloadOverrideAccess.ts';

/**
 * @nullable
 */
export type BillingStatusPayloadOverride = {
  username: string;
  access: BillingStatusPayloadOverrideAccess;
  updatedBy: string;
  updatedAt: number;
} | null;
