/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { BillingStatusPayloadAccessSource } from './billingStatusPayloadAccessSource.ts';
import type { BillingStatusPayloadOrganization } from './billingStatusPayloadOrganization.ts';
import type { BillingStatusPayloadOverride } from './billingStatusPayloadOverride.ts';
import type { BillingStatusPayloadPlan } from './billingStatusPayloadPlan.ts';

export interface BillingStatusPayload {
  /** @nullable */
  organization: BillingStatusPayloadOrganization;
  /** @nullable */
  trialEndsAt: number | null;
  /** @nullable */
  status: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  hasAccess: boolean;
  /** @nullable */
  accessSource: BillingStatusPayloadAccessSource;
  /** @nullable */
  override: BillingStatusPayloadOverride;
  /** @nullable */
  plan: BillingStatusPayloadPlan;
}
