/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type BillingStatusPayloadAccessSource = typeof BillingStatusPayloadAccessSource[keyof typeof BillingStatusPayloadAccessSource] | null;


export const BillingStatusPayloadAccessSource = {
  config_bypass: 'config_bypass',
  stripe: 'stripe',
  trial: 'trial',
  admin_grant: 'admin_grant',
  admin_revoke: 'admin_revoke',
  no_organization: 'no_organization',
  none: 'none',
} as const;
