/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type BillingStatusPayloadOverrideMode = typeof BillingStatusPayloadOverrideMode[keyof typeof BillingStatusPayloadOverrideMode];


export const BillingStatusPayloadOverrideMode = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
