/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { BillingStatusPayloadAccessSource } from './billingStatusPayloadAccessSource';
import type { BillingStatusPayloadOverride } from './billingStatusPayloadOverride';
import type { BillingStatusPayloadPlan } from './billingStatusPayloadPlan';

export interface BillingStatusPayload {
  /** @nullable */
  status: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  hasAccess: boolean;
  /** @nullable */
  accessSource: BillingStatusPayloadAccessSource;
  /** @nullable */
  override: BillingStatusPayloadOverride;
  /** @nullable */
  plan: BillingStatusPayloadPlan;
}
