/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeUsername200User } from './changeUsername200User.ts';

export type ChangeUsername200 = {
  user: ChangeUsername200User;
};
