/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CollaboratorListPayloadCurrentUserPermissionAccess = typeof CollaboratorListPayloadCurrentUserPermissionAccess[keyof typeof CollaboratorListPayloadCurrentUserPermissionAccess];


export const CollaboratorListPayloadCurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
