/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CollaboratorListPayloadCollaboratorsItemAccess } from './collaboratorListPayloadCollaboratorsItemAccess.ts';
import type { CollaboratorListPayloadCollaboratorsItemUser } from './collaboratorListPayloadCollaboratorsItemUser.ts';

export type CollaboratorListPayloadCollaboratorsItem = {
  permission: string;
  access: CollaboratorListPayloadCollaboratorsItemAccess;
  permissionLabel: string;
  roleName: string;
  user: CollaboratorListPayloadCollaboratorsItemUser;
};
