/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CollaboratorListPayloadCurrentUserPermission = {
  permission: string;
  access: 'read' | 'write' | 'admin';
  permissionLabel: string;
  roleName: string;
  user: {
  id: number;
  login: string;
  full_name: string;
  email: string;
  avatar_url: string;
};
} | null;
