/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CollaboratorListPayloadCollaboratorsItem } from './collaboratorListPayloadCollaboratorsItem';
import type { CollaboratorListPayloadCurrentUserPermission } from './collaboratorListPayloadCurrentUserPermission';

export interface CollaboratorListPayload {
  collaborators: CollaboratorListPayloadCollaboratorsItem[];
  page: number;
  limit: number;
  hasMore: boolean;
  /** @nullable */
  currentUserPermission: CollaboratorListPayloadCurrentUserPermission;
}
