/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CollaboratorListPayloadCollaboratorsItem } from './collaboratorListPayloadCollaboratorsItem.ts';
import type { CollaboratorListPayloadCurrentUserPermission } from './collaboratorListPayloadCurrentUserPermission.ts';

export interface CollaboratorListPayload {
  collaborators: CollaboratorListPayloadCollaboratorsItem[];
  page: number;
  limit: number;
  hasMore: boolean;
  /** @nullable */
  currentUserPermission: CollaboratorListPayloadCurrentUserPermission;
}
