/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CollaboratorListPayloadCollaboratorsItemAccess =
  (typeof CollaboratorListPayloadCollaboratorsItemAccess)[keyof typeof CollaboratorListPayloadCollaboratorsItemAccess];

export const CollaboratorListPayloadCollaboratorsItemAccess = {
  read: "read",
  write: "write",
  admin: "admin",
} as const;
