/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CollaboratorListPayloadCurrentUserPermissionAccess } from './collaboratorListPayloadCurrentUserPermissionAccess.ts';
import type { CollaboratorListPayloadCurrentUserPermissionUser } from './collaboratorListPayloadCurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type CollaboratorListPayloadCurrentUserPermission = {
  permission: string;
  access: CollaboratorListPayloadCurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: CollaboratorListPayloadCurrentUserPermissionUser;
} | null;
