/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CollaboratorListPayloadCollaboratorsItemAccess } from './collaboratorListPayloadCollaboratorsItemAccess';
import type { CollaboratorListPayloadCollaboratorsItemUser } from './collaboratorListPayloadCollaboratorsItemUser';

export type CollaboratorListPayloadCollaboratorsItem = {
  permission: string;
  access: CollaboratorListPayloadCollaboratorsItemAccess;
  permissionLabel: string;
  roleName: string;
  user: CollaboratorListPayloadCollaboratorsItemUser;
};
