/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDocumentDiscussion201ThreadsItemCommentsItem } from './createDocumentDiscussion201ThreadsItemCommentsItem.ts';
import type { CreateDocumentDiscussion201ThreadsItemEventsItem } from './createDocumentDiscussion201ThreadsItemEventsItem.ts';
import type { CreateDocumentDiscussion201ThreadsItemOrigin } from './createDocumentDiscussion201ThreadsItemOrigin.ts';
import type { CreateDocumentDiscussion201ThreadsItemReactionsItem } from './createDocumentDiscussion201ThreadsItemReactionsItem.ts';
import type { CreateDocumentDiscussion201ThreadsItemResolvedBy } from './createDocumentDiscussion201ThreadsItemResolvedBy.ts';

export type CreateDocumentDiscussion201ThreadsItem = {
  id: string;
  origin: CreateDocumentDiscussion201ThreadsItemOrigin;
  comments: CreateDocumentDiscussion201ThreadsItemCommentsItem[];
  events: CreateDocumentDiscussion201ThreadsItemEventsItem[];
  reactions: CreateDocumentDiscussion201ThreadsItemReactionsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: CreateDocumentDiscussion201ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
