/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBinderChangeDiscussion201ThreadsItemCommentsItemAuthor } from './createBinderChangeDiscussion201ThreadsItemCommentsItemAuthor.ts';
import type { CreateBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem } from './createBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem.ts';

export type CreateBinderChangeDiscussion201ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: CreateBinderChangeDiscussion201ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: CreateBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem[];
};
