/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationInvitationBodyLevel } from './createOrganizationInvitationBodyLevel.ts';

export type CreateOrganizationInvitationBody = {
  /** @minLength 1 */
  email: string;
  owner?: boolean;
  binder?: string;
  level?: CreateOrganizationInvitationBodyLevel;
};
