/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateDocumentDiscussion201ThreadsItemOrigin = typeof CreateDocumentDiscussion201ThreadsItemOrigin[keyof typeof CreateDocumentDiscussion201ThreadsItemOrigin];


export const CreateDocumentDiscussion201ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
