/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemContent } from './createBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemContent.ts';
import type { CreateBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem } from './createBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type CreateBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem = {
  content: CreateBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: CreateBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem[];
};
