/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateDocumentBody = {
  /** File upload */
  file?: unknown | null;
  repoName: string;
  nextVersion: string;
  requiredApprovals?: string;
  description?: string;
};
