/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBinderChangeDiscussion201ThreadsItem } from './createBinderChangeDiscussion201ThreadsItem.ts';

export type CreateBinderChangeDiscussion201 = {
  threads: CreateBinderChangeDiscussion201ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
