/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganization201Organization = {
  id: number;
  name: string;
  displayName: string;
  workspace: string;
  /** @nullable */
  trialEndsAt: number | null;
};
