/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateWorkspace201Workspace } from './createWorkspace201Workspace.ts';

export type CreateWorkspace201 = {
  workspace: CreateWorkspace201Workspace;
};
