/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateOrganizationInvitation201InvitationBinderLevel = typeof CreateOrganizationInvitation201InvitationBinderLevel[keyof typeof CreateOrganizationInvitation201InvitationBinderLevel] | null;


export const CreateOrganizationInvitation201InvitationBinderLevel = {
  admin: 'admin',
  editor: 'editor',
  reviewer: 'reviewer',
} as const;
