/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateOrganizationInvitation200InvitationBinderLevel = typeof CreateOrganizationInvitation200InvitationBinderLevel[keyof typeof CreateOrganizationInvitation200InvitationBinderLevel] | null;


export const CreateOrganizationInvitation200InvitationBinderLevel = {
  admin: 'admin',
  editor: 'editor',
  reviewer: 'reviewer',
} as const;
