/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateWorkspaceDocument201 = {
  organization: string;
  workspace: string;
  documentPath: string;
  slugPath: string;
  branch: string;
  /** @nullable */
  pullRequestNumber: number | null;
};
