/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent } from './createDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent.ts';
import type { CreateDocumentDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem } from './createDocumentDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type CreateDocumentDiscussion201ThreadsItemCommentsItemReactionsItem = {
  content: CreateDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: CreateDocumentDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem[];
};
