/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDocument200RepositoryOwner } from "./createDocument200RepositoryOwner";

export type CreateDocument200Repository = {
  id: number;
  name: string;
  full_name: string;
  description: string;
  updated_at: string;
  owner: CreateDocument200RepositoryOwner;
};
