/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDocumentDiscussion201ThreadsItem } from './createDocumentDiscussion201ThreadsItem.ts';

export type CreateDocumentDiscussion201 = {
  threads: CreateDocumentDiscussion201ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
