/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationInvitation200Invitation } from './createOrganizationInvitation200Invitation.ts';

export type CreateOrganizationInvitation200 = {
  invitation: CreateOrganizationInvitation200Invitation;
};
