/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationGroup201GroupMembersItem } from './createOrganizationGroup201GroupMembersItem.ts';

export type CreateOrganizationGroup201Group = {
  id: number;
  name: string;
  description: string;
  access: string;
  memberCount: number;
  members: CreateOrganizationGroup201GroupMembersItem[];
  binders: string[];
};
