/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationInvitation201InvitationBinderLevel } from './createOrganizationInvitation201InvitationBinderLevel.ts';
import type { CreateOrganizationInvitation201InvitationOrgRole } from './createOrganizationInvitation201InvitationOrgRole.ts';
import type { CreateOrganizationInvitation201InvitationStatus } from './createOrganizationInvitation201InvitationStatus.ts';

export type CreateOrganizationInvitation201Invitation = {
  id: string;
  email: string;
  orgRole: CreateOrganizationInvitation201InvitationOrgRole;
  /** @nullable */
  binder: string | null;
  /** @nullable */
  binderLevel: CreateOrganizationInvitation201InvitationBinderLevel;
  grant: string;
  invitedBy: string;
  createdAt: number;
  expiresAt: number;
  status: CreateOrganizationInvitation201InvitationStatus;
};
