/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBinderChangeDiscussion201ThreadsItemCommentsItem } from './createBinderChangeDiscussion201ThreadsItemCommentsItem.ts';
import type { CreateBinderChangeDiscussion201ThreadsItemEventsItem } from './createBinderChangeDiscussion201ThreadsItemEventsItem.ts';
import type { CreateBinderChangeDiscussion201ThreadsItemOrigin } from './createBinderChangeDiscussion201ThreadsItemOrigin.ts';
import type { CreateBinderChangeDiscussion201ThreadsItemResolvedBy } from './createBinderChangeDiscussion201ThreadsItemResolvedBy.ts';

export type CreateBinderChangeDiscussion201ThreadsItem = {
  id: string;
  origin: CreateBinderChangeDiscussion201ThreadsItemOrigin;
  comments: CreateBinderChangeDiscussion201ThreadsItemCommentsItem[];
  events: CreateBinderChangeDiscussion201ThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: CreateBinderChangeDiscussion201ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
