/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganizationInvitation201InvitationOrgRole = typeof CreateOrganizationInvitation201InvitationOrgRole[keyof typeof CreateOrganizationInvitation201InvitationOrgRole];


export const CreateOrganizationInvitation201InvitationOrgRole = {
  owner: 'owner',
  member: 'member',
} as const;
