/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateDocumentBody = {
  /** File upload */
  file: Blob;
  repoName: string;
  nextVersion: string;
  requiredApprovals?: string;
  description?: string;
};
