/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBinderChangeDiscussion201ThreadsItemEventsItemActor } from './createBinderChangeDiscussion201ThreadsItemEventsItemActor.ts';

export type CreateBinderChangeDiscussion201ThreadsItemEventsItem = {
  id: number;
  actor: CreateBinderChangeDiscussion201ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
