/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBillingCheckoutBodyIntent } from './createBillingCheckoutBodyIntent.ts';

export type CreateBillingCheckoutBody = {
  idempotencyKey: string;
  intent?: CreateBillingCheckoutBodyIntent;
};
