/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationInvitation201Invitation } from './createOrganizationInvitation201Invitation.ts';

export type CreateOrganizationInvitation201 = {
  invitation: CreateOrganizationInvitation201Invitation;
};
