/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganizationInvitation201InvitationStatus = typeof CreateOrganizationInvitation201InvitationStatus[keyof typeof CreateOrganizationInvitation201InvitationStatus];


export const CreateOrganizationInvitation201InvitationStatus = {
  pending: 'pending',
  accepted: 'accepted',
  joined: 'joined',
  revoked: 'revoked',
  expired: 'expired',
} as const;
