/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDocument200Repository } from './createDocument200Repository';

export type CreateDocument200 = {
  repository: CreateDocument200Repository;
  owner: string;
  repo: string;
  canonicalFile: string;
  prNumber: number;
  prTitle: string;
  branchName: string;
  commitSha: string;
};
