/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganizationInvitation200InvitationStatus = typeof CreateOrganizationInvitation200InvitationStatus[keyof typeof CreateOrganizationInvitation200InvitationStatus];


export const CreateOrganizationInvitation200InvitationStatus = {
  pending: 'pending',
  accepted: 'accepted',
  joined: 'joined',
  revoked: 'revoked',
  expired: 'expired',
} as const;
