/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationGroup201Group } from './createOrganizationGroup201Group.ts';

export type CreateOrganizationGroup201 = {
  organization: string;
  group: CreateOrganizationGroup201Group;
};
