/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDocumentDiscussion201ThreadsItemEventsItemActor } from './createDocumentDiscussion201ThreadsItemEventsItemActor.ts';

export type CreateDocumentDiscussion201ThreadsItemEventsItem = {
  id: number;
  actor: CreateDocumentDiscussion201ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
