/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateBinderFolder201 = {
  organization: string;
  workspace: string;
  branch: string;
  changeNumber: number;
};
