/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationInvitation200InvitationBinderLevel } from './createOrganizationInvitation200InvitationBinderLevel.ts';
import type { CreateOrganizationInvitation200InvitationOrgRole } from './createOrganizationInvitation200InvitationOrgRole.ts';
import type { CreateOrganizationInvitation200InvitationStatus } from './createOrganizationInvitation200InvitationStatus.ts';

export type CreateOrganizationInvitation200Invitation = {
  id: string;
  email: string;
  orgRole: CreateOrganizationInvitation200InvitationOrgRole;
  /** @nullable */
  binder: string | null;
  /** @nullable */
  binderLevel: CreateOrganizationInvitation200InvitationBinderLevel;
  grant: string;
  invitedBy: string;
  createdAt: number;
  expiresAt: number;
  status: CreateOrganizationInvitation200InvitationStatus;
};
