/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateOrganizationInvitation200InvitationOrgRole = typeof CreateOrganizationInvitation200InvitationOrgRole[keyof typeof CreateOrganizationInvitation200InvitationOrgRole];


export const CreateOrganizationInvitation200InvitationOrgRole = {
  owner: 'owner',
  member: 'member',
} as const;
