/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBinder201Workspace } from './createBinder201Workspace.ts';

export type CreateBinder201 = {
  workspace: CreateBinder201Workspace;
};
