/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type CreateBinderChangeDiscussion201ThreadsItemOrigin = typeof CreateBinderChangeDiscussion201ThreadsItemOrigin[keyof typeof CreateBinderChangeDiscussion201ThreadsItemOrigin];


export const CreateBinderChangeDiscussion201ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
