/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDocumentDiscussion201ThreadsItemCommentsItemAuthor } from './createDocumentDiscussion201ThreadsItemCommentsItemAuthor.ts';

export type CreateDocumentDiscussion201ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: CreateDocumentDiscussion201ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
};
