/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganization201Organization } from './createOrganization201Organization.ts';

export type CreateOrganization201 = {
  organization: CreateOrganization201Organization;
};
