/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export interface DeleteAccountBody {
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  confirm: string;
}

export type DeleteAccountBody = {
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  confirm: string;
};
