/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DiscussionSummaryThreadsItemCommentsItemAuthor } from './discussionSummaryThreadsItemCommentsItemAuthor.ts';
import type { DiscussionSummaryThreadsItemCommentsItemReactionsItem } from './discussionSummaryThreadsItemCommentsItemReactionsItem.ts';

export type DiscussionSummaryThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: DiscussionSummaryThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: DiscussionSummaryThreadsItemCommentsItemReactionsItem[];
};
