/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DiscussionSummaryThreadsItemCommentsItem } from './discussionSummaryThreadsItemCommentsItem.ts';
import type { DiscussionSummaryThreadsItemEventsItem } from './discussionSummaryThreadsItemEventsItem.ts';
import type { DiscussionSummaryThreadsItemOrigin } from './discussionSummaryThreadsItemOrigin.ts';
import type { DiscussionSummaryThreadsItemResolvedBy } from './discussionSummaryThreadsItemResolvedBy.ts';

export type DiscussionSummaryThreadsItem = {
  id: string;
  origin: DiscussionSummaryThreadsItemOrigin;
  comments: DiscussionSummaryThreadsItemCommentsItem[];
  events: DiscussionSummaryThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: DiscussionSummaryThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
