/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DiscussionSummaryThreadsItem } from './discussionSummaryThreadsItem.ts';

export interface DiscussionSummary {
  threads: DiscussionSummaryThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
}
