/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type DiscussionSummaryThreadsItemOrigin = typeof DiscussionSummaryThreadsItemOrigin[keyof typeof DiscussionSummaryThreadsItemOrigin];


export const DiscussionSummaryThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
