/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DiscussionSummaryThreadsItemEventsItemActor } from './discussionSummaryThreadsItemEventsItemActor.ts';

export type DiscussionSummaryThreadsItemEventsItem = {
  id: number;
  actor: DiscussionSummaryThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
