/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DiscussionSummaryThreadsItemCommentsItemReactionsItemContent } from './discussionSummaryThreadsItemCommentsItemReactionsItemContent.ts';
import type { DiscussionSummaryThreadsItemCommentsItemReactionsItemUsersItem } from './discussionSummaryThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type DiscussionSummaryThreadsItemCommentsItemReactionsItem = {
  content: DiscussionSummaryThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: DiscussionSummaryThreadsItemCommentsItemReactionsItemUsersItem[];
};
