/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentPermissionsPayloadCurrentUserPermissionAccess } from './documentPermissionsPayloadCurrentUserPermissionAccess.ts';
import type { DocumentPermissionsPayloadCurrentUserPermissionUser } from './documentPermissionsPayloadCurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type DocumentPermissionsPayloadCurrentUserPermission = {
  permission: string;
  access: DocumentPermissionsPayloadCurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: DocumentPermissionsPayloadCurrentUserPermissionUser;
} | null;
