/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentDetailPayloadUploadPullRequestsItemReviewersItemStatus = typeof DocumentDetailPayloadUploadPullRequestsItemReviewersItemStatus[keyof typeof DocumentDetailPayloadUploadPullRequestsItemReviewersItemStatus];


export const DocumentDetailPayloadUploadPullRequestsItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
