/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadUploadPullRequestsItemReviewersItemStatus } from './documentDetailPayloadUploadPullRequestsItemReviewersItemStatus.ts';

export type DocumentDetailPayloadUploadPullRequestsItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: DocumentDetailPayloadUploadPullRequestsItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
