/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadOpenPullRequestsItemApprovalState } from './documentDetailPayloadOpenPullRequestsItemApprovalState.ts';
import type { DocumentDetailPayloadOpenPullRequestsItemAssignee } from './documentDetailPayloadOpenPullRequestsItemAssignee.ts';
import type { DocumentDetailPayloadOpenPullRequestsItemReviewersItem } from './documentDetailPayloadOpenPullRequestsItemReviewersItem.ts';
import type { DocumentDetailPayloadOpenPullRequestsItemReviewsItem } from './documentDetailPayloadOpenPullRequestsItemReviewsItem.ts';
import type { DocumentDetailPayloadOpenPullRequestsItemUser } from './documentDetailPayloadOpenPullRequestsItemUser.ts';

export type DocumentDetailPayloadOpenPullRequestsItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  requiredApprovals: number;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: DocumentDetailPayloadOpenPullRequestsItemReviewersItem[];
  /** @nullable */
  assignee: DocumentDetailPayloadOpenPullRequestsItemAssignee;
  body?: string;
  approvalState: DocumentDetailPayloadOpenPullRequestsItemApprovalState;
  /** @nullable */
  user?: DocumentDetailPayloadOpenPullRequestsItemUser;
  reviews?: DocumentDetailPayloadOpenPullRequestsItemReviewsItem[];
};
