/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadUploadPullRequestsItemApprovalState } from './documentDetailPayloadUploadPullRequestsItemApprovalState.ts';
import type { DocumentDetailPayloadUploadPullRequestsItemAssignee } from './documentDetailPayloadUploadPullRequestsItemAssignee.ts';
import type { DocumentDetailPayloadUploadPullRequestsItemReviewersItem } from './documentDetailPayloadUploadPullRequestsItemReviewersItem.ts';
import type { DocumentDetailPayloadUploadPullRequestsItemReviewsItem } from './documentDetailPayloadUploadPullRequestsItemReviewsItem.ts';
import type { DocumentDetailPayloadUploadPullRequestsItemUser } from './documentDetailPayloadUploadPullRequestsItemUser.ts';

export type DocumentDetailPayloadUploadPullRequestsItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: DocumentDetailPayloadUploadPullRequestsItemReviewersItem[];
  /** @nullable */
  assignee: DocumentDetailPayloadUploadPullRequestsItemAssignee;
  body?: string;
  approvalState: DocumentDetailPayloadUploadPullRequestsItemApprovalState;
  /** @nullable */
  user?: DocumentDetailPayloadUploadPullRequestsItemUser;
  reviews?: DocumentDetailPayloadUploadPullRequestsItemReviewsItem[];
};
