/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentHistoryPayloadCanonicalFile } from './documentHistoryPayloadCanonicalFile.ts';
import type { DocumentHistoryPayloadVersionsItem } from './documentHistoryPayloadVersionsItem.ts';

export interface DocumentHistoryPayload {
  versions: DocumentHistoryPayloadVersionsItem[];
  /** @nullable */
  canonicalFile: DocumentHistoryPayloadCanonicalFile;
}
