/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentHistoryPayloadVersionsItemReviewsItemAuthor } from './documentHistoryPayloadVersionsItemReviewsItemAuthor.ts';
import type { DocumentHistoryPayloadVersionsItemReviewsItemState } from './documentHistoryPayloadVersionsItemReviewsItemState.ts';

export type DocumentHistoryPayloadVersionsItemReviewsItem = {
  id: number;
  author: DocumentHistoryPayloadVersionsItemReviewsItemAuthor;
  state: DocumentHistoryPayloadVersionsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
