/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadCurrentUserPermissionAccess } from './documentDetailPayloadCurrentUserPermissionAccess.ts';
import type { DocumentDetailPayloadCurrentUserPermissionUser } from './documentDetailPayloadCurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type DocumentDetailPayloadCurrentUserPermission = {
  permission: string;
  access: DocumentDetailPayloadCurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: DocumentDetailPayloadCurrentUserPermissionUser;
} | null;
