/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentDetailPayloadUploadPullRequestsItemApprovalState = typeof DocumentDetailPayloadUploadPullRequestsItemApprovalState[keyof typeof DocumentDetailPayloadUploadPullRequestsItemApprovalState];


export const DocumentDetailPayloadUploadPullRequestsItemApprovalState = {
  working: 'working',
  in_review: 'in_review',
  changes_requested: 'changes_requested',
  approved: 'approved',
  published: 'published',
} as const;
