/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadBranchProtection } from './documentDetailPayloadBranchProtection.ts';
import type { DocumentDetailPayloadCanonicalFile } from './documentDetailPayloadCanonicalFile.ts';
import type { DocumentDetailPayloadCurrentUserPermission } from './documentDetailPayloadCurrentUserPermission.ts';
import type { DocumentDetailPayloadLatestTag } from './documentDetailPayloadLatestTag.ts';
import type { DocumentDetailPayloadOpenPullRequestsItem } from './documentDetailPayloadOpenPullRequestsItem.ts';
import type { DocumentDetailPayloadRepository } from './documentDetailPayloadRepository.ts';
import type { DocumentDetailPayloadReviewSettings } from './documentDetailPayloadReviewSettings.ts';
import type { DocumentDetailPayloadTagsItem } from './documentDetailPayloadTagsItem.ts';
import type { DocumentDetailPayloadUploadPullRequestsItem } from './documentDetailPayloadUploadPullRequestsItem.ts';

export interface DocumentDetailPayload {
  repository: DocumentDetailPayloadRepository;
  tags: DocumentDetailPayloadTagsItem[];
  /** @nullable */
  latestTag: DocumentDetailPayloadLatestTag;
  openPullRequests: DocumentDetailPayloadOpenPullRequestsItem[];
  uploadPullRequests: DocumentDetailPayloadUploadPullRequestsItem[];
  /** @nullable */
  branchProtection: DocumentDetailPayloadBranchProtection;
  /** @nullable */
  reviewSettings?: DocumentDetailPayloadReviewSettings;
  /** @nullable */
  canonicalFile: DocumentDetailPayloadCanonicalFile;
  /** @nullable */
  currentUserPermission: DocumentDetailPayloadCurrentUserPermission;
}
