/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadOpenPullRequestsItemReviewersItemStatus } from './documentDetailPayloadOpenPullRequestsItemReviewersItemStatus.ts';

export type DocumentDetailPayloadOpenPullRequestsItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: DocumentDetailPayloadOpenPullRequestsItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
