/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadOpenPullRequestsItemReviewsItemAuthor } from './documentDetailPayloadOpenPullRequestsItemReviewsItemAuthor.ts';
import type { DocumentDetailPayloadOpenPullRequestsItemReviewsItemState } from './documentDetailPayloadOpenPullRequestsItemReviewsItemState.ts';

export type DocumentDetailPayloadOpenPullRequestsItemReviewsItem = {
  id: number;
  author: DocumentDetailPayloadOpenPullRequestsItemReviewsItemAuthor;
  state: DocumentDetailPayloadOpenPullRequestsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
