/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentDetailPayloadUploadPullRequestsItemReviewsItemAuthor } from './documentDetailPayloadUploadPullRequestsItemReviewsItemAuthor.ts';
import type { DocumentDetailPayloadUploadPullRequestsItemReviewsItemState } from './documentDetailPayloadUploadPullRequestsItemReviewsItemState.ts';

export type DocumentDetailPayloadUploadPullRequestsItemReviewsItem = {
  id: number;
  author: DocumentDetailPayloadUploadPullRequestsItemReviewsItemAuthor;
  state: DocumentDetailPayloadUploadPullRequestsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
