/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentPermissionsPayloadCurrentUserPermissionAccess = typeof DocumentPermissionsPayloadCurrentUserPermissionAccess[keyof typeof DocumentPermissionsPayloadCurrentUserPermissionAccess];


export const DocumentPermissionsPayloadCurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
