/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentSearchResultsPayloadDocumentsItem } from './documentSearchResultsPayloadDocumentsItem.ts';

export interface DocumentSearchResultsPayload {
  documents: DocumentSearchResultsPayloadDocumentsItem[];
  page: number;
  limit: number;
  hasMore: boolean;
}
