/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentPermissionsPayloadBranchProtection } from './documentPermissionsPayloadBranchProtection.ts';
import type { DocumentPermissionsPayloadCurrentUserPermission } from './documentPermissionsPayloadCurrentUserPermission.ts';
import type { DocumentPermissionsPayloadReviewSettings } from './documentPermissionsPayloadReviewSettings.ts';

export interface DocumentPermissionsPayload {
  /** @nullable */
  branchProtection: DocumentPermissionsPayloadBranchProtection;
  isPrivate: boolean;
  isInternal: boolean;
  /** @nullable */
  currentUserPermission?: DocumentPermissionsPayloadCurrentUserPermission;
  /** @nullable */
  reviewSettings?: DocumentPermissionsPayloadReviewSettings;
}
