/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentPermissionsPayloadBranchProtection } from "./documentPermissionsPayloadBranchProtection";
import type { DocumentPermissionsPayloadCurrentUserPermission } from "./documentPermissionsPayloadCurrentUserPermission";

export interface DocumentPermissionsPayload {
  /** @nullable */
  branchProtection: DocumentPermissionsPayloadBranchProtection;
  isPrivate: boolean;
  isInternal: boolean;
  /** @nullable */
  currentUserPermission?: DocumentPermissionsPayloadCurrentUserPermission;
}
