/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentDetailPayloadCurrentUserPermissionAccess = typeof DocumentDetailPayloadCurrentUserPermissionAccess[keyof typeof DocumentDetailPayloadCurrentUserPermissionAccess];


export const DocumentDetailPayloadCurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
