/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentHistoryPayloadVersionsItemReviewsItem } from './documentHistoryPayloadVersionsItemReviewsItem.ts';
import type { DocumentHistoryPayloadVersionsItemSubmission } from './documentHistoryPayloadVersionsItemSubmission.ts';

export type DocumentHistoryPayloadVersionsItem = {
  version: number;
  tagName: string;
  sha: string;
  createdAt: string;
  /** @nullable */
  submission: DocumentHistoryPayloadVersionsItemSubmission;
  reviews: DocumentHistoryPayloadVersionsItemReviewsItem[];
  discussionCount: number;
};
