/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportBinderDocumentFormat } from './exportBinderDocumentFormat.ts';

export type ExportBinderDocumentParams = {
format: ExportBinderDocumentFormat;
ref?: string;
};
