/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ExportBinderDocumentFormat = typeof ExportBinderDocumentFormat[keyof typeof ExportBinderDocumentFormat];


export const ExportBinderDocumentFormat = {
  pdf: 'pdf',
  docx: 'docx',
} as const;
