/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetBillingStatus200AccessSource = typeof GetBillingStatus200AccessSource[keyof typeof GetBillingStatus200AccessSource] | null;


export const GetBillingStatus200AccessSource = {
  config_bypass: 'config_bypass',
  stripe: 'stripe',
  admin_grant: 'admin_grant',
  admin_revoke: 'admin_revoke',
  none: 'none',
} as const;
