/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBillingStatus200AccessSource } from './getBillingStatus200AccessSource';
import type { GetBillingStatus200Override } from './getBillingStatus200Override';
import type { GetBillingStatus200Plan } from './getBillingStatus200Plan';

export type GetBillingStatus200 = {
  /** @nullable */
  status: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  hasAccess: boolean;
  /** @nullable */
  accessSource: GetBillingStatus200AccessSource;
  /** @nullable */
  override: GetBillingStatus200Override;
  /** @nullable */
  plan: GetBillingStatus200Plan;
};
