/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderSettings200SignOffRulesItemScope } from './getBinderSettings200SignOffRulesItemScope.ts';

export type GetBinderSettings200SignOffRulesItem = {
  scope: GetBinderSettings200SignOffRulesItemScope;
  target: string;
  teams: string[];
  users: string[];
};
