/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderSettings200SignOffDocumentsItem = {
  uid: string;
  slugPath: string;
  name: string;
  folder: string;
};
