/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderChange200ChangeReviewersItemStatus = typeof GetBinderChange200ChangeReviewersItemStatus[keyof typeof GetBinderChange200ChangeReviewersItemStatus];


export const GetBinderChange200ChangeReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
