/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderChange200ChangeApprovalState = typeof GetBinderChange200ChangeApprovalState[keyof typeof GetBinderChange200ChangeApprovalState];


export const GetBinderChange200ChangeApprovalState = {
  working: 'working',
  in_review: 'in_review',
  changes_requested: 'changes_requested',
  approved: 'approved',
  published: 'published',
} as const;
