/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderDocument200Document } from './getBinderDocument200Document.ts';
import type { GetBinderDocument200LatestVersion } from './getBinderDocument200LatestVersion.ts';
import type { GetBinderDocument200VersionsItem } from './getBinderDocument200VersionsItem.ts';

export type GetBinderDocument200 = {
  organization: string;
  workspace: string;
  document: GetBinderDocument200Document;
  versions: GetBinderDocument200VersionsItem[];
  /** @nullable */
  latestVersion: GetBinderDocument200LatestVersion;
  openChanges: (unknown | null)[];
};
