/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderHistory200VersionsItemKind } from './getBinderHistory200VersionsItemKind.ts';

export type GetBinderHistory200VersionsItem = {
  kind: GetBinderHistory200VersionsItemKind;
  slugPath: string;
  name: string;
  folder: string;
  /** @nullable */
  version: number | null;
  tag: string;
  commitSha: string;
  publishedAt: string;
  /** @nullable */
  changeNumber: number | null;
  changeTitle: string;
  submittedBy: string;
  approvers: string[];
};
