/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetBinderChangeConflicts200FilesItemAutomatic = typeof GetBinderChangeConflicts200FilesItemAutomatic[keyof typeof GetBinderChangeConflicts200FilesItemAutomatic] | null;


export const GetBinderChangeConflicts200FilesItemAutomatic = {
  ours: 'ours',
  theirs: 'theirs',
} as const;
