/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderDocument200OpenChangesItemReviewsItemAuthor } from './getBinderDocument200OpenChangesItemReviewsItemAuthor.ts';
import type { GetBinderDocument200OpenChangesItemReviewsItemState } from './getBinderDocument200OpenChangesItemReviewsItemState.ts';

export type GetBinderDocument200OpenChangesItemReviewsItem = {
  id: number;
  author: GetBinderDocument200OpenChangesItemReviewsItemAuthor;
  state: GetBinderDocument200OpenChangesItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
