/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderSettings200SignOffRulesItem } from './getBinderSettings200SignOffRulesItem.ts';
import type { GetBinderSettings200SignOffUnreadableItem } from './getBinderSettings200SignOffUnreadableItem.ts';

export type GetBinderSettings200SignOff = {
  enforced: boolean;
  exists: boolean;
  rules: GetBinderSettings200SignOffRulesItem[];
  unreadable: GetBinderSettings200SignOffUnreadableItem[];
  folders: string[];
  groups: string[];
  /** @nullable */
  pendingChange: number | null;
};
