/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChangeConflicts200FilesItemAutomatic } from './getBinderChangeConflicts200FilesItemAutomatic.ts';
import type { GetBinderChangeConflicts200FilesItemBase } from './getBinderChangeConflicts200FilesItemBase.ts';
import type { GetBinderChangeConflicts200FilesItemKind } from './getBinderChangeConflicts200FilesItemKind.ts';
import type { GetBinderChangeConflicts200FilesItemOurs } from './getBinderChangeConflicts200FilesItemOurs.ts';
import type { GetBinderChangeConflicts200FilesItemTheirs } from './getBinderChangeConflicts200FilesItemTheirs.ts';

export type GetBinderChangeConflicts200FilesItem = {
  key: string;
  path: string;
  kind: GetBinderChangeConflicts200FilesItemKind;
  /** @nullable */
  automatic: GetBinderChangeConflicts200FilesItemAutomatic;
  /** @nullable */
  base: GetBinderChangeConflicts200FilesItemBase;
  /** @nullable */
  ours: GetBinderChangeConflicts200FilesItemOurs;
  /** @nullable */
  theirs: GetBinderChangeConflicts200FilesItemTheirs;
};
