/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetBillingStatus200Plan = {
  amount: number;
  currency: string;
  interval: string;
  formatted: string;
} | null;
