/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderDraft200OthersItem = {
  branch: string;
  owner: string;
  /** @nullable */
  updatedAt: string | null;
  /** @nullable */
  lastAct: string | null;
};
