/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderDraft200Draft } from './getBinderDraft200Draft.ts';
import type { GetBinderDraft200OthersItem } from './getBinderDraft200OthersItem.ts';

export type GetBinderDraft200 = {
  organization: string;
  workspace: string;
  /** @nullable */
  draft: GetBinderDraft200Draft;
  others: GetBinderDraft200OthersItem[];
};
