/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderDocument200OpenChangesItemReviewersItemStatus } from './getBinderDocument200OpenChangesItemReviewersItemStatus.ts';

export type GetBinderDocument200OpenChangesItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: GetBinderDocument200OpenChangesItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
