/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBillingStatus200OverrideAccess } from './getBillingStatus200OverrideAccess.ts';
import type { GetBillingStatus200OverrideMode } from './getBillingStatus200OverrideMode.ts';

/**
 * @nullable
 */
export type GetBillingStatus200Override = {
  access: GetBillingStatus200OverrideAccess;
  mode?: GetBillingStatus200OverrideMode;
  /** @nullable */
  reason?: string | null;
  updatedBy: string;
  updatedAt: number;
} | null;
