/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderArchive200DocumentsItem = {
  uid: string;
  title: string;
  /** @nullable */
  slugPath: string | null;
  lastVersion: number;
  /** @nullable */
  lastPublishedAt: string | null;
  /** @nullable */
  archivedAt: string | null;
  /** @nullable */
  archivings: number | null;
};
