/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderArchive200DocumentsItem } from './getBinderArchive200DocumentsItem.ts';

export type GetBinderArchive200 = {
  organization: string;
  workspace: string;
  documents: GetBinderArchive200DocumentsItem[];
};
