/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChange200Change } from './getBinderChange200Change.ts';
import type { GetBinderChange200DocumentsItem } from './getBinderChange200DocumentsItem.ts';
import type { GetBinderChange200RemovedDocumentsItem } from './getBinderChange200RemovedDocumentsItem.ts';
import type { GetBinderChange200RequiredReviewers } from './getBinderChange200RequiredReviewers.ts';
import type { GetBinderChange200Viewer } from './getBinderChange200Viewer.ts';

export type GetBinderChange200 = {
  organization: string;
  workspace: string;
  change: GetBinderChange200Change;
  /** @nullable */
  branchLabel: string | null;
  documents: GetBinderChange200DocumentsItem[];
  removedDocuments: GetBinderChange200RemovedDocumentsItem[];
  isBehind: boolean;
  hasConflicts: boolean;
  blockOnUnresolvedThreads: boolean;
  unresolvedThreadCount: number;
  canManage: boolean;
  requiredReviewers: GetBinderChange200RequiredReviewers;
  viewer: GetBinderChange200Viewer;
};
