/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetBillingStatus200Override = {
  username: string;
  access: "grant" | "revoke";
  updatedBy: string;
  updatedAt: number;
} | null;
