/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderDocument200OpenChangesItemApprovalState } from './getBinderDocument200OpenChangesItemApprovalState.ts';
import type { GetBinderDocument200OpenChangesItemAssignee } from './getBinderDocument200OpenChangesItemAssignee.ts';
import type { GetBinderDocument200OpenChangesItemReviewersItem } from './getBinderDocument200OpenChangesItemReviewersItem.ts';
import type { GetBinderDocument200OpenChangesItemReviewsItem } from './getBinderDocument200OpenChangesItemReviewsItem.ts';
import type { GetBinderDocument200OpenChangesItemUser } from './getBinderDocument200OpenChangesItemUser.ts';

export type GetBinderDocument200OpenChangesItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: GetBinderDocument200OpenChangesItemReviewersItem[];
  /** @nullable */
  assignee: GetBinderDocument200OpenChangesItemAssignee;
  body?: string;
  approvalState: GetBinderDocument200OpenChangesItemApprovalState;
  /** @nullable */
  user?: GetBinderDocument200OpenChangesItemUser;
  reviews?: GetBinderDocument200OpenChangesItemReviewsItem[];
};
