/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChangeConflicts200FilesItem } from './getBinderChangeConflicts200FilesItem.ts';

export type GetBinderChangeConflicts200 = {
  organization: string;
  workspace: string;
  changeNumber: number;
  open: boolean;
  upToDate: boolean;
  headSha: string;
  baseSha: string;
  canResolve: boolean;
  files: GetBinderChangeConflicts200FilesItem[];
};
