/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderHistory200VersionsItem = {
  slugPath: string;
  name: string;
  folder: string;
  version: number;
  tag: string;
  commitSha: string;
  publishedAt: string;
  /** @nullable */
  changeNumber: number | null;
  changeTitle: string;
  submittedBy: string;
  approvers: string[];
};
