/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderChangeConflicts200FilesItemKind = typeof GetBinderChangeConflicts200FilesItemKind[keyof typeof GetBinderChangeConflicts200FilesItemKind];


export const GetBinderChangeConflicts200FilesItemKind = {
  editor: 'editor',
  text: 'text',
  binary: 'binary',
} as const;
