/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChange200Change } from './getBinderChange200Change.ts';
import type { GetBinderChange200DocumentsItem } from './getBinderChange200DocumentsItem.ts';

export type GetBinderChange200 = {
  organization: string;
  workspace: string;
  change: GetBinderChange200Change;
  documents: GetBinderChange200DocumentsItem[];
  isBehind: boolean;
  blockOnUnresolvedThreads: boolean;
  unresolvedThreadCount: number;
  canManage: boolean;
};
