/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderHistory200VersionsItemKind = typeof GetBinderHistory200VersionsItemKind[keyof typeof GetBinderHistory200VersionsItemKind];


export const GetBinderHistory200VersionsItemKind = {
  version: 'version',
  archived: 'archived',
} as const;
