/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderDocument200OpenChangesItemReviewsItemState = typeof GetBinderDocument200OpenChangesItemReviewsItemState[keyof typeof GetBinderDocument200OpenChangesItemReviewsItemState];


export const GetBinderDocument200OpenChangesItemReviewsItemState = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  other: 'other',
} as const;
