/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderPeople200GroupsItemMembersItem } from './getBinderPeople200GroupsItemMembersItem.ts';

export type GetBinderPeople200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: GetBinderPeople200GroupsItemMembersItem[];
};
