/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderDocument200State = typeof GetBinderDocument200State[keyof typeof GetBinderDocument200State];


export const GetBinderDocument200State = {
  published: 'published',
  proposed: 'proposed',
} as const;
