/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderSettings200SignOffRulesItemScope = typeof GetBinderSettings200SignOffRulesItemScope[keyof typeof GetBinderSettings200SignOffRulesItemScope];


export const GetBinderSettings200SignOffRulesItemScope = {
  binder: 'binder',
  folder: 'folder',
  document: 'document',
} as const;
