/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetBinderChange200Outcome = typeof GetBinderChange200Outcome[keyof typeof GetBinderChange200Outcome] | null;


export const GetBinderChange200Outcome = {
  published: 'published',
  declined: 'declined',
  withdrawn: 'withdrawn',
} as const;
