/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderSettings200Rules } from './getBinderSettings200Rules.ts';
import type { GetBinderSettings200TeamsItem } from './getBinderSettings200TeamsItem.ts';

export type GetBinderSettings200 = {
  organization: string;
  workspace: string;
  teams: GetBinderSettings200TeamsItem[];
  rules: GetBinderSettings200Rules;
  canManage: boolean;
};
