/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderDraft200DraftActsItem } from './getBinderDraft200DraftActsItem.ts';

/**
 * @nullable
 */
export type GetBinderDraft200Draft = {
  branch: string;
  name: string;
  named: boolean;
  owner: string;
  /** @nullable */
  updatedAt: string | null;
  acts: GetBinderDraft200DraftActsItem[];
} | null;
