/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChange200DocumentsItemCurrentVersion } from './getBinderChange200DocumentsItemCurrentVersion.ts';
import type { GetBinderChange200DocumentsItemVersionsItem } from './getBinderChange200DocumentsItemVersionsItem.ts';

export type GetBinderChange200DocumentsItem = {
  path: string;
  slugPath: string;
  name: string;
  folder: string;
  size: number;
  sha: string;
  nextVersion: number;
  /** @nullable */
  currentVersion: GetBinderChange200DocumentsItemCurrentVersion;
  versions: GetBinderChange200DocumentsItemVersionsItem[];
};
