/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBillingStatus200OverrideMode = typeof GetBillingStatus200OverrideMode[keyof typeof GetBillingStatus200OverrideMode];


export const GetBillingStatus200OverrideMode = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
