/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderDocument200OpenChangesItemApprovalState = typeof GetBinderDocument200OpenChangesItemApprovalState[keyof typeof GetBinderDocument200OpenChangesItemApprovalState];


export const GetBinderDocument200OpenChangesItemApprovalState = {
  working: 'working',
  in_review: 'in_review',
  changes_requested: 'changes_requested',
  approved: 'approved',
  published: 'published',
} as const;
