/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderPeople200GroupsItem } from './getBinderPeople200GroupsItem.ts';
import type { GetBinderPeople200OrganizationMembersItem } from './getBinderPeople200OrganizationMembersItem.ts';
import type { GetBinderPeople200PeopleItem } from './getBinderPeople200PeopleItem.ts';

export type GetBinderPeople200 = {
  organization: string;
  workspace: string;
  people: GetBinderPeople200PeopleItem[];
  groups: GetBinderPeople200GroupsItem[];
  openToOrganization: boolean;
  organizationMembers: GetBinderPeople200OrganizationMembersItem[];
  canManage: boolean;
};
