/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderHistory200VersionsItem } from './getBinderHistory200VersionsItem.ts';

export type GetBinderHistory200 = {
  organization: string;
  workspace: string;
  versions: GetBinderHistory200VersionsItem[];
};
