/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChange200ChangeReviewersItemStatus } from './getBinderChange200ChangeReviewersItemStatus.ts';

export type GetBinderChange200ChangeReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: GetBinderChange200ChangeReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
