/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChange200ChangeApprovalState } from './getBinderChange200ChangeApprovalState.ts';
import type { GetBinderChange200ChangeAssignee } from './getBinderChange200ChangeAssignee.ts';
import type { GetBinderChange200ChangeReviewersItem } from './getBinderChange200ChangeReviewersItem.ts';
import type { GetBinderChange200ChangeReviewsItem } from './getBinderChange200ChangeReviewsItem.ts';
import type { GetBinderChange200ChangeUser } from './getBinderChange200ChangeUser.ts';

export type GetBinderChange200Change = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: GetBinderChange200ChangeReviewersItem[];
  /** @nullable */
  assignee: GetBinderChange200ChangeAssignee;
  body?: string;
  approvalState: GetBinderChange200ChangeApprovalState;
  /** @nullable */
  user?: GetBinderChange200ChangeUser;
  reviews?: GetBinderChange200ChangeReviewsItem[];
};
