/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBillingStatus200OverrideAccess } from './getBillingStatus200OverrideAccess.ts';

/**
 * @nullable
 */
export type GetBillingStatus200Override = {
  username: string;
  access: GetBillingStatus200OverrideAccess;
  updatedBy: string;
  updatedAt: number;
} | null;
