/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChange200RemovedDocumentsItemLastVersion } from './getBinderChange200RemovedDocumentsItemLastVersion.ts';

export type GetBinderChange200RemovedDocumentsItem = {
  path: string;
  slugPath: string;
  name: string;
  /** @nullable */
  uid: string | null;
  folder: string;
  size: number;
  sha: string;
  /** @nullable */
  lastVersion: GetBinderChange200RemovedDocumentsItemLastVersion;
};
