/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBillingStatus200OverrideAccess = typeof GetBillingStatus200OverrideAccess[keyof typeof GetBillingStatus200OverrideAccess];


export const GetBillingStatus200OverrideAccess = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
