/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderChange200ChangeReviewsItemAuthor } from './getBinderChange200ChangeReviewsItemAuthor.ts';
import type { GetBinderChange200ChangeReviewsItemState } from './getBinderChange200ChangeReviewsItemState.ts';

export type GetBinderChange200ChangeReviewsItem = {
  id: number;
  author: GetBinderChange200ChangeReviewsItemAuthor;
  state: GetBinderChange200ChangeReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
