/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetBinderPeople200PeopleItem = {
  login: string;
  fullName: string;
  access: string;
  through: string;
  individual: boolean;
  groups: string[];
  seat: boolean;
};
