/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinder200Workspace } from './getBinder200Workspace.ts';

export type GetBinder200 = {
  workspace: GetBinder200Workspace;
  documentCount: number;
  openChangeCount: number;
};
