/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBinderSettings200TeamsItemMembersItem } from './getBinderSettings200TeamsItemMembersItem.ts';

export type GetBinderSettings200TeamsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: GetBinderSettings200TeamsItemMembersItem[];
};
