/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetClosedChanges200ChangesItem } from './getClosedChanges200ChangesItem.ts';

export type GetClosedChanges200 = {
  changes: GetClosedChanges200ChangesItem[];
};
