/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetClosedChanges200ChangesItemOutcome = typeof GetClosedChanges200ChangesItemOutcome[keyof typeof GetClosedChanges200ChangesItemOutcome];


export const GetClosedChanges200ChangesItemOutcome = {
  published: 'published',
  declined: 'declined',
  withdrawn: 'withdrawn',
} as const;
