/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetClosedChanges200ChangesItemReviewsItemAuthor } from './getClosedChanges200ChangesItemReviewsItemAuthor.ts';
import type { GetClosedChanges200ChangesItemReviewsItemState } from './getClosedChanges200ChangesItemReviewsItemState.ts';

export type GetClosedChanges200ChangesItemReviewsItem = {
  id: number;
  author: GetClosedChanges200ChangesItemReviewsItemAuthor;
  state: GetClosedChanges200ChangesItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
