/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentHistory200VersionsItemReviewsItem } from './getDocumentHistory200VersionsItemReviewsItem.ts';
import type { GetDocumentHistory200VersionsItemSubmission } from './getDocumentHistory200VersionsItemSubmission.ts';

export type GetDocumentHistory200VersionsItem = {
  version: number;
  tagName: string;
  sha: string;
  createdAt: string;
  /** @nullable */
  submission: GetDocumentHistory200VersionsItemSubmission;
  reviews: GetDocumentHistory200VersionsItemReviewsItem[];
  discussionCount: number;
};
