/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200OpenPullRequestsItemApprovalState } from './getDocumentDetail200OpenPullRequestsItemApprovalState.ts';
import type { GetDocumentDetail200OpenPullRequestsItemAssignee } from './getDocumentDetail200OpenPullRequestsItemAssignee.ts';
import type { GetDocumentDetail200OpenPullRequestsItemReviewersItem } from './getDocumentDetail200OpenPullRequestsItemReviewersItem.ts';
import type { GetDocumentDetail200OpenPullRequestsItemReviewsItem } from './getDocumentDetail200OpenPullRequestsItemReviewsItem.ts';
import type { GetDocumentDetail200OpenPullRequestsItemUser } from './getDocumentDetail200OpenPullRequestsItemUser.ts';

export type GetDocumentDetail200OpenPullRequestsItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: GetDocumentDetail200OpenPullRequestsItemReviewersItem[];
  /** @nullable */
  assignee: GetDocumentDetail200OpenPullRequestsItemAssignee;
  body?: string;
  approvalState: GetDocumentDetail200OpenPullRequestsItemApprovalState;
  /** @nullable */
  user?: GetDocumentDetail200OpenPullRequestsItemUser;
  reviews?: GetDocumentDetail200OpenPullRequestsItemReviewsItem[];
};
