/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentHistory200CanonicalFile } from './getDocumentHistory200CanonicalFile.ts';
import type { GetDocumentHistory200VersionsItem } from './getDocumentHistory200VersionsItem.ts';

export type GetDocumentHistory200 = {
  versions: GetDocumentHistory200VersionsItem[];
  /** @nullable */
  canonicalFile: GetDocumentHistory200CanonicalFile;
};
