/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200UploadPullRequestsItemReviewsItemAuthor } from './getDocumentDetail200UploadPullRequestsItemReviewsItemAuthor.ts';
import type { GetDocumentDetail200UploadPullRequestsItemReviewsItemState } from './getDocumentDetail200UploadPullRequestsItemReviewsItemState.ts';

export type GetDocumentDetail200UploadPullRequestsItemReviewsItem = {
  id: number;
  author: GetDocumentDetail200UploadPullRequestsItemReviewsItemAuthor;
  state: GetDocumentDetail200UploadPullRequestsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
