/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200CurrentUserPermissionAccess } from './getDocumentDetail200CurrentUserPermissionAccess.ts';
import type { GetDocumentDetail200CurrentUserPermissionUser } from './getDocumentDetail200CurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type GetDocumentDetail200CurrentUserPermission = {
  permission: string;
  access: GetDocumentDetail200CurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: GetDocumentDetail200CurrentUserPermissionUser;
} | null;
