/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentPermissions200BranchProtection } from './getDocumentPermissions200BranchProtection.ts';
import type { GetDocumentPermissions200CurrentUserPermission } from './getDocumentPermissions200CurrentUserPermission.ts';
import type { GetDocumentPermissions200ReviewSettings } from './getDocumentPermissions200ReviewSettings.ts';

export type GetDocumentPermissions200 = {
  /** @nullable */
  branchProtection: GetDocumentPermissions200BranchProtection;
  isPrivate: boolean;
  isInternal: boolean;
  /** @nullable */
  currentUserPermission?: GetDocumentPermissions200CurrentUserPermission;
  /** @nullable */
  reviewSettings?: GetDocumentPermissions200ReviewSettings;
};
