/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200OpenPullRequestsItemReviewersItemStatus } from './getDocumentDetail200OpenPullRequestsItemReviewersItemStatus.ts';

export type GetDocumentDetail200OpenPullRequestsItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: GetDocumentDetail200OpenPullRequestsItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
