/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetDocumentDetail200OpenPullRequestsItemReviewersItemStatus = typeof GetDocumentDetail200OpenPullRequestsItemReviewersItemStatus[keyof typeof GetDocumentDetail200OpenPullRequestsItemReviewersItemStatus];


export const GetDocumentDetail200OpenPullRequestsItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
