/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentPermissions200CurrentUserPermissionAccess } from './getDocumentPermissions200CurrentUserPermissionAccess.ts';
import type { GetDocumentPermissions200CurrentUserPermissionUser } from './getDocumentPermissions200CurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type GetDocumentPermissions200CurrentUserPermission = {
  permission: string;
  access: GetDocumentPermissions200CurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: GetDocumentPermissions200CurrentUserPermissionUser;
} | null;
