/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetDocumentDetail200BranchProtection = {
  requiredApprovals: number;
  enableApprovalsWhitelist: boolean;
  approvalsWhitelistUsernames: string[];
  approvalsWhitelistTeams: string[];
  enableMergeWhitelist: boolean;
  mergeWhitelistUsernames: string[];
  mergeWhitelistTeams: string[];
  blockOnRejectedReviews: boolean;
  dismissStaleApprovals: boolean;
  enablePush: boolean;
} | null;
