/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentHistory200VersionsItemReviewsItemAuthor } from './getDocumentHistory200VersionsItemReviewsItemAuthor.ts';
import type { GetDocumentHistory200VersionsItemReviewsItemState } from './getDocumentHistory200VersionsItemReviewsItemState.ts';

export type GetDocumentHistory200VersionsItemReviewsItem = {
  id: number;
  author: GetDocumentHistory200VersionsItemReviewsItemAuthor;
  state: GetDocumentHistory200VersionsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
