/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetDocumentPermissions200CurrentUserPermissionAccess = typeof GetDocumentPermissions200CurrentUserPermissionAccess[keyof typeof GetDocumentPermissions200CurrentUserPermissionAccess];


export const GetDocumentPermissions200CurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
