/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetDocumentHistory200VersionsItemSubmission = {
  number: number;
  title: string;
  body: string;
  submittedBy: string;
  submittedAt: string;
  /** @nullable */
  mergedAt: string | null;
  /** @nullable */
  mergedBy: string | null;
} | null;
