/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200BranchProtection } from './getDocumentDetail200BranchProtection';
import type { GetDocumentDetail200CanonicalFile } from './getDocumentDetail200CanonicalFile';
import type { GetDocumentDetail200CurrentUserPermission } from './getDocumentDetail200CurrentUserPermission';
import type { GetDocumentDetail200LatestTag } from './getDocumentDetail200LatestTag';
import type { GetDocumentDetail200OpenPullRequestsItem } from './getDocumentDetail200OpenPullRequestsItem';
import type { GetDocumentDetail200Repository } from './getDocumentDetail200Repository';
import type { GetDocumentDetail200TagsItem } from './getDocumentDetail200TagsItem';
import type { GetDocumentDetail200UploadPullRequestsItem } from './getDocumentDetail200UploadPullRequestsItem';

export type GetDocumentDetail200 = {
  repository: GetDocumentDetail200Repository;
  tags: GetDocumentDetail200TagsItem[];
  /** @nullable */
  latestTag: GetDocumentDetail200LatestTag;
  openPullRequests: GetDocumentDetail200OpenPullRequestsItem[];
  uploadPullRequests: GetDocumentDetail200UploadPullRequestsItem[];
  /** @nullable */
  branchProtection: GetDocumentDetail200BranchProtection;
  /** @nullable */
  canonicalFile: GetDocumentDetail200CanonicalFile;
  /** @nullable */
  currentUserPermission: GetDocumentDetail200CurrentUserPermission;
};
