/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200RepositoryOwner } from './getDocumentDetail200RepositoryOwner.ts';

export type GetDocumentDetail200Repository = {
  id: number;
  name: string;
  full_name: string;
  description: string;
  updated_at: string;
  owner: GetDocumentDetail200RepositoryOwner;
};
