/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200BranchProtection } from './getDocumentDetail200BranchProtection.ts';
import type { GetDocumentDetail200CanonicalFile } from './getDocumentDetail200CanonicalFile.ts';
import type { GetDocumentDetail200CurrentUserPermission } from './getDocumentDetail200CurrentUserPermission.ts';
import type { GetDocumentDetail200LatestTag } from './getDocumentDetail200LatestTag.ts';
import type { GetDocumentDetail200OpenPullRequestsItem } from './getDocumentDetail200OpenPullRequestsItem.ts';
import type { GetDocumentDetail200Repository } from './getDocumentDetail200Repository.ts';
import type { GetDocumentDetail200ReviewSettings } from './getDocumentDetail200ReviewSettings.ts';
import type { GetDocumentDetail200TagsItem } from './getDocumentDetail200TagsItem.ts';
import type { GetDocumentDetail200UploadPullRequestsItem } from './getDocumentDetail200UploadPullRequestsItem.ts';

export type GetDocumentDetail200 = {
  repository: GetDocumentDetail200Repository;
  tags: GetDocumentDetail200TagsItem[];
  /** @nullable */
  latestTag: GetDocumentDetail200LatestTag;
  openPullRequests: GetDocumentDetail200OpenPullRequestsItem[];
  uploadPullRequests: GetDocumentDetail200UploadPullRequestsItem[];
  /** @nullable */
  branchProtection: GetDocumentDetail200BranchProtection;
  /** @nullable */
  reviewSettings?: GetDocumentDetail200ReviewSettings;
  /** @nullable */
  canonicalFile: GetDocumentDetail200CanonicalFile;
  /** @nullable */
  currentUserPermission: GetDocumentDetail200CurrentUserPermission;
};
