/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetDocumentDetail200CurrentUserPermissionAccess = typeof GetDocumentDetail200CurrentUserPermissionAccess[keyof typeof GetDocumentDetail200CurrentUserPermissionAccess];


export const GetDocumentDetail200CurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
