/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetDocumentDetail200UploadPullRequestsItemReviewersItemStatus = typeof GetDocumentDetail200UploadPullRequestsItemReviewersItemStatus[keyof typeof GetDocumentDetail200UploadPullRequestsItemReviewersItemStatus];


export const GetDocumentDetail200UploadPullRequestsItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
