/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200OpenPullRequestsItemReviewsItemAuthor } from './getDocumentDetail200OpenPullRequestsItemReviewsItemAuthor.ts';
import type { GetDocumentDetail200OpenPullRequestsItemReviewsItemState } from './getDocumentDetail200OpenPullRequestsItemReviewsItemState.ts';

export type GetDocumentDetail200OpenPullRequestsItemReviewsItem = {
  id: number;
  author: GetDocumentDetail200OpenPullRequestsItemReviewsItemAuthor;
  state: GetDocumentDetail200OpenPullRequestsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
