/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetDocumentDetail200OpenPullRequestsItemReviewsItemState = typeof GetDocumentDetail200OpenPullRequestsItemReviewsItemState[keyof typeof GetDocumentDetail200OpenPullRequestsItemReviewsItemState];


export const GetDocumentDetail200OpenPullRequestsItemReviewsItemState = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  other: 'other',
} as const;
