/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentDetail200UploadPullRequestsItemReviewersItemStatus } from './getDocumentDetail200UploadPullRequestsItemReviewersItemStatus.ts';

export type GetDocumentDetail200UploadPullRequestsItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: GetDocumentDetail200UploadPullRequestsItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
