/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetDocumentDetail200UploadPullRequestsItemApprovalState = typeof GetDocumentDetail200UploadPullRequestsItemApprovalState[keyof typeof GetDocumentDetail200UploadPullRequestsItemApprovalState];


export const GetDocumentDetail200UploadPullRequestsItemApprovalState = {
  working: 'working',
  in_review: 'in_review',
  changes_requested: 'changes_requested',
  approved: 'approved',
  published: 'published',
} as const;
