/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentPermissions200BranchProtection } from "./getDocumentPermissions200BranchProtection";
import type { GetDocumentPermissions200CurrentUserPermission } from "./getDocumentPermissions200CurrentUserPermission";

export type GetDocumentPermissions200 = {
  /** @nullable */
  branchProtection: GetDocumentPermissions200BranchProtection;
  isPrivate: boolean;
  isInternal: boolean;
  /** @nullable */
  currentUserPermission?: GetDocumentPermissions200CurrentUserPermission;
};
