/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetEmailPreferences200Preferences } from './getEmailPreferences200Preferences.ts';

export type GetEmailPreferences200 = {
  preferences: GetEmailPreferences200Preferences;
};
