/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200OpenItemPendingPRsItemReviewsItemAuthor } from './getHomeChanges200OpenItemPendingPRsItemReviewsItemAuthor.ts';
import type { GetHomeChanges200OpenItemPendingPRsItemReviewsItemState } from './getHomeChanges200OpenItemPendingPRsItemReviewsItemState.ts';

export type GetHomeChanges200OpenItemPendingPRsItemReviewsItem = {
  id: number;
  author: GetHomeChanges200OpenItemPendingPRsItemReviewsItemAuthor;
  state: GetHomeChanges200OpenItemPendingPRsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
