/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetHomeChanges200DecidedItemChangesItemReviewsItemState = typeof GetHomeChanges200DecidedItemChangesItemReviewsItemState[keyof typeof GetHomeChanges200DecidedItemChangesItemReviewsItemState];


export const GetHomeChanges200DecidedItemChangesItemReviewsItemState = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  other: 'other',
} as const;
