/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200OpenItemPendingPRsItemApprovalState } from './getHomeChanges200OpenItemPendingPRsItemApprovalState.ts';
import type { GetHomeChanges200OpenItemPendingPRsItemAssignee } from './getHomeChanges200OpenItemPendingPRsItemAssignee.ts';
import type { GetHomeChanges200OpenItemPendingPRsItemReviewersItem } from './getHomeChanges200OpenItemPendingPRsItemReviewersItem.ts';
import type { GetHomeChanges200OpenItemPendingPRsItemReviewsItem } from './getHomeChanges200OpenItemPendingPRsItemReviewsItem.ts';
import type { GetHomeChanges200OpenItemPendingPRsItemUser } from './getHomeChanges200OpenItemPendingPRsItemUser.ts';

export type GetHomeChanges200OpenItemPendingPRsItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: GetHomeChanges200OpenItemPendingPRsItemReviewersItem[];
  /** @nullable */
  assignee: GetHomeChanges200OpenItemPendingPRsItemAssignee;
  body?: string;
  approvalState: GetHomeChanges200OpenItemPendingPRsItemApprovalState;
  /** @nullable */
  user?: GetHomeChanges200OpenItemPendingPRsItemUser;
  reviews?: GetHomeChanges200OpenItemPendingPRsItemReviewsItem[];
};
