/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200DecidedItemChangesItemReviewsItemAuthor } from './getHomeChanges200DecidedItemChangesItemReviewsItemAuthor.ts';
import type { GetHomeChanges200DecidedItemChangesItemReviewsItemState } from './getHomeChanges200DecidedItemChangesItemReviewsItemState.ts';

export type GetHomeChanges200DecidedItemChangesItemReviewsItem = {
  id: number;
  author: GetHomeChanges200DecidedItemChangesItemReviewsItemAuthor;
  state: GetHomeChanges200DecidedItemChangesItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
