/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetHomeChanges200DecidedItemChangesItemOutcome = typeof GetHomeChanges200DecidedItemChangesItemOutcome[keyof typeof GetHomeChanges200DecidedItemChangesItemOutcome];


export const GetHomeChanges200DecidedItemChangesItemOutcome = {
  published: 'published',
  declined: 'declined',
  withdrawn: 'withdrawn',
} as const;
