/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetHomeChanges200DecidedItemChangesItemReviewersItemStatus = typeof GetHomeChanges200DecidedItemChangesItemReviewersItemStatus[keyof typeof GetHomeChanges200DecidedItemChangesItemReviewersItemStatus];


export const GetHomeChanges200DecidedItemChangesItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
