/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200DecidedItemChangesItem } from './getHomeChanges200DecidedItemChangesItem.ts';

export type GetHomeChanges200DecidedItem = {
  owner: string;
  repo: string;
  changes: GetHomeChanges200DecidedItemChangesItem[];
};
