/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200OpenItemRepoOwner } from './getHomeChanges200OpenItemRepoOwner.ts';

export type GetHomeChanges200OpenItemRepo = {
  name: string;
  owner: GetHomeChanges200OpenItemRepoOwner;
};
