/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200DecidedItem } from './getHomeChanges200DecidedItem.ts';
import type { GetHomeChanges200OpenItem } from './getHomeChanges200OpenItem.ts';

export type GetHomeChanges200 = {
  open: GetHomeChanges200OpenItem[];
  decided: GetHomeChanges200DecidedItem[];
};
