/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200DecidedItemChangesItemReviewersItemStatus } from './getHomeChanges200DecidedItemChangesItemReviewersItemStatus.ts';

export type GetHomeChanges200DecidedItemChangesItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: GetHomeChanges200DecidedItemChangesItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
