/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200DecidedItemChangesItemAssignee } from './getHomeChanges200DecidedItemChangesItemAssignee.ts';
import type { GetHomeChanges200DecidedItemChangesItemOutcome } from './getHomeChanges200DecidedItemChangesItemOutcome.ts';
import type { GetHomeChanges200DecidedItemChangesItemReviewersItem } from './getHomeChanges200DecidedItemChangesItemReviewersItem.ts';
import type { GetHomeChanges200DecidedItemChangesItemReviewsItem } from './getHomeChanges200DecidedItemChangesItemReviewsItem.ts';

export type GetHomeChanges200DecidedItemChangesItem = {
  number: number;
  title: string;
  body: string;
  branchName: string;
  submittedBy: string;
  submittedAt: string;
  /** @nullable */
  closedAt: string | null;
  outcome: GetHomeChanges200DecidedItemChangesItemOutcome;
  /** @nullable */
  decidedBy: string | null;
  /** @nullable */
  publishedVersion: number | null;
  reviews: GetHomeChanges200DecidedItemChangesItemReviewsItem[];
  reviewers: GetHomeChanges200DecidedItemChangesItemReviewersItem[];
  /** @nullable */
  assignee: GetHomeChanges200DecidedItemChangesItemAssignee;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
};
