/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200OpenItemPendingPRsItem } from './getHomeChanges200OpenItemPendingPRsItem.ts';
import type { GetHomeChanges200OpenItemRepo } from './getHomeChanges200OpenItemRepo.ts';

export type GetHomeChanges200OpenItem = {
  repo: GetHomeChanges200OpenItemRepo;
  pendingPRs: GetHomeChanges200OpenItemPendingPRsItem[];
  /** @nullable */
  error: string | null;
};
