/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetHomeChanges200OpenItemPendingPRsItemReviewersItemStatus } from './getHomeChanges200OpenItemPendingPRsItemReviewersItemStatus.ts';

export type GetHomeChanges200OpenItemPendingPRsItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: GetHomeChanges200OpenItemPendingPRsItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
