/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetHomeChanges200OpenItemPendingPRsItemReviewersItemStatus = typeof GetHomeChanges200OpenItemPendingPRsItemReviewersItemStatus[keyof typeof GetHomeChanges200OpenItemPendingPRsItemReviewersItemStatus];


export const GetHomeChanges200OpenItemPendingPRsItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
