/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetInvitation200Status = typeof GetInvitation200Status[keyof typeof GetInvitation200Status];


export const GetInvitation200Status = {
  pending: 'pending',
  accepted: 'accepted',
  joined: 'joined',
  revoked: 'revoked',
  expired: 'expired',
} as const;
