/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetInvitation200Status } from './getInvitation200Status.ts';

export type GetInvitation200 = {
  organization: string;
  organizationName: string;
  invitedBy: string;
  grant: string;
  email: string;
  status: GetInvitation200Status;
  acceptedByYou?: boolean;
};
