/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetLegalStatus200OrganizationsItem } from './getLegalStatus200OrganizationsItem.ts';

export type GetLegalStatus200 = {
  version: string;
  person: boolean;
  organizations: GetLegalStatus200OrganizationsItem[];
};
