/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetOnboarding200StepsItemId = typeof GetOnboarding200StepsItemId[keyof typeof GetOnboarding200StepsItemId];


export const GetOnboarding200StepsItemId = {
  organization: 'organization',
  binder: 'binder',
  documents: 'documents',
  approvers: 'approvers',
  publish: 'publish',
} as const;
