/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOnboarding200StepsItemId } from './getOnboarding200StepsItemId.ts';

export type GetOnboarding200StepsItem = {
  id: GetOnboarding200StepsItemId;
  done: boolean;
  /** @nullable */
  href: string | null;
};
