/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrganizationPeople200GroupsItemMembersItem } from './getOrganizationPeople200GroupsItemMembersItem.ts';

export type GetOrganizationPeople200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  memberCount: number;
  members: GetOrganizationPeople200GroupsItemMembersItem[];
  binders: string[];
};
