/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOnboarding200StepsItem } from './getOnboarding200StepsItem.ts';

export type GetOnboarding200 = {
  steps: GetOnboarding200StepsItem[];
  complete: boolean;
  /** @nullable */
  org: string | null;
  /** @nullable */
  binder: string | null;
};
