/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrganizationPeople200GroupsItem } from './getOrganizationPeople200GroupsItem.ts';
import type { GetOrganizationPeople200PeopleItem } from './getOrganizationPeople200PeopleItem.ts';

export type GetOrganizationPeople200 = {
  organization: string;
  people: GetOrganizationPeople200PeopleItem[];
  groups: GetOrganizationPeople200GroupsItem[];
  binders: string[];
  canManage: boolean;
};
