/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetOrganizationPeople200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  memberCount: number;
};
