/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GetWorkspaceDocument200Document } from './getWorkspaceDocument200Document.ts';
import type { GetWorkspaceDocument200LatestVersion } from './getWorkspaceDocument200LatestVersion.ts';
import type { GetWorkspaceDocument200VersionsItem } from './getWorkspaceDocument200VersionsItem.ts';

export type GetWorkspaceDocument200 = {
  organization: string;
  workspace: string;
  document: GetWorkspaceDocument200Document;
  versions: GetWorkspaceDocument200VersionsItem[];
  /** @nullable */
  latestVersion: GetWorkspaceDocument200LatestVersion;
  openChanges: (unknown | null)[];
};
