/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type GetWorkspaceDocument200Document = {
  path: string;
  slugPath: string;
  name: string;
  folder: string;
  size: number;
  sha: string;
};
