/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GrantBinderGroup200TeamsItemMembersItem } from './grantBinderGroup200TeamsItemMembersItem.ts';

export type GrantBinderGroup200TeamsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: GrantBinderGroup200TeamsItemMembersItem[];
};
