/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { GrantBinderGroup200TeamsItem } from './grantBinderGroup200TeamsItem.ts';

export type GrantBinderGroup200 = {
  organization: string;
  workspace: string;
  teams: GrantBinderGroup200TeamsItem[];
  approvalsWhitelist: string[];
};
