/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadOpenItemPendingPRsItemApprovalState } from './homeChangesPayloadOpenItemPendingPRsItemApprovalState.ts';
import type { HomeChangesPayloadOpenItemPendingPRsItemAssignee } from './homeChangesPayloadOpenItemPendingPRsItemAssignee.ts';
import type { HomeChangesPayloadOpenItemPendingPRsItemReviewersItem } from './homeChangesPayloadOpenItemPendingPRsItemReviewersItem.ts';
import type { HomeChangesPayloadOpenItemPendingPRsItemReviewsItem } from './homeChangesPayloadOpenItemPendingPRsItemReviewsItem.ts';
import type { HomeChangesPayloadOpenItemPendingPRsItemUser } from './homeChangesPayloadOpenItemPendingPRsItemUser.ts';

export type HomeChangesPayloadOpenItemPendingPRsItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: HomeChangesPayloadOpenItemPendingPRsItemReviewersItem[];
  /** @nullable */
  assignee: HomeChangesPayloadOpenItemPendingPRsItemAssignee;
  body?: string;
  approvalState: HomeChangesPayloadOpenItemPendingPRsItemApprovalState;
  /** @nullable */
  user?: HomeChangesPayloadOpenItemPendingPRsItemUser;
  reviews?: HomeChangesPayloadOpenItemPendingPRsItemReviewsItem[];
};
