/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadOpenItemPendingPRsItemReviewsItemAuthor } from './homeChangesPayloadOpenItemPendingPRsItemReviewsItemAuthor.ts';
import type { HomeChangesPayloadOpenItemPendingPRsItemReviewsItemState } from './homeChangesPayloadOpenItemPendingPRsItemReviewsItemState.ts';

export type HomeChangesPayloadOpenItemPendingPRsItemReviewsItem = {
  id: number;
  author: HomeChangesPayloadOpenItemPendingPRsItemReviewsItemAuthor;
  state: HomeChangesPayloadOpenItemPendingPRsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
