/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadOpenItemPendingPRsItemReviewersItemStatus } from './homeChangesPayloadOpenItemPendingPRsItemReviewersItemStatus.ts';

export type HomeChangesPayloadOpenItemPendingPRsItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: HomeChangesPayloadOpenItemPendingPRsItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
