/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadDecidedItemChangesItem } from './homeChangesPayloadDecidedItemChangesItem.ts';

export type HomeChangesPayloadDecidedItem = {
  owner: string;
  repo: string;
  changes: HomeChangesPayloadDecidedItemChangesItem[];
};
