/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadDecidedItem } from './homeChangesPayloadDecidedItem.ts';
import type { HomeChangesPayloadOpenItem } from './homeChangesPayloadOpenItem.ts';

export interface HomeChangesPayload {
  open: HomeChangesPayloadOpenItem[];
  decided: HomeChangesPayloadDecidedItem[];
}
