/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadDecidedItemChangesItemAssignee } from './homeChangesPayloadDecidedItemChangesItemAssignee.ts';
import type { HomeChangesPayloadDecidedItemChangesItemOutcome } from './homeChangesPayloadDecidedItemChangesItemOutcome.ts';
import type { HomeChangesPayloadDecidedItemChangesItemReviewersItem } from './homeChangesPayloadDecidedItemChangesItemReviewersItem.ts';
import type { HomeChangesPayloadDecidedItemChangesItemReviewsItem } from './homeChangesPayloadDecidedItemChangesItemReviewsItem.ts';

export type HomeChangesPayloadDecidedItemChangesItem = {
  number: number;
  title: string;
  body: string;
  branchName: string;
  submittedBy: string;
  submittedAt: string;
  /** @nullable */
  closedAt: string | null;
  outcome: HomeChangesPayloadDecidedItemChangesItemOutcome;
  /** @nullable */
  decidedBy: string | null;
  /** @nullable */
  publishedVersion: number | null;
  reviews: HomeChangesPayloadDecidedItemChangesItemReviewsItem[];
  reviewers: HomeChangesPayloadDecidedItemChangesItemReviewersItem[];
  /** @nullable */
  assignee: HomeChangesPayloadDecidedItemChangesItemAssignee;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
};
