/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadDecidedItemChangesItemReviewersItemStatus } from './homeChangesPayloadDecidedItemChangesItemReviewersItemStatus.ts';

export type HomeChangesPayloadDecidedItemChangesItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: HomeChangesPayloadDecidedItemChangesItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
