/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type HomeChangesPayloadOpenItemPendingPRsItemReviewersItemStatus = typeof HomeChangesPayloadOpenItemPendingPRsItemReviewersItemStatus[keyof typeof HomeChangesPayloadOpenItemPendingPRsItemReviewersItemStatus];


export const HomeChangesPayloadOpenItemPendingPRsItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
