/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type HomeChangesPayloadDecidedItemChangesItemOutcome = typeof HomeChangesPayloadDecidedItemChangesItemOutcome[keyof typeof HomeChangesPayloadDecidedItemChangesItemOutcome];


export const HomeChangesPayloadDecidedItemChangesItemOutcome = {
  published: 'published',
  declined: 'declined',
  withdrawn: 'withdrawn',
} as const;
