/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadDecidedItemChangesItemReviewsItemAuthor } from './homeChangesPayloadDecidedItemChangesItemReviewsItemAuthor.ts';
import type { HomeChangesPayloadDecidedItemChangesItemReviewsItemState } from './homeChangesPayloadDecidedItemChangesItemReviewsItemState.ts';

export type HomeChangesPayloadDecidedItemChangesItemReviewsItem = {
  id: number;
  author: HomeChangesPayloadDecidedItemChangesItemReviewsItemAuthor;
  state: HomeChangesPayloadDecidedItemChangesItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
