/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadOpenItemRepoOwner } from './homeChangesPayloadOpenItemRepoOwner.ts';

export type HomeChangesPayloadOpenItemRepo = {
  name: string;
  owner: HomeChangesPayloadOpenItemRepoOwner;
};
