/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { HomeChangesPayloadOpenItemLatestTag } from './homeChangesPayloadOpenItemLatestTag.ts';
import type { HomeChangesPayloadOpenItemPendingPRsItem } from './homeChangesPayloadOpenItemPendingPRsItem.ts';
import type { HomeChangesPayloadOpenItemRepo } from './homeChangesPayloadOpenItemRepo.ts';

export type HomeChangesPayloadOpenItem = {
  repo: HomeChangesPayloadOpenItemRepo;
  /** @nullable */
  latestTag: HomeChangesPayloadOpenItemLatestTag;
  pendingPRs: HomeChangesPayloadOpenItemPendingPRsItem[];
  /** @nullable */
  error: string | null;
};
