/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { InitialDocumentUploadResultRepository } from './initialDocumentUploadResultRepository.ts';

export interface InitialDocumentUploadResult {
  repository: InitialDocumentUploadResultRepository;
  owner: string;
  repo: string;
  canonicalFile: string;
  prNumber: number;
  prTitle: string;
  branchName: string;
  commitSha: string;
}
