/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { InitialDocumentUploadResultRepositoryOwner } from "./initialDocumentUploadResultRepositoryOwner";

export type InitialDocumentUploadResultRepository = {
  id: number;
  name: string;
  full_name: string;
  description: string;
  updated_at: string;
  owner: InitialDocumentUploadResultRepositoryOwner;
};
