/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderCollaborators200CurrentUserPermissionAccess } from './listBinderCollaborators200CurrentUserPermissionAccess.ts';
import type { ListBinderCollaborators200CurrentUserPermissionUser } from './listBinderCollaborators200CurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type ListBinderCollaborators200CurrentUserPermission = {
  permission: string;
  access: ListBinderCollaborators200CurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: ListBinderCollaborators200CurrentUserPermissionUser;
} | null;
