/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListWorkspaces200WorkspacesItem } from './listWorkspaces200WorkspacesItem.ts';

export type ListWorkspaces200 = {
  workspaces: ListWorkspaces200WorkspacesItem[];
};
