/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListOrganizations200OrganizationsItem } from './listOrganizations200OrganizationsItem.ts';

export type ListOrganizations200 = {
  organizations: ListOrganizations200OrganizationsItem[];
};
