/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DocumentsItemPendingPRsItemApprovalState } from './listDocuments200DocumentsItemPendingPRsItemApprovalState.ts';
import type { ListDocuments200DocumentsItemPendingPRsItemAssignee } from './listDocuments200DocumentsItemPendingPRsItemAssignee.ts';
import type { ListDocuments200DocumentsItemPendingPRsItemReviewersItem } from './listDocuments200DocumentsItemPendingPRsItemReviewersItem.ts';
import type { ListDocuments200DocumentsItemPendingPRsItemReviewsItem } from './listDocuments200DocumentsItemPendingPRsItemReviewsItem.ts';
import type { ListDocuments200DocumentsItemPendingPRsItemUser } from './listDocuments200DocumentsItemPendingPRsItemUser.ts';

export type ListDocuments200DocumentsItemPendingPRsItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  requiredApprovals: number;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: ListDocuments200DocumentsItemPendingPRsItemReviewersItem[];
  /** @nullable */
  assignee: ListDocuments200DocumentsItemPendingPRsItemAssignee;
  body?: string;
  approvalState: ListDocuments200DocumentsItemPendingPRsItemApprovalState;
  /** @nullable */
  user?: ListDocuments200DocumentsItemPendingPRsItemUser;
  reviews?: ListDocuments200DocumentsItemPendingPRsItemReviewsItem[];
};
