/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAdminSubscriptionAccess200UsersItemAccessSource } from './listAdminSubscriptionAccess200UsersItemAccessSource.ts';
import type { ListAdminSubscriptionAccess200UsersItemOrganization } from './listAdminSubscriptionAccess200UsersItemOrganization.ts';
import type { ListAdminSubscriptionAccess200UsersItemOverride } from './listAdminSubscriptionAccess200UsersItemOverride.ts';

export type ListAdminSubscriptionAccess200UsersItem = {
  username: string;
  fullName?: string;
  email?: string;
  /** @nullable */
  organization: ListAdminSubscriptionAccess200UsersItemOrganization;
  /** @nullable */
  trialEndsAt?: number | null;
  hasAccess: boolean;
  accessSource: ListAdminSubscriptionAccess200UsersItemAccessSource;
  /** @nullable */
  stripeStatus: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  /** @nullable */
  override: ListAdminSubscriptionAccess200UsersItemOverride;
};
