/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocuments200DocumentsItemPendingPRsItemReviewersItemStatus = typeof ListDocuments200DocumentsItemPendingPRsItemReviewersItemStatus[keyof typeof ListDocuments200DocumentsItemPendingPRsItemReviewersItemStatus];


export const ListDocuments200DocumentsItemPendingPRsItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
