/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAdminSubscriptionAccess200UsersItemOverrideAccess } from './listAdminSubscriptionAccess200UsersItemOverrideAccess.ts';

/**
 * @nullable
 */
export type ListAdminSubscriptionAccess200UsersItemOverride = {
  username: string;
  access: ListAdminSubscriptionAccess200UsersItemOverrideAccess;
  updatedBy: string;
  updatedAt: number;
} | null;
