/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocumentCollaborators200CollaboratorsItemAccess =
  (typeof ListDocumentCollaborators200CollaboratorsItemAccess)[keyof typeof ListDocumentCollaborators200CollaboratorsItemAccess];

export const ListDocumentCollaborators200CollaboratorsItemAccess = {
  read: "read",
  write: "write",
  admin: "admin",
} as const;
