/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DocumentsItemRepoOwner } from './listDocuments200DocumentsItemRepoOwner';

export type ListDocuments200DocumentsItemRepo = {
  id: number;
  name: string;
  full_name: string;
  description: string;
  updated_at: string;
  owner: ListDocuments200DocumentsItemRepoOwner;
};
