/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentCollaborators200CollaboratorsItemAccess } from './listDocumentCollaborators200CollaboratorsItemAccess.ts';
import type { ListDocumentCollaborators200CollaboratorsItemUser } from './listDocumentCollaborators200CollaboratorsItemUser.ts';

export type ListDocumentCollaborators200CollaboratorsItem = {
  permission: string;
  access: ListDocumentCollaborators200CollaboratorsItemAccess;
  permissionLabel: string;
  roleName: string;
  user: ListDocumentCollaborators200CollaboratorsItemUser;
};
