/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DocumentsItemLatestVersion } from './listDocuments200DocumentsItemLatestVersion.ts';
import type { ListDocuments200DocumentsItemState } from './listDocuments200DocumentsItemState.ts';

export type ListDocuments200DocumentsItem = {
  /** @nullable */
  path: string | null;
  slugPath: string;
  name: string;
  folder: string;
  /** @nullable */
  size: number | null;
  /** @nullable */
  sha: string | null;
  state: ListDocuments200DocumentsItemState;
  openChangeCount: number;
  /** @nullable */
  latestVersion: ListDocuments200DocumentsItemLatestVersion;
  organization: string;
  binder: string;
  binderDescription: string;
};
