/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListWorkspaceDocuments200DocumentsItem } from './listWorkspaceDocuments200DocumentsItem.ts';

export type ListWorkspaceDocuments200 = {
  organization?: string;
  workspace: string;
  documents: ListWorkspaceDocuments200DocumentsItem[];
};
