/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderDocuments200DocumentsItem } from './listBinderDocuments200DocumentsItem.ts';

export type ListBinderDocuments200 = {
  organization?: string;
  workspace: string;
  documents: ListBinderDocuments200DocumentsItem[];
};
