/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListAdminSubscriptionAccess200UsersItemOverrideMode = typeof ListAdminSubscriptionAccess200UsersItemOverrideMode[keyof typeof ListAdminSubscriptionAccess200UsersItemOverrideMode];


export const ListAdminSubscriptionAccess200UsersItemOverrideMode = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
