/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChanges200ChangesItemReviewersItemStatus } from './listBinderChanges200ChangesItemReviewersItemStatus.ts';

export type ListBinderChanges200ChangesItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: ListBinderChanges200ChangesItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
