/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentDiscussions200ThreadsItemEventsItemActor } from './listDocumentDiscussions200ThreadsItemEventsItemActor.ts';

export type ListDocumentDiscussions200ThreadsItemEventsItem = {
  id: number;
  actor: ListDocumentDiscussions200ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
