/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentDiscussions200ThreadsItemCommentsItemAuthor } from './listDocumentDiscussions200ThreadsItemCommentsItemAuthor.ts';
import type { ListDocumentDiscussions200ThreadsItemCommentsItemReactionsItem } from './listDocumentDiscussions200ThreadsItemCommentsItemReactionsItem.ts';

export type ListDocumentDiscussions200ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: ListDocumentDiscussions200ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: ListDocumentDiscussions200ThreadsItemCommentsItemReactionsItem[];
};
