/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListNotifications200NotificationsItem } from './listNotifications200NotificationsItem.ts';

export type ListNotifications200 = {
  notifications: ListNotifications200NotificationsItem[];
};
