/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderCollaborators200CollaboratorsItemAccess } from './listBinderCollaborators200CollaboratorsItemAccess.ts';
import type { ListBinderCollaborators200CollaboratorsItemUser } from './listBinderCollaborators200CollaboratorsItemUser.ts';

export type ListBinderCollaborators200CollaboratorsItem = {
  permission: string;
  access: ListBinderCollaborators200CollaboratorsItemAccess;
  permissionLabel: string;
  roleName: string;
  user: ListBinderCollaborators200CollaboratorsItemUser;
};
