/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderChanges200State = typeof ListBinderChanges200State[keyof typeof ListBinderChanges200State];


export const ListBinderChanges200State = {
  open: 'open',
  closed: 'closed',
} as const;
