/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemContent = typeof ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemContent[keyof typeof ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemContent];


export const ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemContent = {
  '+1': '+1',
  NUMBER_MINUS_1: '-1',
  confused: 'confused',
  eyes: 'eyes',
  heart: 'heart',
} as const;
