/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocumentCollaborators200CurrentUserPermissionAccess = typeof ListDocumentCollaborators200CurrentUserPermissionAccess[keyof typeof ListDocumentCollaborators200CurrentUserPermissionAccess];


export const ListDocumentCollaborators200CurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
