/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListNotificationsAll = typeof ListNotificationsAll[keyof typeof ListNotificationsAll];


export const ListNotificationsAll = {
  NUMBER_1: '1',
} as const;
