/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocuments200DocumentsItemPendingPRsItemApprovalState = typeof ListDocuments200DocumentsItemPendingPRsItemApprovalState[keyof typeof ListDocuments200DocumentsItemPendingPRsItemApprovalState];


export const ListDocuments200DocumentsItemPendingPRsItemApprovalState = {
  working: 'working',
  in_review: 'in_review',
  changes_requested: 'changes_requested',
  approved: 'approved',
  published: 'published',
} as const;
