/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListOrganizationInvitations200InvitationsItemBinderLevel } from './listOrganizationInvitations200InvitationsItemBinderLevel.ts';
import type { ListOrganizationInvitations200InvitationsItemOrgRole } from './listOrganizationInvitations200InvitationsItemOrgRole.ts';
import type { ListOrganizationInvitations200InvitationsItemStatus } from './listOrganizationInvitations200InvitationsItemStatus.ts';

export type ListOrganizationInvitations200InvitationsItem = {
  id: string;
  email: string;
  orgRole: ListOrganizationInvitations200InvitationsItemOrgRole;
  /** @nullable */
  binder: string | null;
  /** @nullable */
  binderLevel: ListOrganizationInvitations200InvitationsItemBinderLevel;
  grant: string;
  invitedBy: string;
  createdAt: number;
  expiresAt: number;
  status: ListOrganizationInvitations200InvitationsItemStatus;
};
