/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ListOrganizationInvitations200InvitationsItemBinderLevel = typeof ListOrganizationInvitations200InvitationsItemBinderLevel[keyof typeof ListOrganizationInvitations200InvitationsItemBinderLevel] | null;


export const ListOrganizationInvitations200InvitationsItemBinderLevel = {
  admin: 'admin',
  editor: 'editor',
  reviewer: 'reviewer',
} as const;
