/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChanges200ChangesItem } from './listBinderChanges200ChangesItem.ts';
import type { ListBinderChanges200State } from './listBinderChanges200State.ts';

export type ListBinderChanges200 = {
  organization: string;
  workspace: string;
  state: ListBinderChanges200State;
  changes: ListBinderChanges200ChangesItem[];
};
