/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChanges200ChangesItemReviewsItemAuthor } from './listBinderChanges200ChangesItemReviewsItemAuthor.ts';
import type { ListBinderChanges200ChangesItemReviewsItemState } from './listBinderChanges200ChangesItemReviewsItemState.ts';

export type ListBinderChanges200ChangesItemReviewsItem = {
  id: number;
  author: ListBinderChanges200ChangesItemReviewsItemAuthor;
  state: ListBinderChanges200ChangesItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
