/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderCollaborators200CurrentUserPermissionAccess = typeof ListBinderCollaborators200CurrentUserPermissionAccess[keyof typeof ListBinderCollaborators200CurrentUserPermissionAccess];


export const ListBinderCollaborators200CurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
