/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListNotifications200NotificationsItemReason } from './listNotifications200NotificationsItemReason.ts';

export type ListNotifications200NotificationsItem = {
  id: number;
  unread: boolean;
  org: string;
  binder: string;
  changeNumber: number;
  title: string;
  reason: ListNotifications200NotificationsItemReason;
  /** @nullable */
  actor: string | null;
  /** @nullable */
  actorName: string | null;
  updatedAt: string;
};
