/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DocumentsItemLatestTag } from './listDocuments200DocumentsItemLatestTag';
import type { ListDocuments200DocumentsItemPendingPRsItem } from './listDocuments200DocumentsItemPendingPRsItem';
import type { ListDocuments200DocumentsItemRepo } from './listDocuments200DocumentsItemRepo';

export type ListDocuments200DocumentsItem = {
  repo: ListDocuments200DocumentsItemRepo;
  /** @nullable */
  latestTag: ListDocuments200DocumentsItemLatestTag;
  pendingPRs: ListDocuments200DocumentsItemPendingPRsItem[];
  /** @nullable */
  error: string | null;
};
