/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListOrganizationBinders200WorkspacesItem } from './listOrganizationBinders200WorkspacesItem.ts';

export type ListOrganizationBinders200 = {
  workspaces: ListOrganizationBinders200WorkspacesItem[];
};
