/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderChanges200ChangesItemReviewsItemState = typeof ListBinderChanges200ChangesItemReviewsItemState[keyof typeof ListBinderChanges200ChangesItemReviewsItemState];


export const ListBinderChanges200ChangesItemReviewsItemState = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  other: 'other',
} as const;
