/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChangeDiscussions200ThreadsItemEventsItemActor } from './listBinderChangeDiscussions200ThreadsItemEventsItemActor.ts';

export type ListBinderChangeDiscussions200ThreadsItemEventsItem = {
  id: number;
  actor: ListBinderChangeDiscussions200ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
