/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderCollaborators200CollaboratorsItem } from './listBinderCollaborators200CollaboratorsItem.ts';
import type { ListBinderCollaborators200CurrentUserPermission } from './listBinderCollaborators200CurrentUserPermission.ts';

export type ListBinderCollaborators200 = {
  collaborators: ListBinderCollaborators200CollaboratorsItem[];
  page: number;
  limit: number;
  hasMore: boolean;
  /** @nullable */
  currentUserPermission: ListBinderCollaborators200CurrentUserPermission;
};
