/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChangeUpdates200UpdatesItem } from './listBinderChangeUpdates200UpdatesItem.ts';

export type ListBinderChangeUpdates200 = {
  updates: ListBinderChangeUpdates200UpdatesItem[];
  resetsApprovals: boolean;
};
