/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentCollaborators200CollaboratorsItemAccess } from "./listDocumentCollaborators200CollaboratorsItemAccess";
import type { ListDocumentCollaborators200CollaboratorsItemUser } from "./listDocumentCollaborators200CollaboratorsItemUser";

export type ListDocumentCollaborators200CollaboratorsItem = {
  permission: string;
  access: ListDocumentCollaborators200CollaboratorsItemAccess;
  permissionLabel: string;
  roleName: string;
  user: ListDocumentCollaborators200CollaboratorsItemUser;
};
