/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DocumentsItem } from './listDocuments200DocumentsItem.ts';

export type ListDocuments200 = {
  documents: ListDocuments200DocumentsItem[];
  page: number;
  limit: number;
  hasMore: boolean;
};
