/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DocumentsItem } from './listDocuments200DocumentsItem';

export type ListDocuments200 = {
  documents: ListDocuments200DocumentsItem[];
};
