/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChangeDiscussions200ThreadsItem } from './listBinderChangeDiscussions200ThreadsItem.ts';

export type ListBinderChangeDiscussions200 = {
  threads: ListBinderChangeDiscussions200ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
