/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentDiscussions200ThreadsItem } from './listDocumentDiscussions200ThreadsItem.ts';

export type ListDocumentDiscussions200 = {
  threads: ListDocumentDiscussions200ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
