/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderChanges200ChangesItemOutcome = typeof ListBinderChanges200ChangesItemOutcome[keyof typeof ListBinderChanges200ChangesItemOutcome];


export const ListBinderChanges200ChangesItemOutcome = {
  open: 'open',
  published: 'published',
  declined: 'declined',
  withdrawn: 'withdrawn',
} as const;
