/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentDiscussions200ThreadsItemCommentsItem } from './listDocumentDiscussions200ThreadsItemCommentsItem.ts';
import type { ListDocumentDiscussions200ThreadsItemEventsItem } from './listDocumentDiscussions200ThreadsItemEventsItem.ts';
import type { ListDocumentDiscussions200ThreadsItemOrigin } from './listDocumentDiscussions200ThreadsItemOrigin.ts';
import type { ListDocumentDiscussions200ThreadsItemReactionsItem } from './listDocumentDiscussions200ThreadsItemReactionsItem.ts';
import type { ListDocumentDiscussions200ThreadsItemResolvedBy } from './listDocumentDiscussions200ThreadsItemResolvedBy.ts';

export type ListDocumentDiscussions200ThreadsItem = {
  id: string;
  origin: ListDocumentDiscussions200ThreadsItemOrigin;
  comments: ListDocumentDiscussions200ThreadsItemCommentsItem[];
  events: ListDocumentDiscussions200ThreadsItemEventsItem[];
  reactions: ListDocumentDiscussions200ThreadsItemReactionsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: ListDocumentDiscussions200ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
