/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderChangeDiscussions200ThreadsItemOrigin = typeof ListBinderChangeDiscussions200ThreadsItemOrigin[keyof typeof ListBinderChangeDiscussions200ThreadsItemOrigin];


export const ListBinderChangeDiscussions200ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
