/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderDocuments200DocumentsItemLatestVersion } from './listBinderDocuments200DocumentsItemLatestVersion.ts';
import type { ListBinderDocuments200DocumentsItemState } from './listBinderDocuments200DocumentsItemState.ts';

export type ListBinderDocuments200DocumentsItem = {
  path: string;
  slugPath: string;
  name: string;
  folder: string;
  size: number;
  sha: string;
  state: ListBinderDocuments200DocumentsItemState;
  openChangeCount: number;
  /** @nullable */
  latestVersion: ListBinderDocuments200DocumentsItemLatestVersion;
};
