/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderCollaborators200CollaboratorsItemAccess = typeof ListBinderCollaborators200CollaboratorsItemAccess[keyof typeof ListBinderCollaborators200CollaboratorsItemAccess];


export const ListBinderCollaborators200CollaboratorsItemAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
