/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderChanges200ChangesItemReviewersItemStatus = typeof ListBinderChanges200ChangesItemReviewersItemStatus[keyof typeof ListBinderChanges200ChangesItemReviewersItemStatus];


export const ListBinderChanges200ChangesItemReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
