/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentCollaborators200CollaboratorsItem } from './listDocumentCollaborators200CollaboratorsItem.ts';
import type { ListDocumentCollaborators200CurrentUserPermission } from './listDocumentCollaborators200CurrentUserPermission.ts';

export type ListDocumentCollaborators200 = {
  collaborators: ListDocumentCollaborators200CollaboratorsItem[];
  page: number;
  limit: number;
  hasMore: boolean;
  /** @nullable */
  currentUserPermission: ListDocumentCollaborators200CurrentUserPermission;
};
