/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemContent } from './listBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemContent.ts';
import type { ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemUsersItem } from './listBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItem = {
  content: ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItemUsersItem[];
};
