/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinderDocuments200DocumentsItemState = typeof ListBinderDocuments200DocumentsItemState[keyof typeof ListBinderDocuments200DocumentsItemState];


export const ListBinderDocuments200DocumentsItemState = {
  published: 'published',
  proposed: 'proposed',
} as const;
