/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocumentDiscussions200ThreadsItemOrigin = typeof ListDocumentDiscussions200ThreadsItemOrigin[keyof typeof ListDocumentDiscussions200ThreadsItemOrigin];


export const ListDocumentDiscussions200ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
