/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChangeDiscussions200ThreadsItemCommentsItemAuthor } from './listBinderChangeDiscussions200ThreadsItemCommentsItemAuthor.ts';
import type { ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItem } from './listBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItem.ts';

export type ListBinderChangeDiscussions200ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: ListBinderChangeDiscussions200ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: ListBinderChangeDiscussions200ThreadsItemCommentsItemReactionsItem[];
};
