/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListNotifications200NotificationsItemReason = typeof ListNotifications200NotificationsItemReason[keyof typeof ListNotifications200NotificationsItemReason];


export const ListNotifications200NotificationsItemReason = {
  review_requested: 'review_requested',
  your_change: 'your_change',
  published: 'published',
  closed: 'closed',
  activity: 'activity',
} as const;
