/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAdminSubscriptionAccess200UsersItem } from './listAdminSubscriptionAccess200UsersItem.ts';

export type ListAdminSubscriptionAccess200 = {
  users: ListAdminSubscriptionAccess200UsersItem[];
  page: number;
  limit: number;
  hasMore: boolean;
  query: string;
};
