/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListAdminSubscriptionAccess200UsersItemOverrideAccess = typeof ListAdminSubscriptionAccess200UsersItemOverrideAccess[keyof typeof ListAdminSubscriptionAccess200UsersItemOverrideAccess];


export const ListAdminSubscriptionAccess200UsersItemOverrideAccess = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
