/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocuments200DocumentsItemPendingPRsItemReviewsItemState = typeof ListDocuments200DocumentsItemPendingPRsItemReviewsItemState[keyof typeof ListDocuments200DocumentsItemPendingPRsItemReviewsItemState];


export const ListDocuments200DocumentsItemPendingPRsItemReviewsItemState = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  other: 'other',
} as const;
