/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocuments200DocumentsItemState = typeof ListDocuments200DocumentsItemState[keyof typeof ListDocuments200DocumentsItemState];


export const ListDocuments200DocumentsItemState = {
  published: 'published',
  proposed: 'proposed',
} as const;
