/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListOrganizationInvitations200InvitationsItemStatus = typeof ListOrganizationInvitations200InvitationsItemStatus[keyof typeof ListOrganizationInvitations200InvitationsItemStatus];


export const ListOrganizationInvitations200InvitationsItemStatus = {
  pending: 'pending',
  accepted: 'accepted',
  joined: 'joined',
  revoked: 'revoked',
  expired: 'expired',
} as const;
