/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ListDocuments200DocumentsItemPendingPRsItemUser = {
  login: string;
} | null;
