/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChanges200ChangesItemAssignee } from './listBinderChanges200ChangesItemAssignee.ts';
import type { ListBinderChanges200ChangesItemDocumentsItem } from './listBinderChanges200ChangesItemDocumentsItem.ts';
import type { ListBinderChanges200ChangesItemOutcome } from './listBinderChanges200ChangesItemOutcome.ts';
import type { ListBinderChanges200ChangesItemReviewersItem } from './listBinderChanges200ChangesItemReviewersItem.ts';
import type { ListBinderChanges200ChangesItemReviewsItem } from './listBinderChanges200ChangesItemReviewsItem.ts';

export type ListBinderChanges200ChangesItem = {
  number: number;
  title: string;
  body: string;
  branchName: string;
  submittedBy: string;
  submittedAt: string;
  /** @nullable */
  closedAt: string | null;
  outcome: ListBinderChanges200ChangesItemOutcome;
  /** @nullable */
  decidedBy: string | null;
  approvalState: string;
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
  isApproved: boolean;
  isRejected: boolean;
  reviews: ListBinderChanges200ChangesItemReviewsItem[];
  reviewers: ListBinderChanges200ChangesItemReviewersItem[];
  /** @nullable */
  assignee: ListBinderChanges200ChangesItemAssignee;
  documents: ListBinderChanges200ChangesItemDocumentsItem[];
};
