/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListOrganizationInvitations200InvitationsItemOrgRole = typeof ListOrganizationInvitations200InvitationsItemOrgRole[keyof typeof ListOrganizationInvitations200InvitationsItemOrgRole];


export const ListOrganizationInvitations200InvitationsItemOrgRole = {
  owner: 'owner',
  member: 'member',
} as const;
