/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DocumentsItemPendingPRsItemReviewsItemAuthor } from './listDocuments200DocumentsItemPendingPRsItemReviewsItemAuthor.ts';
import type { ListDocuments200DocumentsItemPendingPRsItemReviewsItemState } from './listDocuments200DocumentsItemPendingPRsItemReviewsItemState.ts';

export type ListDocuments200DocumentsItemPendingPRsItemReviewsItem = {
  id: number;
  author: ListDocuments200DocumentsItemPendingPRsItemReviewsItemAuthor;
  state: ListDocuments200DocumentsItemPendingPRsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
