/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBinderChangeDiscussions200ThreadsItemCommentsItem } from './listBinderChangeDiscussions200ThreadsItemCommentsItem.ts';
import type { ListBinderChangeDiscussions200ThreadsItemEventsItem } from './listBinderChangeDiscussions200ThreadsItemEventsItem.ts';
import type { ListBinderChangeDiscussions200ThreadsItemOrigin } from './listBinderChangeDiscussions200ThreadsItemOrigin.ts';
import type { ListBinderChangeDiscussions200ThreadsItemResolvedBy } from './listBinderChangeDiscussions200ThreadsItemResolvedBy.ts';

export type ListBinderChangeDiscussions200ThreadsItem = {
  id: string;
  origin: ListBinderChangeDiscussions200ThreadsItemOrigin;
  comments: ListBinderChangeDiscussions200ThreadsItemCommentsItem[];
  events: ListBinderChangeDiscussions200ThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: ListBinderChangeDiscussions200ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
