/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAdminSubscriptionAccess200UsersItemOverrideAccess } from './listAdminSubscriptionAccess200UsersItemOverrideAccess.ts';
import type { ListAdminSubscriptionAccess200UsersItemOverrideMode } from './listAdminSubscriptionAccess200UsersItemOverrideMode.ts';

/**
 * @nullable
 */
export type ListAdminSubscriptionAccess200UsersItemOverride = {
  access: ListAdminSubscriptionAccess200UsersItemOverrideAccess;
  mode?: ListAdminSubscriptionAccess200UsersItemOverrideMode;
  /** @nullable */
  reason?: string | null;
  updatedBy: string;
  updatedAt: number;
} | null;
