/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentCollaborators200CurrentUserPermissionAccess } from './listDocumentCollaborators200CurrentUserPermissionAccess.ts';
import type { ListDocumentCollaborators200CurrentUserPermissionUser } from './listDocumentCollaborators200CurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type ListDocumentCollaborators200CurrentUserPermission = {
  permission: string;
  access: ListDocumentCollaborators200CurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: ListDocumentCollaborators200CurrentUserPermissionUser;
} | null;
