/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocumentDiscussions200ThreadsItemCommentsItemReactionsItemContent } from './listDocumentDiscussions200ThreadsItemCommentsItemReactionsItemContent.ts';
import type { ListDocumentDiscussions200ThreadsItemCommentsItemReactionsItemUsersItem } from './listDocumentDiscussions200ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type ListDocumentDiscussions200ThreadsItemCommentsItemReactionsItem = {
  content: ListDocumentDiscussions200ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: ListDocumentDiscussions200ThreadsItemCommentsItemReactionsItemUsersItem[];
};
