/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListChangeUpdates200UpdatesItem } from './listChangeUpdates200UpdatesItem.ts';

export type ListChangeUpdates200 = {
  updates: ListChangeUpdates200UpdatesItem[];
  resetsApprovals: boolean;
};
