/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAdminSubscriptionAccess200UsersItemAccessSource } from './listAdminSubscriptionAccess200UsersItemAccessSource';
import type { ListAdminSubscriptionAccess200UsersItemOverride } from './listAdminSubscriptionAccess200UsersItemOverride';

export type ListAdminSubscriptionAccess200UsersItem = {
  username: string;
  fullName?: string;
  email?: string;
  hasAccess: boolean;
  accessSource: ListAdminSubscriptionAccess200UsersItemAccessSource;
  /** @nullable */
  stripeStatus: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  /** @nullable */
  override: ListAdminSubscriptionAccess200UsersItemOverride;
};
