/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ListBinders200WorkspacesItem = {
  id: number;
  name: string;
  owner: string;
  fullName: string;
  description: string;
};
