/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type OpenBinderDraft201DraftActsItem = {
  summary: string;
  sha: string;
  /** @nullable */
  at: string | null;
  paths: string[];
};
