/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { OpenBinderDraft201Draft } from './openBinderDraft201Draft.ts';
import type { OpenBinderDraft201OthersItem } from './openBinderDraft201OthersItem.ts';

export type OpenBinderDraft201 = {
  organization: string;
  workspace: string;
  /** @nullable */
  draft: OpenBinderDraft201Draft;
  others: OpenBinderDraft201OthersItem[];
};
