/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { OpenBinderDraft201DraftActsItem } from './openBinderDraft201DraftActsItem.ts';

/**
 * @nullable
 */
export type OpenBinderDraft201Draft = {
  branch: string;
  owner: string;
  /** @nullable */
  updatedAt: string | null;
  acts: OpenBinderDraft201DraftActsItem[];
} | null;
