/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type OpenBinderDraft201DraftsItem = {
  branch: string;
  name: string;
  /** @nullable */
  updatedAt: string | null;
  actCount: number;
  /** @nullable */
  lastAct: string | null;
};
