/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ProposeBinderSignOffRulesBodyRulesItemScope = typeof ProposeBinderSignOffRulesBodyRulesItemScope[keyof typeof ProposeBinderSignOffRulesBodyRulesItemScope];


export const ProposeBinderSignOffRulesBodyRulesItemScope = {
  binder: 'binder',
  folder: 'folder',
  document: 'document',
} as const;
