/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ProposeBinderSignOffRulesBodyRulesItemScope } from './proposeBinderSignOffRulesBodyRulesItemScope.ts';

export type ProposeBinderSignOffRulesBodyRulesItem = {
  scope: ProposeBinderSignOffRulesBodyRulesItemScope;
  target: string;
  teams: string[];
  users: string[];
};
