/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { PublishBinderChange200TagsItem } from './publishBinderChange200TagsItem.ts';

export type PublishBinderChange200 = {
  ok: boolean;
  tags: PublishBinderChange200TagsItem[];
};
