/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { PublishDocument200Tag } from "./publishDocument200Tag";

export type PublishDocument200 = {
  ok: boolean;
  tag: PublishDocument200Tag;
};
