/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { PublishDocument200Tag } from './publishDocument200Tag.ts';

export type PublishDocument200 = {
  ok: boolean;
  tag: PublishDocument200Tag;
};
