/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type PublishBinderChange200TagsItem = {
  tag: string;
  version: number;
  commitSha: string;
};
