/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReactToDocumentDiscussion200ThreadsItemCommentsItemAuthor } from './reactToDocumentDiscussion200ThreadsItemCommentsItemAuthor.ts';

export type ReactToDocumentDiscussion200ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: ReactToDocumentDiscussion200ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
};
