/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ReactToDocumentDiscussion200ThreadsItemOrigin = typeof ReactToDocumentDiscussion200ThreadsItemOrigin[keyof typeof ReactToDocumentDiscussion200ThreadsItemOrigin];


export const ReactToDocumentDiscussion200ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
