/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReactToDocumentDiscussion200ThreadsItemEventsItemActor } from './reactToDocumentDiscussion200ThreadsItemEventsItemActor.ts';

export type ReactToDocumentDiscussion200ThreadsItemEventsItem = {
  id: number;
  actor: ReactToDocumentDiscussion200ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
