/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReactToDocumentDiscussion200ThreadsItemCommentsItem } from './reactToDocumentDiscussion200ThreadsItemCommentsItem.ts';
import type { ReactToDocumentDiscussion200ThreadsItemEventsItem } from './reactToDocumentDiscussion200ThreadsItemEventsItem.ts';
import type { ReactToDocumentDiscussion200ThreadsItemOrigin } from './reactToDocumentDiscussion200ThreadsItemOrigin.ts';
import type { ReactToDocumentDiscussion200ThreadsItemReactionsItem } from './reactToDocumentDiscussion200ThreadsItemReactionsItem.ts';
import type { ReactToDocumentDiscussion200ThreadsItemResolvedBy } from './reactToDocumentDiscussion200ThreadsItemResolvedBy.ts';

export type ReactToDocumentDiscussion200ThreadsItem = {
  id: string;
  origin: ReactToDocumentDiscussion200ThreadsItemOrigin;
  comments: ReactToDocumentDiscussion200ThreadsItemCommentsItem[];
  events: ReactToDocumentDiscussion200ThreadsItemEventsItem[];
  reactions: ReactToDocumentDiscussion200ThreadsItemReactionsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: ReactToDocumentDiscussion200ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
