/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReactToDocumentDiscussion200ThreadsItem } from './reactToDocumentDiscussion200ThreadsItem.ts';

export type ReactToDocumentDiscussion200 = {
  threads: ReactToDocumentDiscussion200ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
