/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveBinderPerson200GroupsItem } from './removeBinderPerson200GroupsItem.ts';
import type { RemoveBinderPerson200OrganizationMembersItem } from './removeBinderPerson200OrganizationMembersItem.ts';
import type { RemoveBinderPerson200PeopleItem } from './removeBinderPerson200PeopleItem.ts';

export type RemoveBinderPerson200 = {
  organization: string;
  workspace: string;
  people: RemoveBinderPerson200PeopleItem[];
  groups: RemoveBinderPerson200GroupsItem[];
  openToOrganization: boolean;
  organizationMembers: RemoveBinderPerson200OrganizationMembersItem[];
  canManage: boolean;
};
