/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveOrganizationGroupMember200GroupsItemMembersItem } from './removeOrganizationGroupMember200GroupsItemMembersItem.ts';

export type RemoveOrganizationGroupMember200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  memberCount: number;
  members: RemoveOrganizationGroupMember200GroupsItemMembersItem[];
};
