/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveOrganizationPerson200GroupsItemMembersItem } from './removeOrganizationPerson200GroupsItemMembersItem.ts';

export type RemoveOrganizationPerson200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  memberCount: number;
  members: RemoveOrganizationPerson200GroupsItemMembersItem[];
  binders: string[];
};
