/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveBinderPerson200GroupsItemMembersItem } from './removeBinderPerson200GroupsItemMembersItem.ts';

export type RemoveBinderPerson200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: RemoveBinderPerson200GroupsItemMembersItem[];
};
