/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveOrganizationGroupMember200GroupsItem } from './removeOrganizationGroupMember200GroupsItem.ts';
import type { RemoveOrganizationGroupMember200PeopleItem } from './removeOrganizationGroupMember200PeopleItem.ts';

export type RemoveOrganizationGroupMember200 = {
  organization: string;
  people: RemoveOrganizationGroupMember200PeopleItem[];
  groups: RemoveOrganizationGroupMember200GroupsItem[];
  canManage: boolean;
};
