/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RemoveOrganizationPerson200GroupsItem } from './removeOrganizationPerson200GroupsItem.ts';
import type { RemoveOrganizationPerson200PeopleItem } from './removeOrganizationPerson200PeopleItem.ts';

export type RemoveOrganizationPerson200 = {
  organization: string;
  people: RemoveOrganizationPerson200PeopleItem[];
  groups: RemoveOrganizationPerson200GroupsItem[];
  binders: string[];
  canManage: boolean;
  viewer: string;
};
