/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RenameBinderDraft200Draft } from './renameBinderDraft200Draft.ts';
import type { RenameBinderDraft200DraftsItem } from './renameBinderDraft200DraftsItem.ts';
import type { RenameBinderDraft200OthersItem } from './renameBinderDraft200OthersItem.ts';

export type RenameBinderDraft200 = {
  organization: string;
  workspace: string;
  /** @nullable */
  draft: RenameBinderDraft200Draft;
  drafts: RenameBinderDraft200DraftsItem[];
  others: RenameBinderDraft200OthersItem[];
};
