/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ReplyToBinderChangeDiscussion201ThreadsItemOrigin = typeof ReplyToBinderChangeDiscussion201ThreadsItemOrigin[keyof typeof ReplyToBinderChangeDiscussion201ThreadsItemOrigin];


export const ReplyToBinderChangeDiscussion201ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
