/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemContent } from './replyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemContent.ts';
import type { ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem } from './replyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem = {
  content: ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem[];
};
