/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent } from './replyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent.ts';
import type { ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem } from './replyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItem = {
  content: ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemUsersItem[];
};
