/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent = typeof ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent[keyof typeof ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent];


export const ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItemContent = {
  '+1': '+1',
  NUMBER_MINUS_1: '-1',
  confused: 'confused',
  eyes: 'eyes',
  heart: 'heart',
} as const;
