/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToBinderChangeDiscussion201ThreadsItem } from './replyToBinderChangeDiscussion201ThreadsItem.ts';

export type ReplyToBinderChangeDiscussion201 = {
  threads: ReplyToBinderChangeDiscussion201ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
