/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ReplyToDocumentDiscussion201ThreadsItemOrigin = typeof ReplyToDocumentDiscussion201ThreadsItemOrigin[keyof typeof ReplyToDocumentDiscussion201ThreadsItemOrigin];


export const ReplyToDocumentDiscussion201ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
