/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToDocumentDiscussion201ThreadsItemCommentsItemAuthor } from './replyToDocumentDiscussion201ThreadsItemCommentsItemAuthor.ts';
import type { ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItem } from './replyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItem.ts';

export type ReplyToDocumentDiscussion201ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: ReplyToDocumentDiscussion201ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: ReplyToDocumentDiscussion201ThreadsItemCommentsItemReactionsItem[];
};
