/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemAuthor } from './replyToBinderChangeDiscussion201ThreadsItemCommentsItemAuthor.ts';
import type { ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem } from './replyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem.ts';

export type ReplyToBinderChangeDiscussion201ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: ReplyToBinderChangeDiscussion201ThreadsItemCommentsItemReactionsItem[];
};
