/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToDocumentDiscussion201ThreadsItem } from './replyToDocumentDiscussion201ThreadsItem.ts';

export type ReplyToDocumentDiscussion201 = {
  threads: ReplyToDocumentDiscussion201ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
