/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToBinderChangeDiscussion201ThreadsItemEventsItemActor } from './replyToBinderChangeDiscussion201ThreadsItemEventsItemActor.ts';

export type ReplyToBinderChangeDiscussion201ThreadsItemEventsItem = {
  id: number;
  actor: ReplyToBinderChangeDiscussion201ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
