/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToDocumentDiscussion201ThreadsItemEventsItemActor } from './replyToDocumentDiscussion201ThreadsItemEventsItemActor.ts';

export type ReplyToDocumentDiscussion201ThreadsItemEventsItem = {
  id: number;
  actor: ReplyToDocumentDiscussion201ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
