/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReplyToBinderChangeDiscussion201ThreadsItemCommentsItem } from './replyToBinderChangeDiscussion201ThreadsItemCommentsItem.ts';
import type { ReplyToBinderChangeDiscussion201ThreadsItemEventsItem } from './replyToBinderChangeDiscussion201ThreadsItemEventsItem.ts';
import type { ReplyToBinderChangeDiscussion201ThreadsItemOrigin } from './replyToBinderChangeDiscussion201ThreadsItemOrigin.ts';
import type { ReplyToBinderChangeDiscussion201ThreadsItemResolvedBy } from './replyToBinderChangeDiscussion201ThreadsItemResolvedBy.ts';

export type ReplyToBinderChangeDiscussion201ThreadsItem = {
  id: string;
  origin: ReplyToBinderChangeDiscussion201ThreadsItemOrigin;
  comments: ReplyToBinderChangeDiscussion201ThreadsItemCommentsItem[];
  events: ReplyToBinderChangeDiscussion201ThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: ReplyToBinderChangeDiscussion201ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
