/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ResendOrganizationInvitation200InvitationOrgRole = typeof ResendOrganizationInvitation200InvitationOrgRole[keyof typeof ResendOrganizationInvitation200InvitationOrgRole];


export const ResendOrganizationInvitation200InvitationOrgRole = {
  owner: 'owner',
  member: 'member',
} as const;
