/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ResendOrganizationInvitation200InvitationBinderLevel = typeof ResendOrganizationInvitation200InvitationBinderLevel[keyof typeof ResendOrganizationInvitation200InvitationBinderLevel] | null;


export const ResendOrganizationInvitation200InvitationBinderLevel = {
  admin: 'admin',
  editor: 'editor',
  reviewer: 'reviewer',
} as const;
