/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResendOrganizationInvitation200Invitation } from './resendOrganizationInvitation200Invitation.ts';

export type ResendOrganizationInvitation200 = {
  invitation: ResendOrganizationInvitation200Invitation;
};
