/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResendOrganizationInvitation200InvitationBinderLevel } from './resendOrganizationInvitation200InvitationBinderLevel.ts';
import type { ResendOrganizationInvitation200InvitationOrgRole } from './resendOrganizationInvitation200InvitationOrgRole.ts';
import type { ResendOrganizationInvitation200InvitationStatus } from './resendOrganizationInvitation200InvitationStatus.ts';

export type ResendOrganizationInvitation200Invitation = {
  id: string;
  email: string;
  orgRole: ResendOrganizationInvitation200InvitationOrgRole;
  /** @nullable */
  binder: string | null;
  /** @nullable */
  binderLevel: ResendOrganizationInvitation200InvitationBinderLevel;
  grant: string;
  invitedBy: string;
  createdAt: number;
  expiresAt: number;
  status: ResendOrganizationInvitation200InvitationStatus;
};
