/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ResendOrganizationInvitation200InvitationStatus = typeof ResendOrganizationInvitation200InvitationStatus[keyof typeof ResendOrganizationInvitation200InvitationStatus];


export const ResendOrganizationInvitation200InvitationStatus = {
  pending: 'pending',
  accepted: 'accepted',
  joined: 'joined',
  revoked: 'revoked',
  expired: 'expired',
} as const;
