/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveBinderChangeDiscussion200ThreadsItem } from './resolveBinderChangeDiscussion200ThreadsItem.ts';

export type ResolveBinderChangeDiscussion200 = {
  threads: ResolveBinderChangeDiscussion200ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
