/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemContent } from './resolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemContent.ts';
import type { ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemUsersItem } from './resolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItem = {
  content: ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemUsersItem[];
};
