/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveDocumentDiscussion200ThreadsItemCommentsItem } from './resolveDocumentDiscussion200ThreadsItemCommentsItem.ts';
import type { ResolveDocumentDiscussion200ThreadsItemEventsItem } from './resolveDocumentDiscussion200ThreadsItemEventsItem.ts';
import type { ResolveDocumentDiscussion200ThreadsItemOrigin } from './resolveDocumentDiscussion200ThreadsItemOrigin.ts';
import type { ResolveDocumentDiscussion200ThreadsItemResolvedBy } from './resolveDocumentDiscussion200ThreadsItemResolvedBy.ts';

export type ResolveDocumentDiscussion200ThreadsItem = {
  id: string;
  origin: ResolveDocumentDiscussion200ThreadsItemOrigin;
  comments: ResolveDocumentDiscussion200ThreadsItemCommentsItem[];
  events: ResolveDocumentDiscussion200ThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: ResolveDocumentDiscussion200ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
