/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveBinderChangeDiscussion200ThreadsItemCommentsItemAuthor } from './resolveBinderChangeDiscussion200ThreadsItemCommentsItemAuthor.ts';
import type { ResolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItem } from './resolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItem.ts';

export type ResolveBinderChangeDiscussion200ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: ResolveBinderChangeDiscussion200ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: ResolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItem[];
};
