/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveBinderChangeConflictsBodyResolutionsItemTake } from './resolveBinderChangeConflictsBodyResolutionsItemTake.ts';

export type ResolveBinderChangeConflictsBodyResolutionsItem = {
  key: string;
  take: ResolveBinderChangeConflictsBodyResolutionsItemTake;
  base64Content?: string;
};
