/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ResolveDocumentDiscussion200ThreadsItemOrigin = typeof ResolveDocumentDiscussion200ThreadsItemOrigin[keyof typeof ResolveDocumentDiscussion200ThreadsItemOrigin];


export const ResolveDocumentDiscussion200ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
