/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItemContent } from './resolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItemContent.ts';
import type { ResolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItemUsersItem } from './resolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type ResolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItem = {
  content: ResolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: ResolveBinderChangeDiscussion200ThreadsItemCommentsItemReactionsItemUsersItem[];
};
