/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveBinderChangeConflictsBodyResolutionsItem } from './resolveBinderChangeConflictsBodyResolutionsItem.ts';

export type ResolveBinderChangeConflictsBody = {
  headSha: string;
  baseSha: string;
  resolutions: ResolveBinderChangeConflictsBodyResolutionsItem[];
};
