/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveDocumentDiscussion200ThreadsItemCommentsItemAuthor } from './resolveDocumentDiscussion200ThreadsItemCommentsItemAuthor.ts';
import type { ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItem } from './resolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItem.ts';

export type ResolveDocumentDiscussion200ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: ResolveDocumentDiscussion200ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItem[];
};
