/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveDocumentDiscussion200ThreadsItemEventsItemActor } from './resolveDocumentDiscussion200ThreadsItemEventsItemActor.ts';

export type ResolveDocumentDiscussion200ThreadsItemEventsItem = {
  id: number;
  actor: ResolveDocumentDiscussion200ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
