/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveBinderChangeDiscussion200ThreadsItemEventsItemActor } from './resolveBinderChangeDiscussion200ThreadsItemEventsItemActor.ts';

export type ResolveBinderChangeDiscussion200ThreadsItemEventsItem = {
  id: number;
  actor: ResolveBinderChangeDiscussion200ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
