/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ResolveBinderChangeDiscussion200ThreadsItemOrigin = typeof ResolveBinderChangeDiscussion200ThreadsItemOrigin[keyof typeof ResolveBinderChangeDiscussion200ThreadsItemOrigin];


export const ResolveBinderChangeDiscussion200ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
