/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ResolveBinderChangeConflictsBodyResolutionsItemTake = typeof ResolveBinderChangeConflictsBodyResolutionsItemTake[keyof typeof ResolveBinderChangeConflictsBodyResolutionsItemTake];


export const ResolveBinderChangeConflictsBodyResolutionsItemTake = {
  ours: 'ours',
  theirs: 'theirs',
  none: 'none',
  content: 'content',
} as const;
