/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveBinderChangeDiscussion200ThreadsItemCommentsItem } from './resolveBinderChangeDiscussion200ThreadsItemCommentsItem.ts';
import type { ResolveBinderChangeDiscussion200ThreadsItemEventsItem } from './resolveBinderChangeDiscussion200ThreadsItemEventsItem.ts';
import type { ResolveBinderChangeDiscussion200ThreadsItemOrigin } from './resolveBinderChangeDiscussion200ThreadsItemOrigin.ts';
import type { ResolveBinderChangeDiscussion200ThreadsItemResolvedBy } from './resolveBinderChangeDiscussion200ThreadsItemResolvedBy.ts';

export type ResolveBinderChangeDiscussion200ThreadsItem = {
  id: string;
  origin: ResolveBinderChangeDiscussion200ThreadsItemOrigin;
  comments: ResolveBinderChangeDiscussion200ThreadsItemCommentsItem[];
  events: ResolveBinderChangeDiscussion200ThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: ResolveBinderChangeDiscussion200ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
