/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ResolveDocumentDiscussion200ThreadsItem } from './resolveDocumentDiscussion200ThreadsItem.ts';

export type ResolveDocumentDiscussion200 = {
  threads: ResolveDocumentDiscussion200ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
