/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemContent = typeof ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemContent[keyof typeof ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemContent];


export const ResolveDocumentDiscussion200ThreadsItemCommentsItemReactionsItemContent = {
  '+1': '+1',
  NUMBER_MINUS_1: '-1',
  confused: 'confused',
  eyes: 'eyes',
  heart: 'heart',
} as const;
