/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type ReviewBinderChangeBodyEvent = typeof ReviewBinderChangeBodyEvent[keyof typeof ReviewBinderChangeBodyEvent];


export const ReviewBinderChangeBodyEvent = {
  APPROVE: 'APPROVE',
  REQUEST_CHANGES: 'REQUEST_CHANGES',
  COMMENT: 'COMMENT',
} as const;
