/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReviseBinderDocumentBodySource } from './reviseBinderDocumentBodySource.ts';

export type ReviseBinderDocumentBody = {
  /** File upload */
  file: Blob;
  documentPath: string;
  changeNumber?: string;
  draft?: string;
  source?: ReviseBinderDocumentBodySource;
};
