/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewBinderChangeBodyEvent } from './reviewBinderChangeBodyEvent.ts';

export type ReviewBinderChangeBody = {
  event: ReviewBinderChangeBodyEvent;
  body?: string;
};
