/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RevokeBinderGroup200TeamsItemMembersItem } from './revokeBinderGroup200TeamsItemMembersItem.ts';

export type RevokeBinderGroup200TeamsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: RevokeBinderGroup200TeamsItemMembersItem[];
};
