/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { RevokeBinderGroup200TeamsItem } from './revokeBinderGroup200TeamsItem.ts';

export type RevokeBinderGroup200 = {
  organization: string;
  workspace: string;
  teams: RevokeBinderGroup200TeamsItem[];
  approvalsWhitelist: string[];
};
