/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type SearchDocuments200DocumentsItemLastChange = {
  number: number;
  title: string;
  publishedAt: string;
} | null;
