/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchUsersPayloadUsersItem } from './searchUsersPayloadUsersItem.ts';

export interface SearchUsersPayload {
  users: SearchUsersPayloadUsersItem[];
  page: number;
  limit: number;
  hasMore: boolean;
}
