/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SearchDocuments200DocumentsItemState = typeof SearchDocuments200DocumentsItemState[keyof typeof SearchDocuments200DocumentsItemState];


export const SearchDocuments200DocumentsItemState = {
  published: 'published',
  proposed: 'proposed',
} as const;
