/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchDocuments200DocumentsItemOwner } from './searchDocuments200DocumentsItemOwner.ts';

export type SearchDocuments200DocumentsItem = {
  id: number;
  name: string;
  full_name: string;
  description: string;
  updated_at: string;
  owner: SearchDocuments200DocumentsItemOwner;
};
