/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchDocuments200DocumentsItemLatestVersion } from './searchDocuments200DocumentsItemLatestVersion.ts';
import type { SearchDocuments200DocumentsItemState } from './searchDocuments200DocumentsItemState.ts';

export type SearchDocuments200DocumentsItem = {
  /** @nullable */
  path: string | null;
  slugPath: string;
  name: string;
  folder: string;
  /** @nullable */
  size: number | null;
  /** @nullable */
  sha: string | null;
  state: SearchDocuments200DocumentsItemState;
  openChangeCount: number;
  /** @nullable */
  latestVersion: SearchDocuments200DocumentsItemLatestVersion;
  organization: string;
  binder: string;
  binderDescription: string;
};
