/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchUsers200UsersItem } from './searchUsers200UsersItem.ts';

export type SearchUsers200 = {
  users: SearchUsers200UsersItem[];
  page: number;
  limit: number;
  hasMore: boolean;
};
