/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchDocuments200DocumentsItem } from './searchDocuments200DocumentsItem.ts';

export type SearchDocuments200 = {
  documents: SearchDocuments200DocumentsItem[];
  page: number;
  limit: number;
  hasMore: boolean;
};
