/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionAuthStateUser } from './sessionAuthStateUser.ts';

export interface SessionAuthState {
  /** @nullable */
  user: SessionAuthStateUser;
  /** @nullable */
  token: string | null;
}
