/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionAuthStateUser } from "./sessionAuthStateUser";

export interface SessionAuthState {
  /** @nullable */
  user: SessionAuthStateUser;
  /** @nullable */
  token: string | null;
}
