/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SetAdminSubscriptionAccess200UserOverrideAccess = typeof SetAdminSubscriptionAccess200UserOverrideAccess[keyof typeof SetAdminSubscriptionAccess200UserOverrideAccess];


export const SetAdminSubscriptionAccess200UserOverrideAccess = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
