/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SetAdminSubscriptionAccessBodyAccess = typeof SetAdminSubscriptionAccessBodyAccess[keyof typeof SetAdminSubscriptionAccessBodyAccess];


export const SetAdminSubscriptionAccessBodyAccess = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
