/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetAdminSubscriptionAccess200UserAccessSource } from './setAdminSubscriptionAccess200UserAccessSource';
import type { SetAdminSubscriptionAccess200UserOverride } from './setAdminSubscriptionAccess200UserOverride';

export type SetAdminSubscriptionAccess200User = {
  username: string;
  fullName?: string;
  email?: string;
  hasAccess: boolean;
  accessSource: SetAdminSubscriptionAccess200UserAccessSource;
  /** @nullable */
  stripeStatus: string | null;
  /** @nullable */
  currentPeriodEnd: number | null;
  cancelAtPeriodEnd: boolean;
  /** @nullable */
  cancelAt: number | null;
  /** @nullable */
  override: SetAdminSubscriptionAccess200UserOverride;
};
