/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetAdminSubscriptionAccess200User } from "./setAdminSubscriptionAccess200User";

export type SetAdminSubscriptionAccess200 = {
  user: SetAdminSubscriptionAccess200User;
};
