/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SetAdminSubscriptionAccess200UserAccessSource = typeof SetAdminSubscriptionAccess200UserAccessSource[keyof typeof SetAdminSubscriptionAccess200UserAccessSource];


export const SetAdminSubscriptionAccess200UserAccessSource = {
  config_bypass: 'config_bypass',
  stripe: 'stripe',
  trial: 'trial',
  admin_grant: 'admin_grant',
  admin_revoke: 'admin_revoke',
  no_organization: 'no_organization',
  none: 'none',
} as const;
