/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SetAdminSubscriptionAccess200UserOverrideMode = typeof SetAdminSubscriptionAccess200UserOverrideMode[keyof typeof SetAdminSubscriptionAccess200UserOverrideMode];


export const SetAdminSubscriptionAccess200UserOverrideMode = {
  grant: 'grant',
  revoke: 'revoke',
} as const;
