/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetAdminSubscriptionAccess200UserOverrideAccess } from './setAdminSubscriptionAccess200UserOverrideAccess.ts';

/**
 * @nullable
 */
export type SetAdminSubscriptionAccess200UserOverride = {
  username: string;
  access: SetAdminSubscriptionAccess200UserOverrideAccess;
  updatedBy: string;
  updatedAt: number;
} | null;
