/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemContent } from './setBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemContent.ts';
import type { SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemUsersItem } from './setBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem = {
  content: SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemUsersItem[];
};
