/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderVisibility200GroupsItemMembersItem } from './setBinderVisibility200GroupsItemMembersItem.ts';

export type SetBinderVisibility200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: SetBinderVisibility200GroupsItemMembersItem[];
};
