/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemAuthor } from './setBinderDiscussionCommentReaction200ThreadsItemCommentsItemAuthor.ts';
import type { SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem } from './setBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem.ts';

export type SetBinderDiscussionCommentReaction200ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: SetBinderDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem[];
};
