/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderDiscussionCommentReaction200ThreadsItem } from './setBinderDiscussionCommentReaction200ThreadsItem.ts';

export type SetBinderDiscussionCommentReaction200 = {
  threads: SetBinderDiscussionCommentReaction200ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
