/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SetBinderRulesBody = {
  blockOnUnresolvedThreads?: boolean;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  requiredApprovals?: number;
  dismissStaleApprovals?: boolean;
};
