/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderDiscussionCommentReactionBodyContent } from './setBinderDiscussionCommentReactionBodyContent.ts';

export type SetBinderDiscussionCommentReactionBody = {
  content: SetBinderDiscussionCommentReactionBodyContent;
  on: boolean;
};
