/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderDiscussionCommentReaction200ThreadsItemCommentsItem } from './setBinderDiscussionCommentReaction200ThreadsItemCommentsItem.ts';
import type { SetBinderDiscussionCommentReaction200ThreadsItemEventsItem } from './setBinderDiscussionCommentReaction200ThreadsItemEventsItem.ts';
import type { SetBinderDiscussionCommentReaction200ThreadsItemOrigin } from './setBinderDiscussionCommentReaction200ThreadsItemOrigin.ts';
import type { SetBinderDiscussionCommentReaction200ThreadsItemResolvedBy } from './setBinderDiscussionCommentReaction200ThreadsItemResolvedBy.ts';

export type SetBinderDiscussionCommentReaction200ThreadsItem = {
  id: string;
  origin: SetBinderDiscussionCommentReaction200ThreadsItemOrigin;
  comments: SetBinderDiscussionCommentReaction200ThreadsItemCommentsItem[];
  events: SetBinderDiscussionCommentReaction200ThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: SetBinderDiscussionCommentReaction200ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
