/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderPersonLevel200GroupsItemMembersItem } from './setBinderPersonLevel200GroupsItemMembersItem.ts';

export type SetBinderPersonLevel200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  members: SetBinderPersonLevel200GroupsItemMembersItem[];
};
