/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderVisibility200GroupsItem } from './setBinderVisibility200GroupsItem.ts';
import type { SetBinderVisibility200OrganizationMembersItem } from './setBinderVisibility200OrganizationMembersItem.ts';
import type { SetBinderVisibility200PeopleItem } from './setBinderVisibility200PeopleItem.ts';

export type SetBinderVisibility200 = {
  organization: string;
  workspace: string;
  people: SetBinderVisibility200PeopleItem[];
  groups: SetBinderVisibility200GroupsItem[];
  openToOrganization: boolean;
  organizationMembers: SetBinderVisibility200OrganizationMembersItem[];
  canManage: boolean;
};
