/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderPersonLevel200GroupsItem } from './setBinderPersonLevel200GroupsItem.ts';
import type { SetBinderPersonLevel200OrganizationMembersItem } from './setBinderPersonLevel200OrganizationMembersItem.ts';
import type { SetBinderPersonLevel200PeopleItem } from './setBinderPersonLevel200PeopleItem.ts';

export type SetBinderPersonLevel200 = {
  organization: string;
  workspace: string;
  people: SetBinderPersonLevel200PeopleItem[];
  groups: SetBinderPersonLevel200GroupsItem[];
  openToOrganization: boolean;
  organizationMembers: SetBinderPersonLevel200OrganizationMembersItem[];
  canManage: boolean;
};
