/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetBinderDiscussionCommentReaction200ThreadsItemEventsItemActor } from './setBinderDiscussionCommentReaction200ThreadsItemEventsItemActor.ts';

export type SetBinderDiscussionCommentReaction200ThreadsItemEventsItem = {
  id: number;
  actor: SetBinderDiscussionCommentReaction200ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
