/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SetDiscussionCommentReaction200ThreadsItemOrigin = typeof SetDiscussionCommentReaction200ThreadsItemOrigin[keyof typeof SetDiscussionCommentReaction200ThreadsItemOrigin];


export const SetDiscussionCommentReaction200ThreadsItemOrigin = {
  bindersnap: 'bindersnap',
  external: 'external',
} as const;
