/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetDiscussionCommentReaction200ThreadsItem } from './setDiscussionCommentReaction200ThreadsItem.ts';

export type SetDiscussionCommentReaction200 = {
  threads: SetDiscussionCommentReaction200ThreadsItem[];
  totalCount: number;
  unresolvedCount: number;
};
