/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemContent } from './setDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemContent.ts';
import type { SetDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemUsersItem } from './setDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemUsersItem.ts';

export type SetDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem = {
  content: SetDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemContent;
  count: number;
  viewerReacted: boolean;
  users: SetDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItemUsersItem[];
};
