/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SetDiscussionCommentReactionBodyContent = typeof SetDiscussionCommentReactionBodyContent[keyof typeof SetDiscussionCommentReactionBodyContent];


export const SetDiscussionCommentReactionBodyContent = {
  '+1': '+1',
  NUMBER_MINUS_1: '-1',
  confused: 'confused',
  eyes: 'eyes',
  heart: 'heart',
} as const;
