/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetDiscussionCommentReaction200ThreadsItemEventsItemActor } from './setDiscussionCommentReaction200ThreadsItemEventsItemActor.ts';

export type SetDiscussionCommentReaction200ThreadsItemEventsItem = {
  id: number;
  actor: SetDiscussionCommentReaction200ThreadsItemEventsItemActor;
  resolved: boolean;
  at: string;
};
