/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetDiscussionCommentReaction200ThreadsItemCommentsItem } from './setDiscussionCommentReaction200ThreadsItemCommentsItem.ts';
import type { SetDiscussionCommentReaction200ThreadsItemEventsItem } from './setDiscussionCommentReaction200ThreadsItemEventsItem.ts';
import type { SetDiscussionCommentReaction200ThreadsItemOrigin } from './setDiscussionCommentReaction200ThreadsItemOrigin.ts';
import type { SetDiscussionCommentReaction200ThreadsItemResolvedBy } from './setDiscussionCommentReaction200ThreadsItemResolvedBy.ts';

export type SetDiscussionCommentReaction200ThreadsItem = {
  id: string;
  origin: SetDiscussionCommentReaction200ThreadsItemOrigin;
  comments: SetDiscussionCommentReaction200ThreadsItemCommentsItem[];
  events: SetDiscussionCommentReaction200ThreadsItemEventsItem[];
  resolved: boolean;
  /** @nullable */
  resolvedBy: SetDiscussionCommentReaction200ThreadsItemResolvedBy;
  /** @nullable */
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
