/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetDiscussionCommentReaction200ThreadsItemCommentsItemAuthor } from './setDiscussionCommentReaction200ThreadsItemCommentsItemAuthor.ts';
import type { SetDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem } from './setDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem.ts';

export type SetDiscussionCommentReaction200ThreadsItemCommentsItem = {
  id: number;
  threadId: string;
  author: SetDiscussionCommentReaction200ThreadsItemCommentsItemAuthor;
  body: string;
  createdAt: string;
  updatedAt: string;
  htmlUrl: string;
  reactions: SetDiscussionCommentReaction200ThreadsItemCommentsItemReactionsItem[];
};
