/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetOrganizationPersonRole200GroupsItemMembersItem } from './setOrganizationPersonRole200GroupsItemMembersItem.ts';

export type SetOrganizationPersonRole200GroupsItem = {
  id: number;
  name: string;
  description: string;
  access: string;
  memberCount: number;
  members: SetOrganizationPersonRole200GroupsItemMembersItem[];
  binders: string[];
};
