/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SetOrganizationPersonRole200GroupsItem } from './setOrganizationPersonRole200GroupsItem.ts';
import type { SetOrganizationPersonRole200PeopleItem } from './setOrganizationPersonRole200PeopleItem.ts';

export type SetOrganizationPersonRole200 = {
  organization: string;
  people: SetOrganizationPersonRole200PeopleItem[];
  groups: SetOrganizationPersonRole200GroupsItem[];
  binders: string[];
  canManage: boolean;
  viewer: string;
};
