/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export interface SignupBody {
  /** @minLength 1 */
  username: string;
  email: string;
  /** @minLength 1 */
  password: string;
}
