/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type SubmitDocumentReviewBodyEvent = typeof SubmitDocumentReviewBodyEvent[keyof typeof SubmitDocumentReviewBodyEvent];


export const SubmitDocumentReviewBodyEvent = {
  APPROVE: 'APPROVE',
  REQUEST_CHANGES: 'REQUEST_CHANGES',
  COMMENT: 'COMMENT',
} as const;
