/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitDocumentReviewBodyEvent } from "./submitDocumentReviewBodyEvent";

export type SubmitDocumentReviewBody = {
  event: SubmitDocumentReviewBodyEvent;
  body?: string;
};
