/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateBinderChangeAssignments200ReviewersItemStatus = typeof UpdateBinderChangeAssignments200ReviewersItemStatus[keyof typeof UpdateBinderChangeAssignments200ReviewersItemStatus];


export const UpdateBinderChangeAssignments200ReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
