/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateChangeAssignments200ReviewersItemStatus = typeof UpdateChangeAssignments200ReviewersItemStatus[keyof typeof UpdateChangeAssignments200ReviewersItemStatus];


export const UpdateChangeAssignments200ReviewersItemStatus = {
  approved: 'approved',
  changes_requested: 'changes_requested',
  commented: 'commented',
  awaiting: 'awaiting',
} as const;
