/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChangeAssignments200Assignee } from './updateChangeAssignments200Assignee.ts';
import type { UpdateChangeAssignments200ReviewersItem } from './updateChangeAssignments200ReviewersItem.ts';

export type UpdateChangeAssignments200 = {
  /** @nullable */
  assignee: UpdateChangeAssignments200Assignee;
  reviewers: UpdateChangeAssignments200ReviewersItem[];
  approvalCount: number;
  requiredApprovals: number;
};
