/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateChangeAssignments200ReviewersItemStatus } from './updateChangeAssignments200ReviewersItemStatus.ts';

export type UpdateChangeAssignments200ReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: UpdateChangeAssignments200ReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
