/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateDocumentPermissions200BranchProtection } from './updateDocumentPermissions200BranchProtection';
import type { UpdateDocumentPermissions200CurrentUserPermission } from './updateDocumentPermissions200CurrentUserPermission';

export type UpdateDocumentPermissions200 = {
  /** @nullable */
  branchProtection: UpdateDocumentPermissions200BranchProtection;
  isPrivate: boolean;
  isInternal: boolean;
  /** @nullable */
  currentUserPermission?: UpdateDocumentPermissions200CurrentUserPermission;
};
