/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateEmailPreferences200Preferences = {
  reviewRequested: boolean;
  changesRequested: boolean;
  readyToPublish: boolean;
  published: boolean;
};
