/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateDocumentPermissions200CurrentUserPermissionAccess } from './updateDocumentPermissions200CurrentUserPermissionAccess.ts';
import type { UpdateDocumentPermissions200CurrentUserPermissionUser } from './updateDocumentPermissions200CurrentUserPermissionUser.ts';

/**
 * @nullable
 */
export type UpdateDocumentPermissions200CurrentUserPermission = {
  permission: string;
  access: UpdateDocumentPermissions200CurrentUserPermissionAccess;
  permissionLabel: string;
  roleName: string;
  user: UpdateDocumentPermissions200CurrentUserPermissionUser;
} | null;
