/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfile200User } from './updateProfile200User.ts';

export type UpdateProfile200 = {
  user: UpdateProfile200User;
};
