/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateBinderChangeAssignments200Assignee } from './updateBinderChangeAssignments200Assignee.ts';
import type { UpdateBinderChangeAssignments200ReviewersItem } from './updateBinderChangeAssignments200ReviewersItem.ts';

export type UpdateBinderChangeAssignments200 = {
  /** @nullable */
  assignee: UpdateBinderChangeAssignments200Assignee;
  reviewers: UpdateBinderChangeAssignments200ReviewersItem[];
  approvalCount: number;
  /** @nullable */
  requiredApprovals: number | null;
};
