/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateBinderChangeAssignments200ReviewersItemStatus } from './updateBinderChangeAssignments200ReviewersItemStatus.ts';

export type UpdateBinderChangeAssignments200ReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: UpdateBinderChangeAssignments200ReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
