/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateDocumentPermissions200CurrentUserPermissionAccess = typeof UpdateDocumentPermissions200CurrentUserPermissionAccess[keyof typeof UpdateDocumentPermissions200CurrentUserPermissionAccess];


export const UpdateDocumentPermissions200CurrentUserPermissionAccess = {
  read: 'read',
  write: 'write',
  admin: 'admin',
} as const;
