/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateEmailPreferences200Preferences } from './updateEmailPreferences200Preferences.ts';

export type UpdateEmailPreferences200 = {
  preferences: UpdateEmailPreferences200Preferences;
};
