/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateDocumentPermissions200BranchProtection } from './updateDocumentPermissions200BranchProtection.ts';
import type { UpdateDocumentPermissions200CurrentUserPermission } from './updateDocumentPermissions200CurrentUserPermission.ts';
import type { UpdateDocumentPermissions200ReviewSettings } from './updateDocumentPermissions200ReviewSettings.ts';

export type UpdateDocumentPermissions200 = {
  /** @nullable */
  branchProtection: UpdateDocumentPermissions200BranchProtection;
  isPrivate: boolean;
  isInternal: boolean;
  /** @nullable */
  currentUserPermission?: UpdateDocumentPermissions200CurrentUserPermission;
  /** @nullable */
  reviewSettings?: UpdateDocumentPermissions200ReviewSettings;
};
