/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */

export type UploadDocumentVersionBody = {
  /** File upload */
  file: Blob;
  docSlug: string;
  uploaderSlug: string;
  nextVersion: string;
  canonicalFileName?: string;
};
