/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceDocumentSummaryLatestTag } from './workspaceDocumentSummaryLatestTag.ts';
import type { WorkspaceDocumentSummaryPendingPRsItem } from './workspaceDocumentSummaryPendingPRsItem.ts';
import type { WorkspaceDocumentSummaryRepo } from './workspaceDocumentSummaryRepo.ts';

export interface WorkspaceDocumentSummary {
  repo: WorkspaceDocumentSummaryRepo;
  /** @nullable */
  latestTag: WorkspaceDocumentSummaryLatestTag;
  pendingPRs: WorkspaceDocumentSummaryPendingPRsItem[];
  /** @nullable */
  error: string | null;
}
