/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceDocumentSummaryPendingPRsItemApprovalState } from './workspaceDocumentSummaryPendingPRsItemApprovalState.ts';
import type { WorkspaceDocumentSummaryPendingPRsItemUser } from './workspaceDocumentSummaryPendingPRsItemUser.ts';

export type WorkspaceDocumentSummaryPendingPRsItem = {
  id: number;
  number: number;
  title: string;
  state: string;
  created: string;
  created_at?: string;
  updated_at?: string;
  branchName: string;
  approvalCount: number;
  requiredApprovals: number;
  isApproved: boolean;
  isRejected: boolean;
  reviewers: string[];
  body?: string;
  approvalState: WorkspaceDocumentSummaryPendingPRsItemApprovalState;
  /** @nullable */
  user?: WorkspaceDocumentSummaryPendingPRsItemUser;
};
