/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceDocumentSummaryPendingPRsItemReviewsItemAuthor } from './workspaceDocumentSummaryPendingPRsItemReviewsItemAuthor.ts';
import type { WorkspaceDocumentSummaryPendingPRsItemReviewsItemState } from './workspaceDocumentSummaryPendingPRsItemReviewsItemState.ts';

export type WorkspaceDocumentSummaryPendingPRsItemReviewsItem = {
  id: number;
  author: WorkspaceDocumentSummaryPendingPRsItemReviewsItemAuthor;
  state: WorkspaceDocumentSummaryPendingPRsItemReviewsItemState;
  body: string;
  submittedAt: string;
  stale: boolean;
  dismissed: boolean;
};
