/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceDocumentSummaryPendingPRsItemReviewersItemStatus } from './workspaceDocumentSummaryPendingPRsItemReviewersItemStatus.ts';

export type WorkspaceDocumentSummaryPendingPRsItemReviewersItem = {
  login: string;
  fullName: string;
  avatarUrl: string;
  status: WorkspaceDocumentSummaryPendingPRsItemReviewersItemStatus;
  reviewedAt: string;
  stale: boolean;
  requested: boolean;
};
