/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspaceDocumentSummaryLatestTag } from "./workspaceDocumentSummaryLatestTag";
import type { WorkspaceDocumentSummaryPendingPRsItem } from "./workspaceDocumentSummaryPendingPRsItem";
import type { WorkspaceDocumentSummaryRepo } from "./workspaceDocumentSummaryRepo";

export interface WorkspaceDocumentSummary {
  repo: WorkspaceDocumentSummaryRepo;
  /** @nullable */
  latestTag: WorkspaceDocumentSummaryLatestTag;
  pendingPRs: WorkspaceDocumentSummaryPendingPRsItem[];
  /** @nullable */
  error: string | null;
}
