/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddDocumentCollaborator200,
  AddDocumentCollaboratorBody,
  CreateDocument200,
  CreateDocumentBody,
  CreateDocumentDiscussion201,
  CreateDocumentDiscussionBody,
  DownloadDocumentParams,
  GetDocumentDetail200,
  GetDocumentHistory200,
  GetDocumentPermissions200,
  ListDocumentCollaborators200,
  ListDocumentCollaboratorsParams,
  ListDocumentDiscussions200,
  ListDocuments200,
  ListDocumentsParams,
  PublishDocument200,
  PublishDocumentBody,
  ReplyToDocumentDiscussion201,
  ReplyToDocumentDiscussionBody,
  ResolveDocumentDiscussion200,
  ResolveDocumentDiscussionBody,
  SubmitDocumentReviewBody,
  UpdateDocumentPermissions200,
  UpdateDocumentPermissionsBody,
  UploadDocumentVersion200,
  UploadDocumentVersionBody
} from '../model';

import { customFetch } from '.././mutator.ts';

export type listDocumentsResponse200 = {
  data: ListDocuments200
  status: 200
}

export type listDocumentsResponseSuccess = (listDocumentsResponse200) & {
  headers: Headers;
};
;

export type listDocumentsResponse = (listDocumentsResponseSuccess)

export const getListDocumentsUrl = (params?: ListDocumentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/app/documents?${stringifiedParams}` : `/api/app/documents`
}

export const listDocuments = async (params?: ListDocumentsParams, options?: Parameters<typeof customFetch>[1]): Promise<listDocumentsResponse> => {

  return customFetch<listDocumentsResponse>(getListDocumentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type createDocumentResponse200 = {
  data: CreateDocument200
  status: 200
}

export type createDocumentResponseSuccess = (createDocumentResponse200) & {
  headers: Headers;
};
;

export type createDocumentResponse = (createDocumentResponseSuccess)

export const getCreateDocumentUrl = () => {




  return `/api/app/documents`
}

export const createDocument = async (createDocumentBody: CreateDocumentBody, options?: Parameters<typeof customFetch>[1]): Promise<createDocumentResponse> => {
    const formData = new FormData();
formData.append(`file`, createDocumentBody.file);
formData.append(`repoName`, createDocumentBody.repoName);
formData.append(`nextVersion`, createDocumentBody.nextVersion);
if(createDocumentBody.requiredApprovals !== undefined) {
 formData.append(`requiredApprovals`, createDocumentBody.requiredApprovals);
 }
if(createDocumentBody.description !== undefined) {
 formData.append(`description`, createDocumentBody.description);
 }

  return customFetch<createDocumentResponse>(getCreateDocumentUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}


export type getDocumentDetailResponse200 = {
  data: GetDocumentDetail200
  status: 200
}

export type getDocumentDetailResponseSuccess = (getDocumentDetailResponse200) & {
  headers: Headers;
};
;

export type getDocumentDetailResponse = (getDocumentDetailResponseSuccess)

export const getGetDocumentDetailUrl = (owner: string,
    repo: string,) => {




  return `/api/app/documents/${owner}/${repo}`
}

export const getDocumentDetail = async (owner: string,
    repo: string, options?: Parameters<typeof customFetch>[1]): Promise<getDocumentDetailResponse> => {

  return customFetch<getDocumentDetailResponse>(getGetDocumentDetailUrl(owner,repo),
  {
    ...options,
    method: 'GET'


  }
);}


export type getDocumentHistoryResponse200 = {
  data: GetDocumentHistory200
  status: 200
}

export type getDocumentHistoryResponseSuccess = (getDocumentHistoryResponse200) & {
  headers: Headers;
};
;

export type getDocumentHistoryResponse = (getDocumentHistoryResponseSuccess)

export const getGetDocumentHistoryUrl = (owner: string,
    repo: string,) => {




  return `/api/app/documents/${owner}/${repo}/history`
}

export const getDocumentHistory = async (owner: string,
    repo: string, options?: Parameters<typeof customFetch>[1]): Promise<getDocumentHistoryResponse> => {

  return customFetch<getDocumentHistoryResponse>(getGetDocumentHistoryUrl(owner,repo),
  {
    ...options,
    method: 'GET'


  }
);}


export type uploadDocumentVersionResponse200 = {
  data: UploadDocumentVersion200
  status: 200
}

export type uploadDocumentVersionResponseSuccess = (uploadDocumentVersionResponse200) & {
  headers: Headers;
};
;

export type uploadDocumentVersionResponse = (uploadDocumentVersionResponseSuccess)

export const getUploadDocumentVersionUrl = (owner: string,
    repo: string,) => {




  return `/api/app/documents/${owner}/${repo}/versions`
}

export const uploadDocumentVersion = async (owner: string,
    repo: string,
    uploadDocumentVersionBody: UploadDocumentVersionBody, options?: Parameters<typeof customFetch>[1]): Promise<uploadDocumentVersionResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadDocumentVersionBody.file);
formData.append(`docSlug`, uploadDocumentVersionBody.docSlug);
formData.append(`uploaderSlug`, uploadDocumentVersionBody.uploaderSlug);
formData.append(`nextVersion`, uploadDocumentVersionBody.nextVersion);
if(uploadDocumentVersionBody.canonicalFileName !== undefined) {
 formData.append(`canonicalFileName`, uploadDocumentVersionBody.canonicalFileName);
 }

  return customFetch<uploadDocumentVersionResponse>(getUploadDocumentVersionUrl(owner,repo),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}


export type downloadDocumentResponse200 = {
  data: Blob
  status: 200
}

export type downloadDocumentResponseSuccess = (downloadDocumentResponse200) & {
  headers: Headers;
};
;

export type downloadDocumentResponse = (downloadDocumentResponseSuccess)

export const getDownloadDocumentUrl = (owner: string,
    repo: string,
    params?: DownloadDocumentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/app/documents/${owner}/${repo}/download?${stringifiedParams}` : `/api/app/documents/${owner}/${repo}/download`
}

export const downloadDocument = async (owner: string,
    repo: string,
    params?: DownloadDocumentParams, options?: Parameters<typeof customFetch>[1]): Promise<downloadDocumentResponse> => {

  return customFetch<downloadDocumentResponse>(getDownloadDocumentUrl(owner,repo,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type getDocumentPermissionsResponse200 = {
  data: GetDocumentPermissions200
  status: 200
}

export type getDocumentPermissionsResponseSuccess = (getDocumentPermissionsResponse200) & {
  headers: Headers;
};
;

export type getDocumentPermissionsResponse = (getDocumentPermissionsResponseSuccess)

export const getGetDocumentPermissionsUrl = (owner: string,
    repo: string,) => {




  return `/api/app/documents/${owner}/${repo}/permissions`
}

export const getDocumentPermissions = async (owner: string,
    repo: string, options?: Parameters<typeof customFetch>[1]): Promise<getDocumentPermissionsResponse> => {

  return customFetch<getDocumentPermissionsResponse>(getGetDocumentPermissionsUrl(owner,repo),
  {
    ...options,
    method: 'GET'


  }
);}


export type updateDocumentPermissionsResponse200 = {
  data: UpdateDocumentPermissions200
  status: 200
}

export type updateDocumentPermissionsResponseSuccess = (updateDocumentPermissionsResponse200) & {
  headers: Headers;
};
;

export type updateDocumentPermissionsResponse = (updateDocumentPermissionsResponseSuccess)

export const getUpdateDocumentPermissionsUrl = (owner: string,
    repo: string,) => {




  return `/api/app/documents/${owner}/${repo}/permissions`
}

export const updateDocumentPermissions = async (owner: string,
    repo: string,
    updateDocumentPermissionsBody: UpdateDocumentPermissionsBody, options?: Parameters<typeof customFetch>[1]): Promise<updateDocumentPermissionsResponse> => {

  return customFetch<updateDocumentPermissionsResponse>(getUpdateDocumentPermissionsUrl(owner,repo),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDocumentPermissionsBody)
  }
);}


export type listDocumentCollaboratorsResponse200 = {
  data: ListDocumentCollaborators200
  status: 200
}

export type listDocumentCollaboratorsResponseSuccess = (listDocumentCollaboratorsResponse200) & {
  headers: Headers;
};
;

export type listDocumentCollaboratorsResponse = (listDocumentCollaboratorsResponseSuccess)

export const getListDocumentCollaboratorsUrl = (owner: string,
    repo: string,
    params?: ListDocumentCollaboratorsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/app/documents/${owner}/${repo}/collaborators?${stringifiedParams}` : `/api/app/documents/${owner}/${repo}/collaborators`
}

export const listDocumentCollaborators = async (owner: string,
    repo: string,
    params?: ListDocumentCollaboratorsParams, options?: Parameters<typeof customFetch>[1]): Promise<listDocumentCollaboratorsResponse> => {

  return customFetch<listDocumentCollaboratorsResponse>(getListDocumentCollaboratorsUrl(owner,repo,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type addDocumentCollaboratorResponse200 = {
  data: AddDocumentCollaborator200
  status: 200
}

export type addDocumentCollaboratorResponseSuccess = (addDocumentCollaboratorResponse200) & {
  headers: Headers;
};
;

export type addDocumentCollaboratorResponse = (addDocumentCollaboratorResponseSuccess)

export const getAddDocumentCollaboratorUrl = (owner: string,
    repo: string,
    collaborator: string,) => {




  return `/api/app/documents/${owner}/${repo}/collaborators/${collaborator}`
}

export const addDocumentCollaborator = async (owner: string,
    repo: string,
    collaborator: string,
    addDocumentCollaboratorBody: AddDocumentCollaboratorBody, options?: Parameters<typeof customFetch>[1]): Promise<addDocumentCollaboratorResponse> => {

  return customFetch<addDocumentCollaboratorResponse>(getAddDocumentCollaboratorUrl(owner,repo,collaborator),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addDocumentCollaboratorBody)
  }
);}


export type removeDocumentCollaboratorResponse204 = {
  data: void
  status: 204
}

export type removeDocumentCollaboratorResponseSuccess = (removeDocumentCollaboratorResponse204) & {
  headers: Headers;
};
;

export type removeDocumentCollaboratorResponse = (removeDocumentCollaboratorResponseSuccess)

export const getRemoveDocumentCollaboratorUrl = (owner: string,
    repo: string,
    collaborator: string,) => {




  return `/api/app/documents/${owner}/${repo}/collaborators/${collaborator}`
}

export const removeDocumentCollaborator = async (owner: string,
    repo: string,
    collaborator: string, options?: Parameters<typeof customFetch>[1]): Promise<removeDocumentCollaboratorResponse> => {

  return customFetch<removeDocumentCollaboratorResponse>(getRemoveDocumentCollaboratorUrl(owner,repo,collaborator),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type submitDocumentReviewResponse204 = {
  data: void
  status: 204
}

export type submitDocumentReviewResponseSuccess = (submitDocumentReviewResponse204) & {
  headers: Headers;
};
;

export type submitDocumentReviewResponse = (submitDocumentReviewResponseSuccess)

export const getSubmitDocumentReviewUrl = (owner: string,
    repo: string,
    pullNumber: string,) => {




  return `/api/app/documents/${owner}/${repo}/pull-requests/${pullNumber}/reviews`
}

export const submitDocumentReview = async (owner: string,
    repo: string,
    pullNumber: string,
    submitDocumentReviewBody: SubmitDocumentReviewBody, options?: Parameters<typeof customFetch>[1]): Promise<submitDocumentReviewResponse> => {

  return customFetch<submitDocumentReviewResponse>(getSubmitDocumentReviewUrl(owner,repo,pullNumber),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitDocumentReviewBody)
  }
);}


export type listDocumentDiscussionsResponse200 = {
  data: ListDocumentDiscussions200
  status: 200
}

export type listDocumentDiscussionsResponseSuccess = (listDocumentDiscussionsResponse200) & {
  headers: Headers;
};
;

export type listDocumentDiscussionsResponse = (listDocumentDiscussionsResponseSuccess)

export const getListDocumentDiscussionsUrl = (owner: string,
    repo: string,
    pullNumber: string,) => {




  return `/api/app/documents/${owner}/${repo}/pull-requests/${pullNumber}/discussions`
}

export const listDocumentDiscussions = async (owner: string,
    repo: string,
    pullNumber: string, options?: Parameters<typeof customFetch>[1]): Promise<listDocumentDiscussionsResponse> => {

  return customFetch<listDocumentDiscussionsResponse>(getListDocumentDiscussionsUrl(owner,repo,pullNumber),
  {
    ...options,
    method: 'GET'


  }
);}


export type createDocumentDiscussionResponse201 = {
  data: CreateDocumentDiscussion201
  status: 201
}

export type createDocumentDiscussionResponseSuccess = (createDocumentDiscussionResponse201) & {
  headers: Headers;
};
;

export type createDocumentDiscussionResponse = (createDocumentDiscussionResponseSuccess)

export const getCreateDocumentDiscussionUrl = (owner: string,
    repo: string,
    pullNumber: string,) => {




  return `/api/app/documents/${owner}/${repo}/pull-requests/${pullNumber}/discussions`
}

export const createDocumentDiscussion = async (owner: string,
    repo: string,
    pullNumber: string,
    createDocumentDiscussionBody: CreateDocumentDiscussionBody, options?: Parameters<typeof customFetch>[1]): Promise<createDocumentDiscussionResponse> => {

  return customFetch<createDocumentDiscussionResponse>(getCreateDocumentDiscussionUrl(owner,repo,pullNumber),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDocumentDiscussionBody)
  }
);}


export type replyToDocumentDiscussionResponse201 = {
  data: ReplyToDocumentDiscussion201
  status: 201
}

export type replyToDocumentDiscussionResponseSuccess = (replyToDocumentDiscussionResponse201) & {
  headers: Headers;
};
;

export type replyToDocumentDiscussionResponse = (replyToDocumentDiscussionResponseSuccess)

export const getReplyToDocumentDiscussionUrl = (owner: string,
    repo: string,
    pullNumber: string,
    threadId: string,) => {




  return `/api/app/documents/${owner}/${repo}/pull-requests/${pullNumber}/discussions/${threadId}/comments`
}

export const replyToDocumentDiscussion = async (owner: string,
    repo: string,
    pullNumber: string,
    threadId: string,
    replyToDocumentDiscussionBody: ReplyToDocumentDiscussionBody, options?: Parameters<typeof customFetch>[1]): Promise<replyToDocumentDiscussionResponse> => {

  return customFetch<replyToDocumentDiscussionResponse>(getReplyToDocumentDiscussionUrl(owner,repo,pullNumber,threadId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(replyToDocumentDiscussionBody)
  }
);}


export type resolveDocumentDiscussionResponse200 = {
  data: ResolveDocumentDiscussion200
  status: 200
}

export type resolveDocumentDiscussionResponseSuccess = (resolveDocumentDiscussionResponse200) & {
  headers: Headers;
};
;

export type resolveDocumentDiscussionResponse = (resolveDocumentDiscussionResponseSuccess)

export const getResolveDocumentDiscussionUrl = (owner: string,
    repo: string,
    pullNumber: string,
    threadId: string,) => {




  return `/api/app/documents/${owner}/${repo}/pull-requests/${pullNumber}/discussions/${threadId}/resolve`
}

export const resolveDocumentDiscussion = async (owner: string,
    repo: string,
    pullNumber: string,
    threadId: string,
    resolveDocumentDiscussionBody: ResolveDocumentDiscussionBody, options?: Parameters<typeof customFetch>[1]): Promise<resolveDocumentDiscussionResponse> => {

  return customFetch<resolveDocumentDiscussionResponse>(getResolveDocumentDiscussionUrl(owner,repo,pullNumber,threadId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resolveDocumentDiscussionBody)
  }
);}


export type publishDocumentResponse200 = {
  data: PublishDocument200
  status: 200
}

export type publishDocumentResponseSuccess = (publishDocumentResponse200) & {
  headers: Headers;
};
;

export type publishDocumentResponse = (publishDocumentResponseSuccess)

export const getPublishDocumentUrl = (owner: string,
    repo: string,
    pullNumber: string,) => {




  return `/api/app/documents/${owner}/${repo}/pull-requests/${pullNumber}/publish`
}

export const publishDocument = async (owner: string,
    repo: string,
    pullNumber: string,
    publishDocumentBody: PublishDocumentBody, options?: Parameters<typeof customFetch>[1]): Promise<publishDocumentResponse> => {

  return customFetch<publishDocumentResponse>(getPublishDocumentUrl(owner,repo,pullNumber),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(publishDocumentBody)
  }
);}


