/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetHomeChanges200,
  ListDocuments200,
  ListDocumentsParams,
  SearchDocuments200,
  SearchDocumentsParams
} from '../model';

import { customFetch } from '.././mutator.ts';

export type listDocumentsResponse200 = {
  data: ListDocuments200
  status: 200
}

export type listDocumentsResponseSuccess = (listDocumentsResponse200) & {
  headers: Headers;
};
;

export type listDocumentsResponse = (listDocumentsResponseSuccess)

export const getListDocumentsUrl = (params?: ListDocumentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/app/documents?${stringifiedParams}` : `/api/app/documents`
}

export const listDocuments = async (params?: ListDocumentsParams, options?: Parameters<typeof customFetch>[1]): Promise<listDocumentsResponse> => {

  return customFetch<listDocumentsResponse>(getListDocumentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type getHomeChangesResponse200 = {
  data: GetHomeChanges200
  status: 200
}

export type getHomeChangesResponseSuccess = (getHomeChangesResponse200) & {
  headers: Headers;
};
;

export type getHomeChangesResponse = (getHomeChangesResponseSuccess)

export const getGetHomeChangesUrl = () => {




  return `/api/app/home/changes`
}

export const getHomeChanges = async ( options?: Parameters<typeof customFetch>[1]): Promise<getHomeChangesResponse> => {

  return customFetch<getHomeChangesResponse>(getGetHomeChangesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type searchDocumentsResponse200 = {
  data: SearchDocuments200
  status: 200
}

export type searchDocumentsResponseSuccess = (searchDocumentsResponse200) & {
  headers: Headers;
};
;

export type searchDocumentsResponse = (searchDocumentsResponseSuccess)

export const getSearchDocumentsUrl = (params: SearchDocumentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/app/documents/search?${stringifiedParams}` : `/api/app/documents/search`
}

export const searchDocuments = async (params: SearchDocumentsParams, options?: Parameters<typeof customFetch>[1]): Promise<searchDocumentsResponse> => {

  return customFetch<searchDocumentsResponse>(getSearchDocumentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


