/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CountNotifications200,
  ListNotifications200,
  ListNotificationsParams,
  ReadNotifications200,
  ReadNotificationsBody
} from '../model';

import { customFetch } from '.././mutator.ts';

export type listNotificationsResponse200 = {
  data: ListNotifications200
  status: 200
}

export type listNotificationsResponseSuccess = (listNotificationsResponse200) & {
  headers: Headers;
};
;

export type listNotificationsResponse = (listNotificationsResponseSuccess)

export const getListNotificationsUrl = (params?: ListNotificationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/app/notifications?${stringifiedParams}` : `/api/app/notifications`
}

export const listNotifications = async (params?: ListNotificationsParams, options?: Parameters<typeof customFetch>[1]): Promise<listNotificationsResponse> => {

  return customFetch<listNotificationsResponse>(getListNotificationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type countNotificationsResponse200 = {
  data: CountNotifications200
  status: 200
}

export type countNotificationsResponseSuccess = (countNotificationsResponse200) & {
  headers: Headers;
};
;

export type countNotificationsResponse = (countNotificationsResponseSuccess)

export const getCountNotificationsUrl = () => {




  return `/api/app/notifications/count`
}

export const countNotifications = async ( options?: Parameters<typeof customFetch>[1]): Promise<countNotificationsResponse> => {

  return customFetch<countNotificationsResponse>(getCountNotificationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type readNotificationsResponse200 = {
  data: ReadNotifications200
  status: 200
}

export type readNotificationsResponseSuccess = (readNotificationsResponse200) & {
  headers: Headers;
};
;

export type readNotificationsResponse = (readNotificationsResponseSuccess)

export const getReadNotificationsUrl = () => {




  return `/api/app/notifications/read`
}

export const readNotifications = async (readNotificationsBody?: ReadNotificationsBody, options?: Parameters<typeof customFetch>[1]): Promise<readNotificationsResponse> => {

  return customFetch<readNotificationsResponse>(getReadNotificationsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(readNotificationsBody)
  }
);}


