/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ListAdminSubscriptionAccess200,
  ListAdminSubscriptionAccessParams,
  SetAdminSubscriptionAccess200,
  SetAdminSubscriptionAccessBody
} from '../model';

import { customFetch } from '.././mutator';

export type listAdminSubscriptionAccessResponse200 = {
  data: ListAdminSubscriptionAccess200
  status: 200
}

export type listAdminSubscriptionAccessResponseSuccess = (listAdminSubscriptionAccessResponse200) & {
  headers: Headers;
};
;

export type listAdminSubscriptionAccessResponse = (listAdminSubscriptionAccessResponseSuccess)

export const getListAdminSubscriptionAccessUrl = (params?: ListAdminSubscriptionAccessParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/app/admin/subscriptions/access?${stringifiedParams}` : `/api/app/admin/subscriptions/access`
}

export const listAdminSubscriptionAccess = async (params?: ListAdminSubscriptionAccessParams, options?: RequestInit): Promise<listAdminSubscriptionAccessResponse> => {

  return customFetch<listAdminSubscriptionAccessResponse>(getListAdminSubscriptionAccessUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type setAdminSubscriptionAccessResponse200 = {
  data: SetAdminSubscriptionAccess200
  status: 200
}

export type setAdminSubscriptionAccessResponseSuccess = (setAdminSubscriptionAccessResponse200) & {
  headers: Headers;
};
;

export type setAdminSubscriptionAccessResponse = (setAdminSubscriptionAccessResponseSuccess)

export const getSetAdminSubscriptionAccessUrl = (username: string,) => {




  return `/api/app/admin/subscriptions/access/${username}`
}

export const setAdminSubscriptionAccess = async (username: string,
    setAdminSubscriptionAccessBody: SetAdminSubscriptionAccessBody, options?: RequestInit): Promise<setAdminSubscriptionAccessResponse> => {

  return customFetch<setAdminSubscriptionAccessResponse>(getSetAdminSubscriptionAccessUrl(username),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setAdminSubscriptionAccessBody,)
  }
);}


export type clearAdminSubscriptionAccessResponse204 = {
  data: void
  status: 204
}

export type clearAdminSubscriptionAccessResponseSuccess = (clearAdminSubscriptionAccessResponse204) & {
  headers: Headers;
};
;

export type clearAdminSubscriptionAccessResponse = (clearAdminSubscriptionAccessResponseSuccess)

export const getClearAdminSubscriptionAccessUrl = (username: string,) => {




  return `/api/app/admin/subscriptions/access/${username}`
}

export const clearAdminSubscriptionAccess = async (username: string, options?: RequestInit): Promise<clearAdminSubscriptionAccessResponse> => {

  return customFetch<clearAdminSubscriptionAccessResponse>(getClearAdminSubscriptionAccessUrl(username),
  {
    ...options,
    method: 'DELETE'


  }
);}


