/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AcceptLegal200,
  AcceptLegalBody,
  GetLegalStatus200
} from '../model';

import { customFetch } from '.././mutator.ts';

export type getLegalStatusResponse200 = {
  data: GetLegalStatus200
  status: 200
}

export type getLegalStatusResponseSuccess = (getLegalStatusResponse200) & {
  headers: Headers;
};
;

export type getLegalStatusResponse = (getLegalStatusResponseSuccess)

export const getGetLegalStatusUrl = () => {




  return `/api/app/legal`
}

export const getLegalStatus = async ( options?: Parameters<typeof customFetch>[1]): Promise<getLegalStatusResponse> => {

  return customFetch<getLegalStatusResponse>(getGetLegalStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type acceptLegalResponse200 = {
  data: AcceptLegal200
  status: 200
}

export type acceptLegalResponseSuccess = (acceptLegalResponse200) & {
  headers: Headers;
};
;

export type acceptLegalResponse = (acceptLegalResponseSuccess)

export const getAcceptLegalUrl = () => {




  return `/api/app/legal/accept`
}

export const acceptLegal = async (acceptLegalBody: AcceptLegalBody, options?: Parameters<typeof customFetch>[1]): Promise<acceptLegalResponse> => {

  return customFetch<acceptLegalResponse>(getAcceptLegalUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(acceptLegalBody)
  }
);}


