/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AcceptInvitation200,
  AddOrganizationGroupMember200,
  AddOrganizationGroupMemberBody,
  AddOrganizationPerson200,
  AddOrganizationPersonBody,
  CreateOrganization201,
  CreateOrganizationBody,
  CreateOrganizationGroup201,
  CreateOrganizationGroupBody,
  CreateOrganizationInvitation200,
  CreateOrganizationInvitation201,
  CreateOrganizationInvitationBody,
  DeleteOrganizationBody,
  GetInvitation200,
  GetOrganizationDeletion200,
  GetOrganizationPeople200,
  ListOrganizationInvitations200,
  ListOrganizations200,
  RemoveOrganizationGroupMember200,
  RemoveOrganizationPerson200,
  ResendOrganizationInvitation200,
  SetOrganizationPersonRole200,
  SetOrganizationPersonRoleBody
} from '../model';

import { customFetch } from '.././mutator.ts';

export type getOrganizationDeletionResponse200 = {
  data: GetOrganizationDeletion200
  status: 200
}

export type getOrganizationDeletionResponseSuccess = (getOrganizationDeletionResponse200) & {
  headers: Headers;
};
;

export type getOrganizationDeletionResponse = (getOrganizationDeletionResponseSuccess)

export const getGetOrganizationDeletionUrl = (org: string,) => {




  return `/api/app/orgs/${org}/deletion`
}

export const getOrganizationDeletion = async (org: string, options?: Parameters<typeof customFetch>[1]): Promise<getOrganizationDeletionResponse> => {

  return customFetch<getOrganizationDeletionResponse>(getGetOrganizationDeletionUrl(org),
  {
    ...options,
    method: 'GET'


  }
);}


export type deleteOrganizationResponse204 = {
  data: void
  status: 204
}

export type deleteOrganizationResponse403 = {
  data: void
  status: 403
}

export type deleteOrganizationResponse409 = {
  data: void
  status: 409
}

export type deleteOrganizationResponseSuccess = (deleteOrganizationResponse204) & {
  headers: Headers;
};
export type deleteOrganizationResponseError = (deleteOrganizationResponse403 | deleteOrganizationResponse409) & {
  headers: Headers;
};

export type deleteOrganizationResponse = (deleteOrganizationResponseSuccess | deleteOrganizationResponseError)

export const getDeleteOrganizationUrl = (org: string,) => {




  return `/api/app/orgs/${org}`
}

export const deleteOrganization = async (org: string,
    deleteOrganizationBody: DeleteOrganizationBody, options?: Parameters<typeof customFetch>[1]): Promise<deleteOrganizationResponse> => {

  return customFetch<deleteOrganizationResponse>(getDeleteOrganizationUrl(org),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deleteOrganizationBody)
  }
);}


export type listOrganizationsResponse200 = {
  data: ListOrganizations200
  status: 200
}

export type listOrganizationsResponseSuccess = (listOrganizationsResponse200) & {
  headers: Headers;
};
;

export type listOrganizationsResponse = (listOrganizationsResponseSuccess)

export const getListOrganizationsUrl = () => {




  return `/api/app/organizations`
}

export const listOrganizations = async ( options?: Parameters<typeof customFetch>[1]): Promise<listOrganizationsResponse> => {

  return customFetch<listOrganizationsResponse>(getListOrganizationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type createOrganizationResponse201 = {
  data: CreateOrganization201
  status: 201
}

export type createOrganizationResponseSuccess = (createOrganizationResponse201) & {
  headers: Headers;
};
;

export type createOrganizationResponse = (createOrganizationResponseSuccess)

export const getCreateOrganizationUrl = () => {




  return `/api/app/organizations`
}

export const createOrganization = async (createOrganizationBody: CreateOrganizationBody, options?: Parameters<typeof customFetch>[1]): Promise<createOrganizationResponse> => {

  return customFetch<createOrganizationResponse>(getCreateOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationBody)
  }
);}


export type getOrganizationPeopleResponse200 = {
  data: GetOrganizationPeople200
  status: 200
}

export type getOrganizationPeopleResponseSuccess = (getOrganizationPeopleResponse200) & {
  headers: Headers;
};
;

export type getOrganizationPeopleResponse = (getOrganizationPeopleResponseSuccess)

export const getGetOrganizationPeopleUrl = (org: string,) => {




  return `/api/app/orgs/${org}/people`
}

export const getOrganizationPeople = async (org: string, options?: Parameters<typeof customFetch>[1]): Promise<getOrganizationPeopleResponse> => {

  return customFetch<getOrganizationPeopleResponse>(getGetOrganizationPeopleUrl(org),
  {
    ...options,
    method: 'GET'


  }
);}


export type addOrganizationPersonResponse200 = {
  data: AddOrganizationPerson200
  status: 200
}

export type addOrganizationPersonResponseSuccess = (addOrganizationPersonResponse200) & {
  headers: Headers;
};
;

export type addOrganizationPersonResponse = (addOrganizationPersonResponseSuccess)

export const getAddOrganizationPersonUrl = (org: string,) => {




  return `/api/app/orgs/${org}/people`
}

export const addOrganizationPerson = async (org: string,
    addOrganizationPersonBody: AddOrganizationPersonBody, options?: Parameters<typeof customFetch>[1]): Promise<addOrganizationPersonResponse> => {

  return customFetch<addOrganizationPersonResponse>(getAddOrganizationPersonUrl(org),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addOrganizationPersonBody)
  }
);}


export type listOrganizationInvitationsResponse200 = {
  data: ListOrganizationInvitations200
  status: 200
}

export type listOrganizationInvitationsResponseSuccess = (listOrganizationInvitationsResponse200) & {
  headers: Headers;
};
;

export type listOrganizationInvitationsResponse = (listOrganizationInvitationsResponseSuccess)

export const getListOrganizationInvitationsUrl = (org: string,) => {




  return `/api/app/orgs/${org}/invitations`
}

export const listOrganizationInvitations = async (org: string, options?: Parameters<typeof customFetch>[1]): Promise<listOrganizationInvitationsResponse> => {

  return customFetch<listOrganizationInvitationsResponse>(getListOrganizationInvitationsUrl(org),
  {
    ...options,
    method: 'GET'


  }
);}


export type createOrganizationInvitationResponse200 = {
  data: CreateOrganizationInvitation200
  status: 200
}

export type createOrganizationInvitationResponse201 = {
  data: CreateOrganizationInvitation201
  status: 201
}

export type createOrganizationInvitationResponseSuccess = (createOrganizationInvitationResponse200 | createOrganizationInvitationResponse201) & {
  headers: Headers;
};
;

export type createOrganizationInvitationResponse = (createOrganizationInvitationResponseSuccess)

export const getCreateOrganizationInvitationUrl = (org: string,) => {




  return `/api/app/orgs/${org}/invitations`
}

export const createOrganizationInvitation = async (org: string,
    createOrganizationInvitationBody: CreateOrganizationInvitationBody, options?: Parameters<typeof customFetch>[1]): Promise<createOrganizationInvitationResponse> => {

  return customFetch<createOrganizationInvitationResponse>(getCreateOrganizationInvitationUrl(org),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationInvitationBody)
  }
);}


export type revokeOrganizationInvitationResponse204 = {
  data: void
  status: 204
}

export type revokeOrganizationInvitationResponseSuccess = (revokeOrganizationInvitationResponse204) & {
  headers: Headers;
};
;

export type revokeOrganizationInvitationResponse = (revokeOrganizationInvitationResponseSuccess)

export const getRevokeOrganizationInvitationUrl = (org: string,
    id: string,) => {




  return `/api/app/orgs/${org}/invitations/${id}`
}

export const revokeOrganizationInvitation = async (org: string,
    id: string, options?: Parameters<typeof customFetch>[1]): Promise<revokeOrganizationInvitationResponse> => {

  return customFetch<revokeOrganizationInvitationResponse>(getRevokeOrganizationInvitationUrl(org,id),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type resendOrganizationInvitationResponse200 = {
  data: ResendOrganizationInvitation200
  status: 200
}

export type resendOrganizationInvitationResponseSuccess = (resendOrganizationInvitationResponse200) & {
  headers: Headers;
};
;

export type resendOrganizationInvitationResponse = (resendOrganizationInvitationResponseSuccess)

export const getResendOrganizationInvitationUrl = (org: string,
    id: string,) => {




  return `/api/app/orgs/${org}/invitations/${id}/resend`
}

export const resendOrganizationInvitation = async (org: string,
    id: string, options?: Parameters<typeof customFetch>[1]): Promise<resendOrganizationInvitationResponse> => {

  return customFetch<resendOrganizationInvitationResponse>(getResendOrganizationInvitationUrl(org,id),
  {
    ...options,
    method: 'POST'


  }
);}


export type getInvitationResponse200 = {
  data: GetInvitation200
  status: 200
}

export type getInvitationResponseSuccess = (getInvitationResponse200) & {
  headers: Headers;
};
;

export type getInvitationResponse = (getInvitationResponseSuccess)

export const getGetInvitationUrl = (token: string,) => {




  return `/api/app/invitations/${token}`
}

export const getInvitation = async (token: string, options?: Parameters<typeof customFetch>[1]): Promise<getInvitationResponse> => {

  return customFetch<getInvitationResponse>(getGetInvitationUrl(token),
  {
    ...options,
    method: 'GET'


  }
);}


export type acceptInvitationResponse200 = {
  data: AcceptInvitation200
  status: 200
}

export type acceptInvitationResponseSuccess = (acceptInvitationResponse200) & {
  headers: Headers;
};
;

export type acceptInvitationResponse = (acceptInvitationResponseSuccess)

export const getAcceptInvitationUrl = (token: string,) => {




  return `/api/app/invitations/${token}/accept`
}

export const acceptInvitation = async (token: string, options?: Parameters<typeof customFetch>[1]): Promise<acceptInvitationResponse> => {

  return customFetch<acceptInvitationResponse>(getAcceptInvitationUrl(token),
  {
    ...options,
    method: 'POST'


  }
);}


export type setOrganizationPersonRoleResponse200 = {
  data: SetOrganizationPersonRole200
  status: 200
}

export type setOrganizationPersonRoleResponseSuccess = (setOrganizationPersonRoleResponse200) & {
  headers: Headers;
};
;

export type setOrganizationPersonRoleResponse = (setOrganizationPersonRoleResponseSuccess)

export const getSetOrganizationPersonRoleUrl = (org: string,
    username: string,) => {




  return `/api/app/orgs/${org}/people/${username}/role`
}

export const setOrganizationPersonRole = async (org: string,
    username: string,
    setOrganizationPersonRoleBody: SetOrganizationPersonRoleBody, options?: Parameters<typeof customFetch>[1]): Promise<setOrganizationPersonRoleResponse> => {

  return customFetch<setOrganizationPersonRoleResponse>(getSetOrganizationPersonRoleUrl(org,username),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setOrganizationPersonRoleBody)
  }
);}


export type removeOrganizationPersonResponse200 = {
  data: RemoveOrganizationPerson200
  status: 200
}

export type removeOrganizationPersonResponseSuccess = (removeOrganizationPersonResponse200) & {
  headers: Headers;
};
;

export type removeOrganizationPersonResponse = (removeOrganizationPersonResponseSuccess)

export const getRemoveOrganizationPersonUrl = (org: string,
    username: string,) => {




  return `/api/app/orgs/${org}/people/${username}`
}

export const removeOrganizationPerson = async (org: string,
    username: string, options?: Parameters<typeof customFetch>[1]): Promise<removeOrganizationPersonResponse> => {

  return customFetch<removeOrganizationPersonResponse>(getRemoveOrganizationPersonUrl(org,username),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type createOrganizationGroupResponse201 = {
  data: CreateOrganizationGroup201
  status: 201
}

export type createOrganizationGroupResponseSuccess = (createOrganizationGroupResponse201) & {
  headers: Headers;
};
;

export type createOrganizationGroupResponse = (createOrganizationGroupResponseSuccess)

export const getCreateOrganizationGroupUrl = (org: string,) => {




  return `/api/app/orgs/${org}/groups`
}

export const createOrganizationGroup = async (org: string,
    createOrganizationGroupBody: CreateOrganizationGroupBody, options?: Parameters<typeof customFetch>[1]): Promise<createOrganizationGroupResponse> => {

  return customFetch<createOrganizationGroupResponse>(getCreateOrganizationGroupUrl(org),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationGroupBody)
  }
);}


export type addOrganizationGroupMemberResponse200 = {
  data: AddOrganizationGroupMember200
  status: 200
}

export type addOrganizationGroupMemberResponseSuccess = (addOrganizationGroupMemberResponse200) & {
  headers: Headers;
};
;

export type addOrganizationGroupMemberResponse = (addOrganizationGroupMemberResponseSuccess)

export const getAddOrganizationGroupMemberUrl = (org: string,
    group: string,) => {




  return `/api/app/orgs/${org}/groups/${group}/members`
}

export const addOrganizationGroupMember = async (org: string,
    group: string,
    addOrganizationGroupMemberBody: AddOrganizationGroupMemberBody, options?: Parameters<typeof customFetch>[1]): Promise<addOrganizationGroupMemberResponse> => {

  return customFetch<addOrganizationGroupMemberResponse>(getAddOrganizationGroupMemberUrl(org,group),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addOrganizationGroupMemberBody)
  }
);}


export type removeOrganizationGroupMemberResponse200 = {
  data: RemoveOrganizationGroupMember200
  status: 200
}

export type removeOrganizationGroupMemberResponseSuccess = (removeOrganizationGroupMemberResponse200) & {
  headers: Headers;
};
;

export type removeOrganizationGroupMemberResponse = (removeOrganizationGroupMemberResponseSuccess)

export const getRemoveOrganizationGroupMemberUrl = (org: string,
    group: string,
    username: string,) => {




  return `/api/app/orgs/${org}/groups/${group}/members/${username}`
}

export const removeOrganizationGroupMember = async (org: string,
    group: string,
    username: string, options?: Parameters<typeof customFetch>[1]): Promise<removeOrganizationGroupMemberResponse> => {

  return customFetch<removeOrganizationGroupMemberResponse>(getRemoveOrganizationGroupMemberUrl(org,group,username),
  {
    ...options,
    method: 'DELETE'


  }
);}


