/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Bindersnap BFF API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddOrganizationGroupMember200,
  AddOrganizationGroupMemberBody,
  CreateOrganization201,
  CreateOrganizationBody,
  CreateOrganizationGroup201,
  CreateOrganizationGroupBody,
  GetOrganizationPeople200,
  ListOrganizations200,
  RemoveOrganizationGroupMember200
} from '../model';

import { customFetch } from '.././mutator.ts';

export type listOrganizationsResponse200 = {
  data: ListOrganizations200
  status: 200
}

export type listOrganizationsResponseSuccess = (listOrganizationsResponse200) & {
  headers: Headers;
};
;

export type listOrganizationsResponse = (listOrganizationsResponseSuccess)

export const getListOrganizationsUrl = () => {




  return `/api/app/organizations`
}

export const listOrganizations = async ( options?: Parameters<typeof customFetch>[1]): Promise<listOrganizationsResponse> => {

  return customFetch<listOrganizationsResponse>(getListOrganizationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type createOrganizationResponse201 = {
  data: CreateOrganization201
  status: 201
}

export type createOrganizationResponseSuccess = (createOrganizationResponse201) & {
  headers: Headers;
};
;

export type createOrganizationResponse = (createOrganizationResponseSuccess)

export const getCreateOrganizationUrl = () => {




  return `/api/app/organizations`
}

export const createOrganization = async (createOrganizationBody: CreateOrganizationBody, options?: Parameters<typeof customFetch>[1]): Promise<createOrganizationResponse> => {

  return customFetch<createOrganizationResponse>(getCreateOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationBody)
  }
);}


export type getOrganizationPeopleResponse200 = {
  data: GetOrganizationPeople200
  status: 200
}

export type getOrganizationPeopleResponseSuccess = (getOrganizationPeopleResponse200) & {
  headers: Headers;
};
;

export type getOrganizationPeopleResponse = (getOrganizationPeopleResponseSuccess)

export const getGetOrganizationPeopleUrl = (org: string,) => {




  return `/api/app/orgs/${org}/people`
}

export const getOrganizationPeople = async (org: string, options?: Parameters<typeof customFetch>[1]): Promise<getOrganizationPeopleResponse> => {

  return customFetch<getOrganizationPeopleResponse>(getGetOrganizationPeopleUrl(org),
  {
    ...options,
    method: 'GET'


  }
);}


export type createOrganizationGroupResponse201 = {
  data: CreateOrganizationGroup201
  status: 201
}

export type createOrganizationGroupResponseSuccess = (createOrganizationGroupResponse201) & {
  headers: Headers;
};
;

export type createOrganizationGroupResponse = (createOrganizationGroupResponseSuccess)

export const getCreateOrganizationGroupUrl = (org: string,) => {




  return `/api/app/orgs/${org}/groups`
}

export const createOrganizationGroup = async (org: string,
    createOrganizationGroupBody: CreateOrganizationGroupBody, options?: Parameters<typeof customFetch>[1]): Promise<createOrganizationGroupResponse> => {

  return customFetch<createOrganizationGroupResponse>(getCreateOrganizationGroupUrl(org),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationGroupBody)
  }
);}


export type addOrganizationGroupMemberResponse200 = {
  data: AddOrganizationGroupMember200
  status: 200
}

export type addOrganizationGroupMemberResponseSuccess = (addOrganizationGroupMemberResponse200) & {
  headers: Headers;
};
;

export type addOrganizationGroupMemberResponse = (addOrganizationGroupMemberResponseSuccess)

export const getAddOrganizationGroupMemberUrl = (org: string,
    group: string,) => {




  return `/api/app/orgs/${org}/groups/${group}/members`
}

export const addOrganizationGroupMember = async (org: string,
    group: string,
    addOrganizationGroupMemberBody: AddOrganizationGroupMemberBody, options?: Parameters<typeof customFetch>[1]): Promise<addOrganizationGroupMemberResponse> => {

  return customFetch<addOrganizationGroupMemberResponse>(getAddOrganizationGroupMemberUrl(org,group),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addOrganizationGroupMemberBody)
  }
);}


export type removeOrganizationGroupMemberResponse200 = {
  data: RemoveOrganizationGroupMember200
  status: 200
}

export type removeOrganizationGroupMemberResponseSuccess = (removeOrganizationGroupMemberResponse200) & {
  headers: Headers;
};
;

export type removeOrganizationGroupMemberResponse = (removeOrganizationGroupMemberResponseSuccess)

export const getRemoveOrganizationGroupMemberUrl = (org: string,
    group: string,
    username: string,) => {




  return `/api/app/orgs/${org}/groups/${group}/members/${username}`
}

export const removeOrganizationGroupMember = async (org: string,
    group: string,
    username: string, options?: Parameters<typeof customFetch>[1]): Promise<removeOrganizationGroupMemberResponse> => {

  return customFetch<removeOrganizationGroupMemberResponse>(getRemoveOrganizationGroupMemberUrl(org,group,username),
  {
    ...options,
    method: 'DELETE'


  }
);}


